/*
 * Decompiled with CFR 0.151.
 */
package com.google.android.gms.internal.mlkit_vision_common;

import com.google.android.gms.internal.mlkit_vision_common.zzaf;
import com.google.android.gms.internal.mlkit_vision_common.zzah;
import com.google.android.gms.internal.mlkit_vision_common.zzel;
import com.google.android.gms.internal.mlkit_vision_common.zzen;
import com.google.android.gms.internal.mlkit_vision_common.zzeo;

public final class zzag
extends Enum
implements zzel {
    public static final /* enum */ zzag zza;
    private static final /* enum */ zzag zzaa;
    private static final /* enum */ zzag zzab;
    private static final /* enum */ zzag zzac;
    private static final /* enum */ zzag zzad;
    private static final /* enum */ zzag zzae;
    private static final /* enum */ zzag zzaf;
    private static final /* enum */ zzag zzag;
    private static final /* enum */ zzag zzah;
    private static final /* enum */ zzag zzai;
    private static final /* enum */ zzag zzaj;
    private static final /* enum */ zzag zzak;
    private static final /* enum */ zzag zzal;
    private static final /* enum */ zzag zzam;
    private static final /* enum */ zzag zzan;
    private static final /* enum */ zzag zzao;
    private static final /* enum */ zzag zzap;
    private static final /* enum */ zzag zzaq;
    private static final /* enum */ zzag zzar;
    private static final /* enum */ zzag zzas;
    private static final /* enum */ zzag zzat;
    private static final /* enum */ zzag zzau;
    private static final /* enum */ zzag zzav;
    private static final /* enum */ zzag zzaw;
    private static final /* enum */ zzag zzax;
    private static final /* enum */ zzag zzay;
    private static final /* enum */ zzag zzaz;
    private static final /* enum */ zzag zzb;
    private static final /* enum */ zzag zzba;
    private static final /* enum */ zzag zzbb;
    private static final /* enum */ zzag zzbc;
    private static final /* enum */ zzag zzbd;
    private static final /* enum */ zzag zzbe;
    private static final /* enum */ zzag zzbf;
    private static final /* enum */ zzag zzbg;
    private static final /* enum */ zzag zzbh;
    private static final /* enum */ zzag zzbi;
    private static final /* enum */ zzag zzbj;
    private static final /* enum */ zzag zzbk;
    private static final /* enum */ zzag zzbl;
    private static final /* enum */ zzag zzbm;
    private static final /* enum */ zzag zzbn;
    private static final /* enum */ zzag zzbo;
    private static final /* enum */ zzag zzbp;
    private static final /* enum */ zzag zzbq;
    private static final /* enum */ zzag zzbr;
    private static final /* enum */ zzag zzbs;
    private static final /* enum */ zzag zzbt;
    private static final /* enum */ zzag zzbu;
    private static final /* enum */ zzag zzbv;
    private static final /* enum */ zzag zzbw;
    private static final /* enum */ zzag zzbx;
    private static final /* enum */ zzag zzby;
    private static final /* enum */ zzag zzbz;
    private static final /* enum */ zzag zzc;
    private static final /* enum */ zzag zzca;
    private static final /* enum */ zzag zzcb;
    private static final /* enum */ zzag zzcc;
    private static final /* enum */ zzag zzcd;
    private static final /* enum */ zzag zzce;
    private static final /* enum */ zzag zzcf;
    private static final /* enum */ zzag zzcg;
    private static final /* enum */ zzag zzch;
    private static final /* enum */ zzag zzci;
    private static final /* enum */ zzag zzcj;
    private static final /* enum */ zzag zzck;
    private static final /* enum */ zzag zzcl;
    private static final /* enum */ zzag zzcm;
    private static final /* enum */ zzag zzcn;
    private static final /* enum */ zzag zzco;
    private static final /* enum */ zzag zzcp;
    private static final /* enum */ zzag zzcq;
    private static final /* enum */ zzag zzcr;
    private static final /* enum */ zzag zzcs;
    private static final /* enum */ zzag zzct;
    private static final /* enum */ zzag zzcu;
    private static final /* enum */ zzag zzcv;
    private static final /* enum */ zzag zzcw;
    private static final /* enum */ zzag zzcx;
    private static final /* enum */ zzag zzcy;
    private static final /* enum */ zzag zzcz;
    private static final /* enum */ zzag zzd;
    private static final /* enum */ zzag zzda;
    private static final /* enum */ zzag zzdb;
    private static final /* enum */ zzag zzdc;
    private static final /* enum */ zzag zzdd;
    private static final /* enum */ zzag zzde;
    private static final /* enum */ zzag zzdf;
    private static final /* enum */ zzag zzdg;
    private static final /* enum */ zzag zzdh;
    private static final /* enum */ zzag zzdi;
    private static final /* enum */ zzag zzdj;
    private static final /* enum */ zzag zzdk;
    private static final /* enum */ zzag zzdl;
    private static final /* enum */ zzag zzdm;
    private static final /* enum */ zzag zzdn;
    private static final /* enum */ zzag zzdo;
    private static final /* enum */ zzag zzdp;
    private static final /* enum */ zzag zzdq;
    private static final zzeo zzdr;
    private static final /* synthetic */ zzag[] zzdt;
    private static final /* enum */ zzag zze;
    private static final /* enum */ zzag zzf;
    private static final /* enum */ zzag zzg;
    private static final /* enum */ zzag zzh;
    private static final /* enum */ zzag zzi;
    private static final /* enum */ zzag zzj;
    private static final /* enum */ zzag zzk;
    private static final /* enum */ zzag zzl;
    private static final /* enum */ zzag zzm;
    private static final /* enum */ zzag zzn;
    private static final /* enum */ zzag zzo;
    private static final /* enum */ zzag zzp;
    private static final /* enum */ zzag zzq;
    private static final /* enum */ zzag zzr;
    private static final /* enum */ zzag zzs;
    private static final /* enum */ zzag zzt;
    private static final /* enum */ zzag zzu;
    private static final /* enum */ zzag zzv;
    private static final /* enum */ zzag zzw;
    private static final /* enum */ zzag zzx;
    private static final /* enum */ zzag zzy;
    private static final /* enum */ zzag zzz;
    private final int zzds;

    static {
        zzag zzag2;
        Object object = new zzag("UNKNOWN_EVENT", 0, 0);
        zzb = object;
        int n10 = 1;
        object = new zzag("ON_DEVICE_FACE_DETECT", n10, n10);
        zzc = object;
        int n11 = 2;
        object = new zzag("ON_DEVICE_FACE_CREATE", n11, n11);
        zzd = object;
        int n12 = 3;
        object = new zzag("ON_DEVICE_FACE_CLOSE", n12, n12);
        zze = object;
        int n13 = 11;
        object = new zzag("ON_DEVICE_TEXT_DETECT", 4, n13);
        zzf = object;
        int n14 = 12;
        object = new zzag("ON_DEVICE_TEXT_CREATE", 5, n14);
        zzg = object;
        int n15 = 13;
        object = new zzag("ON_DEVICE_TEXT_CLOSE", 6, n15);
        zzh = object;
        int n16 = 21;
        object = new zzag("ON_DEVICE_BARCODE_DETECT", 7, n16);
        zzi = object;
        int n17 = 22;
        object = new zzag("ON_DEVICE_BARCODE_CREATE", 8, n17);
        zzj = object;
        int n18 = 23;
        object = new zzag("ON_DEVICE_BARCODE_CLOSE", 9, n18);
        zzk = object;
        object = new zzag("ON_DEVICE_IMAGE_LABEL_DETECT", 10, 141);
        zzl = object;
        object = new zzag("ON_DEVICE_IMAGE_LABEL_CREATE", n13, 142);
        zzm = object;
        object = new zzag("ON_DEVICE_IMAGE_LABEL_CLOSE", n14, 143);
        zzn = object;
        object = new zzag("ON_DEVICE_IMAGE_LABEL_LOAD", n15, 144);
        zzo = object;
        object = new zzag("ON_DEVICE_SMART_REPLY_DETECT", 14, 151);
        zzp = object;
        object = new zzag("ON_DEVICE_SMART_REPLY_CREATE", 15, 152);
        zzq = object;
        object = new zzag("ON_DEVICE_SMART_REPLY_CLOSE", 16, 153);
        zzr = object;
        object = new zzag("ON_DEVICE_SMART_REPLY_BLACKLIST_UPDATE", 17, 154);
        zzs = object;
        object = new zzag("ON_DEVICE_LANGUAGE_IDENTIFICATION_DETECT", 18, 161);
        zzt = object;
        object = new zzag("ON_DEVICE_LANGUAGE_IDENTIFICATION_CREATE", 19, 162);
        zzu = object;
        object = new zzag("ON_DEVICE_LANGUAGE_IDENTIFICATION_LOAD", 20, 164);
        zzv = object;
        object = new zzag("ON_DEVICE_LANGUAGE_IDENTIFICATION_CLOSE", n16, 163);
        zzw = object;
        object = new zzag("ON_DEVICE_TRANSLATOR_TRANSLATE", n17, 171);
        zzx = object;
        object = new zzag("ON_DEVICE_TRANSLATOR_CREATE", n18, 172);
        zzy = object;
        object = new zzag("ON_DEVICE_TRANSLATOR_LOAD", 24, 173);
        zzz = object;
        object = new zzag("ON_DEVICE_TRANSLATOR_CLOSE", 25, 174);
        zzaa = object;
        object = new zzag("ON_DEVICE_TRANSLATOR_DOWNLOAD", 26, 175);
        zzab = object;
        object = new zzag("ON_DEVICE_ENTITY_EXTRACTION_ANNOTATE", 27, 241);
        zzac = object;
        object = new zzag("ON_DEVICE_ENTITY_EXTRACTION_CREATE", 28, 242);
        zzad = object;
        object = new zzag("ON_DEVICE_ENTITY_EXTRACTION_LOAD", 29, 243);
        zzae = object;
        object = new zzag("ON_DEVICE_ENTITY_EXTRACTION_CLOSE", 30, 244);
        zzaf = object;
        int n19 = 31;
        object = new zzag("ON_DEVICE_ENTITY_EXTRACTION_DOWNLOAD", n19, 245);
        zzag = object;
        int n20 = 32;
        object = new zzag("ON_DEVICE_OBJECT_CREATE", n20, 191);
        zzah = object;
        int n21 = 33;
        object = new zzag("ON_DEVICE_OBJECT_LOAD", n21, 192);
        zzai = object;
        object = new zzag("ON_DEVICE_OBJECT_INFERENCE", 34, 193);
        zzaj = object;
        object = new zzag("ON_DEVICE_OBJECT_CLOSE", 35, 194);
        zzak = object;
        object = new zzag("ON_DEVICE_DI_CREATE", 36, 311);
        zzal = object;
        object = new zzag("ON_DEVICE_DI_LOAD", 37, 312);
        zzam = object;
        object = new zzag("ON_DEVICE_DI_DOWNLOAD", 38, 313);
        zzan = object;
        object = new zzag("ON_DEVICE_DI_RECOGNIZE", 39, 314);
        zzao = object;
        object = new zzag("ON_DEVICE_DI_CLOSE", 40, 315);
        zzap = object;
        n18 = 41;
        object = new zzag("ON_DEVICE_POSE_CREATE", n18, 321);
        zzaq = object;
        int n22 = 42;
        object = new zzag("ON_DEVICE_POSE_LOAD", n22, 322);
        zzar = object;
        n17 = 43;
        object = new zzag("ON_DEVICE_POSE_INFERENCE", n17, 323);
        zzas = object;
        object = new zzag("ON_DEVICE_POSE_CLOSE", 44, 324);
        zzat = object;
        object = new zzag("ON_DEVICE_SEGMENTATION_CREATE", 45, 331);
        zzau = object;
        object = new zzag("ON_DEVICE_SEGMENTATION_LOAD", 46, 332);
        zzav = object;
        object = new zzag("ON_DEVICE_SEGMENTATION_INFERENCE", 47, 333);
        zzaw = object;
        object = new zzag("ON_DEVICE_SEGMENTATION_CLOSE", 48, 334);
        zzax = object;
        object = new zzag("CUSTOM_OBJECT_CREATE", 49, 341);
        zzay = object;
        object = new zzag("CUSTOM_OBJECT_LOAD", 50, 342);
        zzaz = object;
        n15 = 51;
        object = new zzag("CUSTOM_OBJECT_INFERENCE", n15, 343);
        zzba = object;
        n16 = 52;
        object = new zzag("CUSTOM_OBJECT_CLOSE", n16, 344);
        zzbb = object;
        n14 = 53;
        object = new zzag("CUSTOM_IMAGE_LABEL_CREATE", n14, 351);
        zzbc = object;
        object = new zzag("CUSTOM_IMAGE_LABEL_LOAD", 54, 352);
        zzbd = object;
        object = new zzag("CUSTOM_IMAGE_LABEL_DETECT", 55, 353);
        zzbe = object;
        object = new zzag("CUSTOM_IMAGE_LABEL_CLOSE", 56, 354);
        zzbf = object;
        object = new zzag("CLOUD_FACE_DETECT", 57, n19);
        zzbg = object;
        object = new zzag("CLOUD_FACE_CREATE", 58, n20);
        zzbh = object;
        object = new zzag("CLOUD_FACE_CLOSE", 59, n21);
        zzbi = object;
        object = new zzag("CLOUD_CROP_HINTS_CREATE", 60, n18);
        zzbj = object;
        n12 = 61;
        object = new zzag("CLOUD_CROP_HINTS_DETECT", n12, n22);
        zzbk = object;
        n13 = 62;
        object = new zzag("CLOUD_CROP_HINTS_CLOSE", n13, n17);
        zzbl = object;
        n17 = 63;
        object = new zzag("CLOUD_DOCUMENT_TEXT_CREATE", n17, n15);
        zzbm = object;
        object = new zzag("CLOUD_DOCUMENT_TEXT_DETECT", 64, n16);
        zzbn = object;
        object = new zzag("CLOUD_DOCUMENT_TEXT_CLOSE", 65, n14);
        zzbo = object;
        object = new zzag("CLOUD_IMAGE_PROPERTIES_CREATE", 66, n12);
        zzbp = object;
        object = new zzag("CLOUD_IMAGE_PROPERTIES_DETECT", 67, n13);
        zzbq = object;
        object = new zzag("CLOUD_IMAGE_PROPERTIES_CLOSE", 68, n17);
        zzbr = object;
        object = new zzag("CLOUD_IMAGE_LABEL_CREATE", 69, 71);
        zzbs = object;
        object = new zzag("CLOUD_IMAGE_LABEL_DETECT", 70, 72);
        zzbt = object;
        object = new zzag("CLOUD_IMAGE_LABEL_CLOSE", 71, 73);
        zzbu = object;
        object = new zzag("CLOUD_LANDMARK_CREATE", 72, 81);
        zzbv = object;
        object = new zzag("CLOUD_LANDMARK_DETECT", 73, 82);
        zzbw = object;
        object = new zzag("CLOUD_LANDMARK_CLOSE", 74, 83);
        zzbx = object;
        object = new zzag("CLOUD_LOGO_CREATE", 75, 91);
        zzby = object;
        object = new zzag("CLOUD_LOGO_DETECT", 76, 92);
        zzbz = object;
        object = new zzag("CLOUD_LOGO_CLOSE", 77, 93);
        zzca = object;
        object = new zzag("CLOUD_SAFE_SEARCH_CREATE", 78, 111);
        zzcb = object;
        object = new zzag("CLOUD_SAFE_SEARCH_DETECT", 79, 112);
        zzcc = object;
        object = new zzag("CLOUD_SAFE_SEARCH_CLOSE", 80, 113);
        zzcd = object;
        object = new zzag("CLOUD_TEXT_CREATE", 81, 121);
        zzce = object;
        object = new zzag("CLOUD_TEXT_DETECT", 82, 122);
        zzcf = object;
        object = new zzag("CLOUD_TEXT_CLOSE", 83, 123);
        zzcg = object;
        object = new zzag("CLOUD_WEB_SEARCH_CREATE", 84, 131);
        zzch = object;
        object = new zzag("CLOUD_WEB_SEARCH_DETECT", 85, 132);
        zzci = object;
        object = new zzag("CLOUD_WEB_SEARCH_CLOSE", 86, 133);
        zzcj = object;
        object = new zzag("CUSTOM_MODEL_RUN", 87, 102);
        zzck = object;
        object = new zzag("CUSTOM_MODEL_CREATE", 88, 103);
        zzcl = object;
        object = new zzag("CUSTOM_MODEL_CLOSE", 89, 104);
        zzcm = object;
        object = new zzag("CUSTOM_MODEL_LOAD", 90, 105);
        zzcn = object;
        object = new zzag("AUTOML_IMAGE_LABELING_RUN", 91, 181);
        zzco = object;
        object = new zzag("AUTOML_IMAGE_LABELING_CREATE", 92, 182);
        zzcp = object;
        object = new zzag("AUTOML_IMAGE_LABELING_CLOSE", 93, 183);
        zzcq = object;
        object = new zzag("AUTOML_IMAGE_LABELING_LOAD", 94, 184);
        zzcr = object;
        object = new zzag("MODEL_DOWNLOAD", 95, 100);
        zzcs = object;
        object = new zzag("MODEL_UPDATE", 96, 101);
        zzct = object;
        object = new zzag("REMOTE_MODEL_IS_DOWNLOADED", 97, 251);
        zzcu = object;
        object = new zzag("REMOTE_MODEL_DELETE_ON_DEVICE", 98, 252);
        zzcv = object;
        object = new zzag("ACCELERATION_ANALYTICS", 99, 260);
        zzcw = object;
        object = new zzag("AGGREGATED_AUTO_ML_IMAGE_LABELING_INFERENCE", 100, 200);
        zzcx = object;
        object = new zzag("AGGREGATED_CUSTOM_MODEL_INFERENCE", 101, 201);
        zzcy = object;
        object = new zzag("AGGREGATED_ON_DEVICE_BARCODE_DETECTION", 102, 202);
        zzcz = object;
        object = new zzag("AGGREGATED_ON_DEVICE_FACE_DETECTION", 103, 203);
        zzda = object;
        object = new zzag("AGGREGATED_ON_DEVICE_IMAGE_LABEL_DETECTION", 104, 204);
        zzdb = object;
        object = new zzag("AGGREGATED_ON_DEVICE_OBJECT_INFERENCE", 105, 205);
        zzdc = object;
        object = new zzag("AGGREGATED_ON_DEVICE_TEXT_DETECTION", 106, 206);
        zzdd = object;
        object = new zzag("AGGREGATED_ON_DEVICE_POSE_DETECTION", 107, 207);
        zzde = object;
        object = new zzag("AGGREGATED_ON_DEVICE_SEGMENTATION", 108, 208);
        zzdf = object;
        object = new zzag("AGGREGATED_CUSTOM_OBJECT_INFERENCE", 109, 209);
        zzdg = object;
        object = new zzag("AGGREGATED_CUSTOM_IMAGE_LABEL_DETECTION", 110, 210);
        zzdh = object;
        object = new zzag("REMOTE_CONFIG_FETCH", 111, 271);
        zzdi = object;
        object = new zzag("REMOTE_CONFIG_ACTIVATE", 112, 272);
        zzdj = object;
        object = new zzag("REMOTE_CONFIG_FRC_FETCH", 113, 281);
        zzdk = object;
        object = new zzag("INSTALLATION_ID_INIT", 114, 291);
        zzdl = object;
        object = new zzag("INSTALLATION_ID_REGISTER_NEW_ID", 115, 292);
        zzdm = object;
        object = new zzag("INSTALLATION_ID_REFRESH_TEMPORARY_TOKEN", 116, 293);
        zzdn = object;
        object = new zzag("INSTALLATION_ID_FIS_CREATE_INSTALLATION", 117, 301);
        zzdo = object;
        object = new zzag("INSTALLATION_ID_FIS_GENERATE_AUTH_TOKEN", 118, 302);
        zzdp = object;
        object = new zzag("INPUT_IMAGE_CONSTRUCTION", 119, 361);
        zza = object;
        object = new zzag("HANDLE_LEAKED", 120, 371);
        zzdq = object;
        object = new zzag[121];
        object[0] = zzag2 = zzb;
        object[n10] = zzag2 = zzc;
        object[n11] = zzag2 = zzd;
        object[3] = zzag2 = zze;
        object[4] = zzag2 = zzf;
        object[5] = zzag2 = zzg;
        object[6] = zzag2 = zzh;
        object[7] = zzag2 = zzi;
        object[8] = zzag2 = zzj;
        object[9] = zzag2 = zzk;
        object[10] = zzag2 = zzl;
        object[11] = zzag2 = zzm;
        object[12] = zzag2 = zzn;
        object[13] = zzag2 = zzo;
        object[14] = zzag2 = zzp;
        object[15] = zzag2 = zzq;
        object[16] = zzag2 = zzr;
        object[17] = zzag2 = zzs;
        object[18] = zzag2 = zzt;
        object[19] = zzag2 = zzu;
        object[20] = zzag2 = zzv;
        object[21] = zzag2 = zzw;
        object[22] = zzag2 = zzx;
        object[23] = zzag2 = zzy;
        object[24] = zzag2 = zzz;
        object[25] = zzag2 = zzaa;
        object[26] = zzag2 = zzab;
        object[27] = zzag2 = zzac;
        object[28] = zzag2 = zzad;
        object[29] = zzag2 = zzae;
        object[30] = zzag2 = zzaf;
        object[n19] = zzag2 = zzag;
        object[n20] = zzag2 = zzah;
        object[n21] = zzag2 = zzai;
        object[34] = zzag2 = zzaj;
        object[35] = zzag2 = zzak;
        object[36] = zzag2 = zzal;
        object[37] = zzag2 = zzam;
        object[38] = zzag2 = zzan;
        object[39] = zzag2 = zzao;
        object[40] = zzag2 = zzap;
        object[n18] = zzag2 = zzaq;
        object[n22] = zzag2 = zzar;
        object[43] = zzag2 = zzas;
        object[44] = zzag2 = zzat;
        object[45] = zzag2 = zzau;
        object[46] = zzag2 = zzav;
        object[47] = zzag2 = zzaw;
        object[48] = zzag2 = zzax;
        object[49] = zzag2 = zzay;
        object[50] = zzag2 = zzaz;
        object[51] = zzag2 = zzba;
        object[n16] = zzag2 = zzbb;
        object[n14] = zzag2 = zzbc;
        object[54] = zzag2 = zzbd;
        object[55] = zzag2 = zzbe;
        object[56] = zzag2 = zzbf;
        object[57] = zzag2 = zzbg;
        object[58] = zzag2 = zzbh;
        object[59] = zzag2 = zzbi;
        object[60] = zzag2 = zzbj;
        object[n12] = zzag2 = zzbk;
        object[n13] = zzag2 = zzbl;
        object[63] = zzag2 = zzbm;
        object[64] = zzag2 = zzbn;
        object[65] = zzag2 = zzbo;
        object[66] = zzag2 = zzbp;
        object[67] = zzag2 = zzbq;
        object[68] = zzag2 = zzbr;
        object[69] = zzag2 = zzbs;
        object[70] = zzag2 = zzbt;
        object[71] = zzag2 = zzbu;
        object[72] = zzag2 = zzbv;
        object[73] = zzag2 = zzbw;
        object[74] = zzag2 = zzbx;
        object[75] = zzag2 = zzby;
        object[76] = zzag2 = zzbz;
        object[77] = zzag2 = zzca;
        object[78] = zzag2 = zzcb;
        object[79] = zzag2 = zzcc;
        object[80] = zzag2 = zzcd;
        object[81] = zzag2 = zzce;
        object[82] = zzag2 = zzcf;
        object[83] = zzag2 = zzcg;
        object[84] = zzag2 = zzch;
        object[85] = zzag2 = zzci;
        object[86] = zzag2 = zzcj;
        object[87] = zzag2 = zzck;
        object[88] = zzag2 = zzcl;
        object[89] = zzag2 = zzcm;
        object[90] = zzag2 = zzcn;
        object[91] = zzag2 = zzco;
        object[92] = zzag2 = zzcp;
        object[93] = zzag2 = zzcq;
        object[94] = zzag2 = zzcr;
        object[95] = zzag2 = zzcs;
        object[96] = zzag2 = zzct;
        object[97] = zzag2 = zzcu;
        object[98] = zzag2 = zzcv;
        object[99] = zzag2 = zzcw;
        object[100] = zzag2 = zzcx;
        object[101] = zzag2 = zzcy;
        object[102] = zzag2 = zzcz;
        object[103] = zzag2 = zzda;
        object[104] = zzag2 = zzdb;
        object[105] = zzag2 = zzdc;
        object[106] = zzag2 = zzdd;
        object[107] = zzag2 = zzde;
        object[108] = zzag2 = zzdf;
        object[109] = zzag2 = zzdg;
        object[110] = zzag2 = zzdh;
        object[111] = zzag2 = zzdi;
        object[112] = zzag2 = zzdj;
        object[113] = zzag2 = zzdk;
        object[114] = zzag2 = zzdl;
        object[115] = zzag2 = zzdm;
        object[116] = zzag2 = zzdn;
        object[117] = zzag2 = zzdo;
        object[118] = zzag2 = zzdp;
        object[119] = zzag2 = zza;
        object[120] = zzag2 = zzdq;
        zzdt = object;
        zzdr = object = new zzaf();
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private zzag() {
        void var3_1;
        void var2_-1;
        void var1_-1;
        this.zzds = var3_1;
    }

    public static zzag[] values() {
        return (zzag[])zzdt.clone();
    }

    public static zzen zzb() {
        return com.google.android.gms.internal.mlkit_vision_common.zzah.zza;
    }

    public final String toString() {
        StringBuilder stringBuilder = new StringBuilder("<");
        String string2 = zzag.class.getName();
        stringBuilder.append(string2);
        stringBuilder.append('@');
        string2 = Integer.toHexString(System.identityHashCode(this));
        stringBuilder.append(string2);
        stringBuilder.append(" number=");
        int n10 = this.zzds;
        stringBuilder.append(n10);
        stringBuilder.append(" name=");
        string2 = this.name();
        stringBuilder.append(string2);
        stringBuilder.append('>');
        return stringBuilder.toString();
    }

    public final int zza() {
        return this.zzds;
    }
}

