/*
 * Decompiled with CFR 0.151.
 */
package com.google.android.gms.internal.mlkit_vision_common;

import com.google.android.gms.internal.mlkit_vision_common.zzef;
import com.google.android.gms.internal.mlkit_vision_common.zzei;
import com.google.android.gms.internal.mlkit_vision_common.zzet;
import java.lang.reflect.Type;

public final class zzeg
extends Enum {
    public static final /* enum */ zzeg zza;
    private static final /* enum */ zzeg zzaa;
    private static final /* enum */ zzeg zzab;
    private static final /* enum */ zzeg zzac;
    private static final /* enum */ zzeg zzad;
    private static final /* enum */ zzeg zzae;
    private static final /* enum */ zzeg zzaf;
    private static final /* enum */ zzeg zzag;
    private static final /* enum */ zzeg zzah;
    private static final /* enum */ zzeg zzai;
    private static final /* enum */ zzeg zzaj;
    private static final /* enum */ zzeg zzak;
    private static final /* enum */ zzeg zzal;
    private static final /* enum */ zzeg zzam;
    private static final /* enum */ zzeg zzan;
    private static final /* enum */ zzeg zzao;
    private static final /* enum */ zzeg zzap;
    private static final /* enum */ zzeg zzaq;
    private static final /* enum */ zzeg zzar;
    private static final /* enum */ zzeg zzas;
    private static final /* enum */ zzeg zzat;
    private static final /* enum */ zzeg zzau;
    private static final /* enum */ zzeg zzav;
    private static final /* enum */ zzeg zzaw;
    private static final /* enum */ zzeg zzax;
    private static final /* enum */ zzeg zzay;
    public static final /* enum */ zzeg zzb;
    private static final zzeg[] zzbe;
    private static final Type[] zzbf;
    private static final /* synthetic */ zzeg[] zzbg;
    private static final /* enum */ zzeg zzc;
    private static final /* enum */ zzeg zzd;
    private static final /* enum */ zzeg zze;
    private static final /* enum */ zzeg zzf;
    private static final /* enum */ zzeg zzg;
    private static final /* enum */ zzeg zzh;
    private static final /* enum */ zzeg zzi;
    private static final /* enum */ zzeg zzj;
    private static final /* enum */ zzeg zzk;
    private static final /* enum */ zzeg zzl;
    private static final /* enum */ zzeg zzm;
    private static final /* enum */ zzeg zzn;
    private static final /* enum */ zzeg zzo;
    private static final /* enum */ zzeg zzp;
    private static final /* enum */ zzeg zzq;
    private static final /* enum */ zzeg zzr;
    private static final /* enum */ zzeg zzs;
    private static final /* enum */ zzeg zzt;
    private static final /* enum */ zzeg zzu;
    private static final /* enum */ zzeg zzv;
    private static final /* enum */ zzeg zzw;
    private static final /* enum */ zzeg zzx;
    private static final /* enum */ zzeg zzy;
    private static final /* enum */ zzeg zzz;
    private final zzet zzaz;
    private final int zzba;
    private final zzei zzbb;
    private final Class zzbc;
    private final boolean zzbd;

    static {
        zzeg[] zzegArray;
        zzei zzei2 = zzei.zza;
        Enum enum_ = zzet.zze;
        zzeg zzeg22 = null;
        zzeg[] zzegArray2 = zzegArray;
        zzeg[] zzegArray3 = zzei2;
        zzet zzet2 = enum_;
        zzegArray = new zzeg("DOUBLE", 0, 0, zzei2, (zzet)enum_);
        zzc = zzegArray;
        Object object = zzet.zzd;
        zzegArray2 = zzegArray;
        zzet2 = object;
        zzegArray = new zzeg("FLOAT", 1, 1, zzei2, object);
        zzd = zzegArray;
        zzet zzet3 = zzet.zzc;
        zzegArray2 = zzegArray;
        zzet2 = zzet3;
        zzegArray = new zzeg("INT64", 2, 2, zzei2, zzet3);
        zze = zzegArray;
        zzegArray2 = zzegArray;
        zzegArray = new zzeg("UINT64", 3, 3, zzei2, zzet3);
        zzf = zzegArray;
        zzet zzet4 = zzet.zzb;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("INT32", 4, 4, zzei2, zzet4);
        zzg = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet3;
        zzegArray = new zzeg("FIXED64", 5, 5, zzei2, zzet3);
        zzh = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("FIXED32", 6, 6, zzei2, zzet4);
        zzi = zzegArray;
        Enum enum_2 = zzet.zzf;
        zzegArray2 = zzegArray;
        zzet2 = enum_2;
        zzegArray = new zzeg("BOOL", 7, 7, zzei2, (zzet)enum_2);
        zzj = zzegArray;
        Enum enum_3 = zzet.zzg;
        zzegArray2 = zzegArray;
        zzet2 = enum_3;
        zzegArray = new zzeg("STRING", 8, 8, zzei2, (zzet)enum_3);
        zzk = zzegArray;
        zzet zzet5 = zzet.zzj;
        zzegArray2 = zzegArray;
        zzet2 = zzet5;
        zzegArray = new zzeg("MESSAGE", 9, 9, zzei2, zzet5);
        zzl = zzegArray;
        zzet zzet6 = zzet.zzh;
        zzegArray2 = zzegArray;
        zzet2 = zzet6;
        zzegArray = new zzeg("BYTES", 10, 10, zzei2, zzet6);
        zzm = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("UINT32", 11, 11, zzei2, zzet4);
        zzn = zzegArray;
        zzet zzet7 = zzet.zzi;
        zzegArray2 = zzegArray;
        zzet2 = zzet7;
        zzegArray = new zzeg("ENUM", 12, 12, zzei2, zzet7);
        zzo = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("SFIXED32", 13, 13, zzei2, zzet4);
        zzp = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet3;
        zzegArray = new zzeg("SFIXED64", 14, 14, zzei2, zzet3);
        zzq = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("SINT32", 15, 15, zzei2, zzet4);
        zzr = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet3;
        zzegArray = new zzeg("SINT64", 16, 16, zzei2, zzet3);
        zzs = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet5;
        zzegArray = new zzeg("GROUP", 17, 17, zzei2, zzet5);
        zzt = zzegArray;
        zzei2 = zzei.zzb;
        zzegArray2 = zzegArray;
        zzegArray3 = zzei2;
        zzet2 = enum_;
        zzegArray = new zzeg("DOUBLE_LIST", 18, 18, zzei2, (zzet)enum_);
        zzu = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = object;
        zzegArray = new zzeg("FLOAT_LIST", 19, 19, zzei2, object);
        zzv = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet3;
        zzegArray = new zzeg("INT64_LIST", 20, 20, zzei2, zzet3);
        zzw = zzegArray;
        zzegArray2 = zzegArray;
        zzegArray = new zzeg("UINT64_LIST", 21, 21, zzei2, zzet3);
        zzx = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("INT32_LIST", 22, 22, zzei2, zzet4);
        zzy = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet3;
        zzegArray = new zzeg("FIXED64_LIST", 23, 23, zzei2, zzet3);
        zzz = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("FIXED32_LIST", 24, 24, zzei2, zzet4);
        zzaa = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = enum_2;
        zzegArray = new zzeg("BOOL_LIST", 25, 25, zzei2, (zzet)enum_2);
        zzab = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = enum_3;
        zzegArray = new zzeg("STRING_LIST", 26, 26, zzei2, (zzet)enum_3);
        zzac = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet5;
        zzegArray = new zzeg("MESSAGE_LIST", 27, 27, zzei2, zzet5);
        zzad = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet6;
        zzegArray = new zzeg("BYTES_LIST", 28, 28, zzei2, zzet6);
        zzae = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("UINT32_LIST", 29, 29, zzei2, zzet4);
        zzaf = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet7;
        zzegArray = new zzeg("ENUM_LIST", 30, 30, zzei2, zzet7);
        zzag = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("SFIXED32_LIST", 31, 31, zzei2, zzet4);
        zzah = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet3;
        zzegArray = new zzeg("SFIXED64_LIST", 32, 32, zzei2, zzet3);
        zzai = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("SINT32_LIST", 33, 33, zzei2, zzet4);
        zzaj = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet3;
        zzegArray = new zzeg("SINT64_LIST", 34, 34, zzei2, zzet3);
        zzak = zzegArray;
        enum_3 = zzei.zzc;
        zzegArray2 = zzegArray;
        zzegArray3 = enum_3;
        zzet2 = enum_;
        zzegArray = new zzeg("DOUBLE_LIST_PACKED", 35, 35, (zzei)enum_3, (zzet)enum_);
        zza = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = object;
        zzegArray = new zzeg("FLOAT_LIST_PACKED", 36, 36, (zzei)enum_3, object);
        zzal = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet3;
        zzegArray = new zzeg("INT64_LIST_PACKED", 37, 37, (zzei)enum_3, zzet3);
        zzam = zzegArray;
        zzegArray2 = zzegArray;
        zzegArray = new zzeg("UINT64_LIST_PACKED", 38, 38, (zzei)enum_3, zzet3);
        zzan = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("INT32_LIST_PACKED", 39, 39, (zzei)enum_3, zzet4);
        zzao = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet3;
        zzegArray = new zzeg("FIXED64_LIST_PACKED", 40, 40, (zzei)enum_3, zzet3);
        zzap = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("FIXED32_LIST_PACKED", 41, 41, (zzei)enum_3, zzet4);
        zzaq = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = enum_2;
        zzegArray = new zzeg("BOOL_LIST_PACKED", 42, 42, (zzei)enum_3, (zzet)enum_2);
        zzar = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("UINT32_LIST_PACKED", 43, 43, (zzei)enum_3, zzet4);
        zzas = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet7;
        zzegArray = new zzeg("ENUM_LIST_PACKED", 44, 44, (zzei)enum_3, zzet7);
        zzat = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = zzet4;
        zzegArray = new zzeg("SFIXED32_LIST_PACKED", 45, 45, (zzei)enum_3, zzet4);
        zzau = zzegArray;
        enum_ = zzet.zzc;
        zzegArray2 = zzegArray;
        zzet2 = enum_;
        zzegArray = new zzeg("SFIXED64_LIST_PACKED", 46, 46, (zzei)enum_3, (zzet)enum_);
        zzav = zzegArray;
        zzet2 = zzet.zzb;
        zzegArray2 = zzegArray;
        zzegArray = new zzeg("SINT32_LIST_PACKED", 47, 47, (zzei)enum_3, zzet2);
        zzaw = zzegArray;
        zzegArray2 = zzegArray;
        zzet2 = enum_;
        zzegArray = new zzeg("SINT64_LIST_PACKED", 48, 48, (zzei)enum_3, (zzet)enum_);
        zzb = zzegArray;
        zzegArray2 = zzegArray;
        zzegArray3 = zzei2;
        zzet2 = zzet5;
        zzegArray = new zzeg("GROUP_LIST", 49, 49, zzei2, zzet5);
        zzax = zzegArray;
        enum_2 = zzei.zzd;
        enum_3 = zzet.zza;
        object = "MAP";
        int n10 = 50;
        int n11 = 50;
        enum_ = zzegArray2;
        zzegArray2 = new zzeg((String)object, n10, n11, (zzei)enum_2, (zzet)enum_3);
        zzay = zzegArray2;
        int n12 = 51;
        zzegArray2 = new zzeg[n12];
        zzeg[] zzegArray4 = zzc;
        zzegArray2[0] = zzegArray4;
        zzegArray4 = zzd;
        zzegArray2[1] = zzegArray4;
        zzegArray4 = zze;
        zzegArray2[2] = zzegArray4;
        zzegArray4 = zzf;
        zzegArray2[3] = zzegArray4;
        zzegArray4 = zzg;
        zzegArray2[4] = zzegArray4;
        zzegArray4 = zzh;
        zzegArray2[5] = zzegArray4;
        zzegArray4 = zzi;
        zzegArray2[6] = zzegArray4;
        zzegArray4 = zzj;
        zzegArray2[7] = zzegArray4;
        zzegArray4 = zzk;
        zzegArray2[8] = zzegArray4;
        zzegArray4 = zzl;
        zzegArray2[9] = zzegArray4;
        zzegArray4 = zzm;
        zzegArray2[10] = zzegArray4;
        zzegArray4 = zzn;
        zzegArray2[11] = zzegArray4;
        zzegArray4 = zzo;
        zzegArray2[12] = zzegArray4;
        zzegArray4 = zzp;
        zzegArray2[13] = zzegArray4;
        zzegArray4 = zzq;
        zzegArray2[14] = zzegArray4;
        zzegArray4 = zzr;
        zzegArray2[15] = zzegArray4;
        zzegArray4 = zzs;
        zzegArray2[16] = zzegArray4;
        zzegArray4 = zzt;
        zzegArray2[17] = zzegArray4;
        zzegArray4 = zzu;
        zzegArray2[18] = zzegArray4;
        zzegArray4 = zzv;
        zzegArray2[19] = zzegArray4;
        zzegArray4 = zzw;
        zzegArray2[20] = zzegArray4;
        zzegArray4 = zzx;
        zzegArray2[21] = zzegArray4;
        zzegArray4 = zzy;
        zzegArray2[22] = zzegArray4;
        zzegArray4 = zzz;
        zzegArray2[23] = zzegArray4;
        zzegArray4 = zzaa;
        zzegArray2[24] = zzegArray4;
        zzegArray4 = zzab;
        zzegArray2[25] = zzegArray4;
        zzegArray4 = zzac;
        zzegArray2[26] = zzegArray4;
        zzegArray4 = zzad;
        zzegArray2[27] = zzegArray4;
        zzegArray4 = zzae;
        zzegArray2[28] = zzegArray4;
        zzegArray4 = zzaf;
        zzegArray2[29] = zzegArray4;
        zzegArray4 = zzag;
        zzegArray2[30] = zzegArray4;
        zzegArray4 = zzah;
        zzegArray2[31] = zzegArray4;
        zzegArray4 = zzai;
        zzegArray2[32] = zzegArray4;
        zzegArray4 = zzaj;
        zzegArray2[33] = zzegArray4;
        zzegArray4 = zzak;
        zzegArray2[34] = zzegArray4;
        zzegArray4 = zza;
        zzegArray2[35] = zzegArray4;
        zzegArray4 = zzal;
        zzegArray2[36] = zzegArray4;
        zzegArray4 = zzam;
        zzegArray2[37] = zzegArray4;
        zzegArray4 = zzan;
        zzegArray2[38] = zzegArray4;
        zzegArray4 = zzao;
        zzegArray2[39] = zzegArray4;
        zzegArray4 = zzap;
        zzegArray2[40] = zzegArray4;
        zzegArray4 = zzaq;
        zzegArray2[41] = zzegArray4;
        zzegArray4 = zzar;
        zzegArray2[42] = zzegArray4;
        zzegArray4 = zzas;
        zzegArray2[43] = zzegArray4;
        zzegArray4 = zzat;
        zzegArray2[44] = zzegArray4;
        zzegArray4 = zzau;
        zzegArray2[45] = zzegArray4;
        zzegArray4 = zzav;
        zzegArray2[46] = zzegArray4;
        zzegArray4 = zzaw;
        zzegArray2[47] = zzegArray4;
        zzegArray4 = zzb;
        zzegArray2[48] = zzegArray4;
        zzegArray4 = zzax;
        zzegArray2[49] = zzegArray4;
        zzegArray4 = zzay;
        int n13 = 50;
        zzegArray2[n13] = zzegArray4;
        zzbg = zzegArray2;
        zzbf = new Type[0];
        zzegArray2 = zzeg.values();
        zzegArray4 = new zzeg[zzegArray2.length];
        zzbe = zzegArray4;
        for (zzeg zzeg22 : zzegArray2) {
            zzegArray3 = zzbe;
            int n14 = zzeg22.zzba;
            zzegArray3[n14] = zzeg22;
        }
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private zzeg(zzet zzet2) {
        int n11;
        int n12;
        void var5_4;
        int[] nArray;
        void var2_-1;
        void var1_-1;
        this.zzba = (int)zzet2;
        this.zzbb = nArray;
        this.zzaz = var5_4;
        Object object = zzef.zza;
        int n13 = nArray.ordinal();
        int n14 = object[n13];
        n13 = 2;
        int n15 = 1;
        if (n14 != n15) {
            if (n14 != n13) {
                n14 = 0;
                object = null;
                this.zzbc = null;
            } else {
                object = var5_4.zza();
                this.zzbc = object;
            }
        } else {
            object = var5_4.zza();
            this.zzbc = object;
        }
        n14 = 0;
        object = null;
        zzei zzei2 = zzei.zza;
        if (nArray != zzei2 || (n12 = (nArray = zzef.zzb)[n11 = var5_4.ordinal()]) == n15 || n12 == n13 || n12 == (n13 = 3)) {
            n15 = 0;
        }
        this.zzbd = n15;
    }

    public static zzeg[] values() {
        return (zzeg[])zzbg.clone();
    }

    public final int zza() {
        return this.zzba;
    }
}

