/*
 * Decompiled with CFR 0.151.
 */
package com.google.android.gms.internal.vision;

import com.google.android.gms.internal.vision.zzhx;
import com.google.android.gms.internal.vision.zzia;
import com.google.android.gms.internal.vision.zzip;
import java.lang.reflect.Type;

public final class zzhy
extends Enum {
    private static final /* enum */ zzhy zzvg;
    private static final /* enum */ zzhy zzvh;
    private static final /* enum */ zzhy zzvi;
    private static final /* enum */ zzhy zzvj;
    private static final /* enum */ zzhy zzvk;
    private static final /* enum */ zzhy zzvl;
    private static final /* enum */ zzhy zzvm;
    private static final /* enum */ zzhy zzvn;
    private static final /* enum */ zzhy zzvo;
    private static final /* enum */ zzhy zzvp;
    private static final /* enum */ zzhy zzvq;
    private static final /* enum */ zzhy zzvr;
    private static final /* enum */ zzhy zzvs;
    private static final /* enum */ zzhy zzvt;
    private static final /* enum */ zzhy zzvu;
    private static final /* enum */ zzhy zzvv;
    private static final /* enum */ zzhy zzvw;
    private static final /* enum */ zzhy zzvx;
    private static final /* enum */ zzhy zzvy;
    private static final /* enum */ zzhy zzvz;
    private static final /* enum */ zzhy zzwa;
    private static final /* enum */ zzhy zzwb;
    private static final /* enum */ zzhy zzwc;
    private static final /* enum */ zzhy zzwd;
    private static final /* enum */ zzhy zzwe;
    private static final /* enum */ zzhy zzwf;
    private static final /* enum */ zzhy zzwg;
    private static final /* enum */ zzhy zzwh;
    private static final /* enum */ zzhy zzwi;
    private static final /* enum */ zzhy zzwj;
    private static final /* enum */ zzhy zzwk;
    private static final /* enum */ zzhy zzwl;
    private static final /* enum */ zzhy zzwm;
    private static final /* enum */ zzhy zzwn;
    private static final /* enum */ zzhy zzwo;
    public static final /* enum */ zzhy zzwp;
    private static final /* enum */ zzhy zzwq;
    private static final /* enum */ zzhy zzwr;
    private static final /* enum */ zzhy zzws;
    private static final /* enum */ zzhy zzwt;
    private static final /* enum */ zzhy zzwu;
    private static final /* enum */ zzhy zzwv;
    private static final /* enum */ zzhy zzww;
    private static final /* enum */ zzhy zzwx;
    private static final /* enum */ zzhy zzwy;
    private static final /* enum */ zzhy zzwz;
    private static final /* enum */ zzhy zzxa;
    private static final /* enum */ zzhy zzxb;
    public static final /* enum */ zzhy zzxc;
    private static final /* enum */ zzhy zzxd;
    private static final /* enum */ zzhy zzxe;
    private static final zzhy[] zzxj;
    private static final Type[] zzxk;
    private static final /* synthetic */ zzhy[] zzxl;
    private final int id;
    private final zzip zzxf;
    private final zzia zzxg;
    private final Class zzxh;
    private final boolean zzxi;

    static {
        zzhy[] zzhyArray;
        zzia zzia2 = zzia.zzxo;
        Enum enum_ = zzip.zzzc;
        zzhy zzhy22 = null;
        zzhy[] zzhyArray2 = zzhyArray;
        zzhy[] zzhyArray3 = zzia2;
        zzip zzip2 = enum_;
        zzhyArray = new zzhy("DOUBLE", 0, 0, zzia2, (zzip)enum_);
        zzvg = zzhyArray;
        Object object = zzip.zzzb;
        zzhyArray2 = zzhyArray;
        zzip2 = object;
        zzhyArray = new zzhy("FLOAT", 1, 1, zzia2, object);
        zzvh = zzhyArray;
        zzip zzip3 = zzip.zzza;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip3;
        zzhyArray = new zzhy("INT64", 2, 2, zzia2, zzip3);
        zzvi = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzhyArray = new zzhy("UINT64", 3, 3, zzia2, zzip3);
        zzvj = zzhyArray;
        zzip zzip4 = zzip.zzyz;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("INT32", 4, 4, zzia2, zzip4);
        zzvk = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip3;
        zzhyArray = new zzhy("FIXED64", 5, 5, zzia2, zzip3);
        zzvl = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("FIXED32", 6, 6, zzia2, zzip4);
        zzvm = zzhyArray;
        Enum enum_2 = zzip.zzzd;
        zzhyArray2 = zzhyArray;
        zzip2 = enum_2;
        zzhyArray = new zzhy("BOOL", 7, 7, zzia2, (zzip)enum_2);
        zzvn = zzhyArray;
        Enum enum_3 = zzip.zzze;
        zzhyArray2 = zzhyArray;
        zzip2 = enum_3;
        zzhyArray = new zzhy("STRING", 8, 8, zzia2, (zzip)enum_3);
        zzvo = zzhyArray;
        zzip zzip5 = zzip.zzzh;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip5;
        zzhyArray = new zzhy("MESSAGE", 9, 9, zzia2, zzip5);
        zzvp = zzhyArray;
        zzip zzip6 = zzip.zzzf;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip6;
        zzhyArray = new zzhy("BYTES", 10, 10, zzia2, zzip6);
        zzvq = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("UINT32", 11, 11, zzia2, zzip4);
        zzvr = zzhyArray;
        zzip zzip7 = zzip.zzzg;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip7;
        zzhyArray = new zzhy("ENUM", 12, 12, zzia2, zzip7);
        zzvs = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("SFIXED32", 13, 13, zzia2, zzip4);
        zzvt = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip3;
        zzhyArray = new zzhy("SFIXED64", 14, 14, zzia2, zzip3);
        zzvu = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("SINT32", 15, 15, zzia2, zzip4);
        zzvv = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip3;
        zzhyArray = new zzhy("SINT64", 16, 16, zzia2, zzip3);
        zzvw = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip5;
        zzhyArray = new zzhy("GROUP", 17, 17, zzia2, zzip5);
        zzvx = zzhyArray;
        zzia2 = zzia.zzxp;
        zzhyArray2 = zzhyArray;
        zzhyArray3 = zzia2;
        zzip2 = enum_;
        zzhyArray = new zzhy("DOUBLE_LIST", 18, 18, zzia2, (zzip)enum_);
        zzvy = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = object;
        zzhyArray = new zzhy("FLOAT_LIST", 19, 19, zzia2, object);
        zzvz = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip3;
        zzhyArray = new zzhy("INT64_LIST", 20, 20, zzia2, zzip3);
        zzwa = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzhyArray = new zzhy("UINT64_LIST", 21, 21, zzia2, zzip3);
        zzwb = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("INT32_LIST", 22, 22, zzia2, zzip4);
        zzwc = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip3;
        zzhyArray = new zzhy("FIXED64_LIST", 23, 23, zzia2, zzip3);
        zzwd = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("FIXED32_LIST", 24, 24, zzia2, zzip4);
        zzwe = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = enum_2;
        zzhyArray = new zzhy("BOOL_LIST", 25, 25, zzia2, (zzip)enum_2);
        zzwf = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = enum_3;
        zzhyArray = new zzhy("STRING_LIST", 26, 26, zzia2, (zzip)enum_3);
        zzwg = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip5;
        zzhyArray = new zzhy("MESSAGE_LIST", 27, 27, zzia2, zzip5);
        zzwh = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip6;
        zzhyArray = new zzhy("BYTES_LIST", 28, 28, zzia2, zzip6);
        zzwi = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("UINT32_LIST", 29, 29, zzia2, zzip4);
        zzwj = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip7;
        zzhyArray = new zzhy("ENUM_LIST", 30, 30, zzia2, zzip7);
        zzwk = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("SFIXED32_LIST", 31, 31, zzia2, zzip4);
        zzwl = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip3;
        zzhyArray = new zzhy("SFIXED64_LIST", 32, 32, zzia2, zzip3);
        zzwm = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("SINT32_LIST", 33, 33, zzia2, zzip4);
        zzwn = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip3;
        zzhyArray = new zzhy("SINT64_LIST", 34, 34, zzia2, zzip3);
        zzwo = zzhyArray;
        enum_3 = zzia.zzxq;
        zzhyArray2 = zzhyArray;
        zzhyArray3 = enum_3;
        zzip2 = enum_;
        zzhyArray = new zzhy("DOUBLE_LIST_PACKED", 35, 35, (zzia)enum_3, (zzip)enum_);
        zzwp = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = object;
        zzhyArray = new zzhy("FLOAT_LIST_PACKED", 36, 36, (zzia)enum_3, object);
        zzwq = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip3;
        zzhyArray = new zzhy("INT64_LIST_PACKED", 37, 37, (zzia)enum_3, zzip3);
        zzwr = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzhyArray = new zzhy("UINT64_LIST_PACKED", 38, 38, (zzia)enum_3, zzip3);
        zzws = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("INT32_LIST_PACKED", 39, 39, (zzia)enum_3, zzip4);
        zzwt = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip3;
        zzhyArray = new zzhy("FIXED64_LIST_PACKED", 40, 40, (zzia)enum_3, zzip3);
        zzwu = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("FIXED32_LIST_PACKED", 41, 41, (zzia)enum_3, zzip4);
        zzwv = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = enum_2;
        zzhyArray = new zzhy("BOOL_LIST_PACKED", 42, 42, (zzia)enum_3, (zzip)enum_2);
        zzww = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("UINT32_LIST_PACKED", 43, 43, (zzia)enum_3, zzip4);
        zzwx = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip7;
        zzhyArray = new zzhy("ENUM_LIST_PACKED", 44, 44, (zzia)enum_3, zzip7);
        zzwy = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = zzip4;
        zzhyArray = new zzhy("SFIXED32_LIST_PACKED", 45, 45, (zzia)enum_3, zzip4);
        zzwz = zzhyArray;
        enum_ = zzip.zzza;
        zzhyArray2 = zzhyArray;
        zzip2 = enum_;
        zzhyArray = new zzhy("SFIXED64_LIST_PACKED", 46, 46, (zzia)enum_3, (zzip)enum_);
        zzxa = zzhyArray;
        zzip2 = zzip.zzyz;
        zzhyArray2 = zzhyArray;
        zzhyArray = new zzhy("SINT32_LIST_PACKED", 47, 47, (zzia)enum_3, zzip2);
        zzxb = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzip2 = enum_;
        zzhyArray = new zzhy("SINT64_LIST_PACKED", 48, 48, (zzia)enum_3, (zzip)enum_);
        zzxc = zzhyArray;
        zzhyArray2 = zzhyArray;
        zzhyArray3 = zzia2;
        zzip2 = zzip5;
        zzhyArray = new zzhy("GROUP_LIST", 49, 49, zzia2, zzip5);
        zzxd = zzhyArray;
        enum_2 = zzia.zzxr;
        enum_3 = zzip.zzyy;
        object = "MAP";
        int n10 = 50;
        int n11 = 50;
        enum_ = zzhyArray2;
        zzhyArray2 = new zzhy((String)object, n10, n11, (zzia)enum_2, (zzip)enum_3);
        zzxe = zzhyArray2;
        int n12 = 51;
        zzhyArray2 = new zzhy[n12];
        zzhy[] zzhyArray4 = zzvg;
        zzhyArray2[0] = zzhyArray4;
        zzhyArray4 = zzvh;
        zzhyArray2[1] = zzhyArray4;
        zzhyArray4 = zzvi;
        zzhyArray2[2] = zzhyArray4;
        zzhyArray4 = zzvj;
        zzhyArray2[3] = zzhyArray4;
        zzhyArray4 = zzvk;
        zzhyArray2[4] = zzhyArray4;
        zzhyArray4 = zzvl;
        zzhyArray2[5] = zzhyArray4;
        zzhyArray4 = zzvm;
        zzhyArray2[6] = zzhyArray4;
        zzhyArray4 = zzvn;
        zzhyArray2[7] = zzhyArray4;
        zzhyArray4 = zzvo;
        zzhyArray2[8] = zzhyArray4;
        zzhyArray4 = zzvp;
        zzhyArray2[9] = zzhyArray4;
        zzhyArray4 = zzvq;
        zzhyArray2[10] = zzhyArray4;
        zzhyArray4 = zzvr;
        zzhyArray2[11] = zzhyArray4;
        zzhyArray4 = zzvs;
        zzhyArray2[12] = zzhyArray4;
        zzhyArray4 = zzvt;
        zzhyArray2[13] = zzhyArray4;
        zzhyArray4 = zzvu;
        zzhyArray2[14] = zzhyArray4;
        zzhyArray4 = zzvv;
        zzhyArray2[15] = zzhyArray4;
        zzhyArray4 = zzvw;
        zzhyArray2[16] = zzhyArray4;
        zzhyArray4 = zzvx;
        zzhyArray2[17] = zzhyArray4;
        zzhyArray4 = zzvy;
        zzhyArray2[18] = zzhyArray4;
        zzhyArray4 = zzvz;
        zzhyArray2[19] = zzhyArray4;
        zzhyArray4 = zzwa;
        zzhyArray2[20] = zzhyArray4;
        zzhyArray4 = zzwb;
        zzhyArray2[21] = zzhyArray4;
        zzhyArray4 = zzwc;
        zzhyArray2[22] = zzhyArray4;
        zzhyArray4 = zzwd;
        zzhyArray2[23] = zzhyArray4;
        zzhyArray4 = zzwe;
        zzhyArray2[24] = zzhyArray4;
        zzhyArray4 = zzwf;
        zzhyArray2[25] = zzhyArray4;
        zzhyArray4 = zzwg;
        zzhyArray2[26] = zzhyArray4;
        zzhyArray4 = zzwh;
        zzhyArray2[27] = zzhyArray4;
        zzhyArray4 = zzwi;
        zzhyArray2[28] = zzhyArray4;
        zzhyArray4 = zzwj;
        zzhyArray2[29] = zzhyArray4;
        zzhyArray4 = zzwk;
        zzhyArray2[30] = zzhyArray4;
        zzhyArray4 = zzwl;
        zzhyArray2[31] = zzhyArray4;
        zzhyArray4 = zzwm;
        zzhyArray2[32] = zzhyArray4;
        zzhyArray4 = zzwn;
        zzhyArray2[33] = zzhyArray4;
        zzhyArray4 = zzwo;
        zzhyArray2[34] = zzhyArray4;
        zzhyArray4 = zzwp;
        zzhyArray2[35] = zzhyArray4;
        zzhyArray4 = zzwq;
        zzhyArray2[36] = zzhyArray4;
        zzhyArray4 = zzwr;
        zzhyArray2[37] = zzhyArray4;
        zzhyArray4 = zzws;
        zzhyArray2[38] = zzhyArray4;
        zzhyArray4 = zzwt;
        zzhyArray2[39] = zzhyArray4;
        zzhyArray4 = zzwu;
        zzhyArray2[40] = zzhyArray4;
        zzhyArray4 = zzwv;
        zzhyArray2[41] = zzhyArray4;
        zzhyArray4 = zzww;
        zzhyArray2[42] = zzhyArray4;
        zzhyArray4 = zzwx;
        zzhyArray2[43] = zzhyArray4;
        zzhyArray4 = zzwy;
        zzhyArray2[44] = zzhyArray4;
        zzhyArray4 = zzwz;
        zzhyArray2[45] = zzhyArray4;
        zzhyArray4 = zzxa;
        zzhyArray2[46] = zzhyArray4;
        zzhyArray4 = zzxb;
        zzhyArray2[47] = zzhyArray4;
        zzhyArray4 = zzxc;
        zzhyArray2[48] = zzhyArray4;
        zzhyArray4 = zzxd;
        zzhyArray2[49] = zzhyArray4;
        zzhyArray4 = zzxe;
        int n13 = 50;
        zzhyArray2[n13] = zzhyArray4;
        zzxl = zzhyArray2;
        zzxk = new Type[0];
        zzhyArray2 = zzhy.values();
        zzhyArray4 = new zzhy[zzhyArray2.length];
        zzxj = zzhyArray4;
        for (zzhy zzhy22 : zzhyArray2) {
            zzhyArray3 = zzxj;
            int n14 = zzhy22.id;
            zzhyArray3[n14] = zzhy22;
        }
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private zzhy(zzip zzip2) {
        int n11;
        int n12;
        void var5_4;
        int[] nArray;
        void var2_-1;
        void var1_-1;
        this.id = (int)zzip2;
        this.zzxg = nArray;
        this.zzxf = var5_4;
        Object object = zzhx.zzve;
        int n13 = nArray.ordinal();
        int n14 = object[n13];
        n13 = 2;
        int n15 = 1;
        if (n14 != n15) {
            if (n14 != n13) {
                n14 = 0;
                object = null;
                this.zzxh = null;
            } else {
                object = var5_4.zzhq();
                this.zzxh = object;
            }
        } else {
            object = var5_4.zzhq();
            this.zzxh = object;
        }
        n14 = 0;
        object = null;
        zzia zzia2 = zzia.zzxo;
        if (nArray != zzia2 || (n12 = (nArray = zzhx.zzvf)[n11 = var5_4.ordinal()]) == n15 || n12 == n13 || n12 == (n13 = 3)) {
            n15 = 0;
        }
        this.zzxi = n15;
    }

    public static zzhy[] values() {
        return (zzhy[])zzxl.clone();
    }

    public final int id() {
        return this.id;
    }
}

