/*
 * Decompiled with CFR 0.151.
 */
package com.google.android.gms.internal.measurement;

import com.google.android.gms.internal.measurement.zzid;

public final class zzhk
extends Enum {
    public static final /* enum */ zzhk zzA;
    public static final /* enum */ zzhk zzB;
    public static final /* enum */ zzhk zzC;
    public static final /* enum */ zzhk zzD;
    public static final /* enum */ zzhk zzE;
    public static final /* enum */ zzhk zzF;
    public static final /* enum */ zzhk zzG;
    public static final /* enum */ zzhk zzH;
    public static final /* enum */ zzhk zzI;
    public static final /* enum */ zzhk zzJ;
    public static final /* enum */ zzhk zzK;
    public static final /* enum */ zzhk zzL;
    public static final /* enum */ zzhk zzM;
    public static final /* enum */ zzhk zzN;
    public static final /* enum */ zzhk zzO;
    public static final /* enum */ zzhk zzP;
    public static final /* enum */ zzhk zzQ;
    public static final /* enum */ zzhk zzR;
    public static final /* enum */ zzhk zzS;
    public static final /* enum */ zzhk zzT;
    public static final /* enum */ zzhk zzU;
    public static final /* enum */ zzhk zzV;
    public static final /* enum */ zzhk zzW;
    public static final /* enum */ zzhk zzX;
    public static final /* enum */ zzhk zzY;
    public static final /* enum */ zzhk zza;
    private static final zzhk[] zzac;
    private static final /* synthetic */ zzhk[] zzad;
    public static final /* enum */ zzhk zzb;
    public static final /* enum */ zzhk zzc;
    public static final /* enum */ zzhk zzd;
    public static final /* enum */ zzhk zze;
    public static final /* enum */ zzhk zzf;
    public static final /* enum */ zzhk zzg;
    public static final /* enum */ zzhk zzh;
    public static final /* enum */ zzhk zzi;
    public static final /* enum */ zzhk zzj;
    public static final /* enum */ zzhk zzk;
    public static final /* enum */ zzhk zzl;
    public static final /* enum */ zzhk zzm;
    public static final /* enum */ zzhk zzn;
    public static final /* enum */ zzhk zzo;
    public static final /* enum */ zzhk zzp;
    public static final /* enum */ zzhk zzq;
    public static final /* enum */ zzhk zzr;
    public static final /* enum */ zzhk zzs;
    public static final /* enum */ zzhk zzt;
    public static final /* enum */ zzhk zzu;
    public static final /* enum */ zzhk zzv;
    public static final /* enum */ zzhk zzw;
    public static final /* enum */ zzhk zzx;
    public static final /* enum */ zzhk zzy;
    public static final /* enum */ zzhk zzz;
    private final zzid zzZ;
    private final int zzaa;
    private final Class zzab;

    static {
        Enum enum_;
        Object object = zzid.zze;
        zzhk[] zzhkArray = enum_;
        enum_ = new zzhk("DOUBLE", 0, 0, 1, object);
        zza = enum_;
        Object object2 = zzid.zzd;
        int n10 = 1;
        int n11 = 1;
        Enum enum_2 = zzhkArray;
        Enum enum_3 = object2;
        zzhkArray = new zzhk("FLOAT", 1, n10, n11, object2);
        zzb = zzhkArray;
        enum_2 = zzid.zzc;
        int n12 = 1;
        Enum enum_4 = zzhkArray;
        enum_ = enum_2;
        zzhkArray = new zzhk("INT64", 2, 2, n12, (zzid)enum_2);
        zzc = zzhkArray;
        enum_4 = zzhkArray;
        zzhkArray = new zzhk("UINT64", 3, 3, n12, (zzid)enum_2);
        zzd = zzhkArray;
        zzid zzid2 = zzid.zzb;
        int n13 = 1;
        zzhkArray = new zzhk("INT32", 4, 4, n13, zzid2);
        zze = zzhkArray;
        enum_4 = zzhkArray;
        zzhkArray = new zzhk("FIXED64", 5, 5, n12, (zzid)enum_2);
        zzf = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("FIXED32", 6, 6, n12, zzid2);
        zzg = zzhkArray;
        zzid zzid3 = zzid.zzf;
        zzhkArray = new zzhk("BOOL", 7, 7, n13, zzid3);
        zzh = zzhkArray;
        zzid zzid4 = zzid.zzg;
        enum_4 = zzhkArray;
        enum_ = zzid4;
        zzhkArray = new zzhk("STRING", 8, 8, n12, zzid4);
        zzi = zzhkArray;
        zzid zzid5 = zzid.zzj;
        zzhkArray = new zzhk("MESSAGE", 9, 9, n13, zzid5);
        zzj = zzhkArray;
        enum_3 = zzid.zzh;
        enum_4 = zzhkArray;
        enum_ = enum_3;
        zzhkArray = new zzhk("BYTES", 10, 10, n12, (zzid)enum_3);
        zzk = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("UINT32", 11, 11, n12, zzid2);
        zzl = zzhkArray;
        zzid zzid6 = zzid.zzi;
        String string2 = "ENUM";
        int n14 = 12;
        zzhkArray = new zzhk(string2, 12, n14, n13, zzid6);
        zzm = zzhkArray;
        enum_4 = zzhkArray;
        zzhkArray = new zzhk("SFIXED32", 13, 13, n12, zzid2);
        zzn = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = enum_2;
        zzhkArray = new zzhk("SFIXED64", 14, 14, n12, (zzid)enum_2);
        zzo = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("SINT32", 15, 15, n12, zzid2);
        zzp = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = enum_2;
        zzhkArray = new zzhk("SINT64", 16, 16, n12, (zzid)enum_2);
        zzq = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid5;
        zzhkArray = new zzhk("GROUP", 17, 17, n12, zzid5);
        zzr = zzhkArray;
        zzhkArray = enum_;
        zzs = enum_ = new zzhk("DOUBLE_LIST", 18, 18, 2, object);
        n12 = 2;
        enum_4 = zzhkArray;
        enum_ = object2;
        zzhkArray = new zzhk("FLOAT_LIST", 19, 19, n12, object2);
        zzt = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = enum_2;
        zzhkArray = new zzhk("INT64_LIST", 20, 20, n12, (zzid)enum_2);
        zzu = zzhkArray;
        enum_4 = zzhkArray;
        zzhkArray = new zzhk("UINT64_LIST", 21, 21, n12, (zzid)enum_2);
        zzv = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("INT32_LIST", 22, 22, n12, zzid2);
        zzw = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = enum_2;
        zzhkArray = new zzhk("FIXED64_LIST", 23, 23, n12, (zzid)enum_2);
        zzx = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("FIXED32_LIST", 24, 24, n12, zzid2);
        zzy = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid3;
        zzhkArray = new zzhk("BOOL_LIST", 25, 25, n12, zzid3);
        zzz = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid4;
        zzhkArray = new zzhk("STRING_LIST", 26, 26, n12, zzid4);
        zzA = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid5;
        zzhkArray = new zzhk("MESSAGE_LIST", 27, 27, n12, zzid5);
        zzB = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = enum_3;
        zzhkArray = new zzhk("BYTES_LIST", 28, 28, n12, (zzid)enum_3);
        zzC = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("UINT32_LIST", 29, 29, n12, zzid2);
        zzD = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid6;
        zzhkArray = new zzhk("ENUM_LIST", 30, 30, n12, zzid6);
        zzE = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("SFIXED32_LIST", 31, 31, n12, zzid2);
        zzF = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = enum_2;
        zzhkArray = new zzhk("SFIXED64_LIST", 32, 32, n12, (zzid)enum_2);
        zzG = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("SINT32_LIST", 33, 33, n12, zzid2);
        zzH = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = enum_2;
        zzhkArray = new zzhk("SINT64_LIST", 34, 34, n12, (zzid)enum_2);
        zzI = zzhkArray;
        zzhkArray = enum_;
        zzJ = enum_ = new zzhk("DOUBLE_LIST_PACKED", 35, 35, 3, object);
        n12 = 3;
        enum_4 = zzhkArray;
        enum_ = object2;
        zzhkArray = new zzhk("FLOAT_LIST_PACKED", 36, 36, n12, object2);
        zzK = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = enum_2;
        zzhkArray = new zzhk("INT64_LIST_PACKED", 37, 37, n12, (zzid)enum_2);
        zzL = zzhkArray;
        enum_4 = zzhkArray;
        zzhkArray = new zzhk("UINT64_LIST_PACKED", 38, 38, n12, (zzid)enum_2);
        zzM = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("INT32_LIST_PACKED", 39, 39, n12, zzid2);
        zzN = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = enum_2;
        zzhkArray = new zzhk("FIXED64_LIST_PACKED", 40, 40, n12, (zzid)enum_2);
        zzO = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("FIXED32_LIST_PACKED", 41, 41, n12, zzid2);
        zzP = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid3;
        zzhkArray = new zzhk("BOOL_LIST_PACKED", 42, 42, n12, zzid3);
        zzQ = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("UINT32_LIST_PACKED", 43, 43, n12, zzid2);
        zzR = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid6;
        zzhkArray = new zzhk("ENUM_LIST_PACKED", 44, 44, n12, zzid6);
        zzS = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = zzid2;
        zzhkArray = new zzhk("SFIXED32_LIST_PACKED", 45, 45, n12, zzid2);
        zzT = zzhkArray;
        object = zzid.zzc;
        object2 = "SFIXED64_LIST_PACKED";
        int n15 = 46;
        int n16 = 46;
        int n17 = 3;
        enum_3 = zzhkArray;
        zzhkArray = new zzhk((String)object2, n15, n16, n17, object);
        zzU = zzhkArray;
        enum_4 = zzhkArray;
        zzhkArray = new zzhk("SINT32_LIST_PACKED", 47, 47, n12, zzid2);
        zzV = zzhkArray;
        enum_4 = zzhkArray;
        enum_ = object;
        zzhkArray = new zzhk("SINT64_LIST_PACKED", 48, 48, n12, object);
        zzW = zzhkArray;
        int n18 = 49;
        n12 = 2;
        enum_4 = zzhkArray;
        enum_ = zzid5;
        zzhkArray = new zzhk("GROUP_LIST", 49, n18, n12, zzid5);
        zzX = zzhkArray;
        zzid4 = zzid.zza;
        object = "MAP";
        int n19 = 50;
        int n20 = 50;
        int n21 = 4;
        enum_ = zzhkArray;
        zzhkArray = new zzhk((String)object, n19, n20, n21, zzid4);
        zzY = zzhkArray;
        int n22 = 51;
        zzhkArray = new zzhk[n22];
        enum_4 = zza;
        zzhkArray[0] = enum_4;
        zzhkArray[1] = enum_4 = zzb;
        zzhkArray[2] = enum_4 = zzc;
        zzhkArray[3] = enum_4 = zzd;
        zzhkArray[4] = enum_4 = zze;
        zzhkArray[5] = enum_4 = zzf;
        zzhkArray[6] = enum_4 = zzg;
        zzhkArray[7] = enum_4 = zzh;
        zzhkArray[8] = enum_4 = zzi;
        zzhkArray[9] = enum_4 = zzj;
        zzhkArray[10] = enum_4 = zzk;
        zzhkArray[11] = enum_4 = zzl;
        zzhkArray[12] = enum_4 = zzm;
        zzhkArray[13] = enum_4 = zzn;
        zzhkArray[14] = enum_4 = zzo;
        zzhkArray[15] = enum_4 = zzp;
        zzhkArray[16] = enum_4 = zzq;
        zzhkArray[17] = enum_4 = zzr;
        zzhkArray[18] = enum_4 = zzs;
        zzhkArray[19] = enum_4 = zzt;
        zzhkArray[20] = enum_4 = zzu;
        zzhkArray[21] = enum_4 = zzv;
        zzhkArray[22] = enum_4 = zzw;
        zzhkArray[23] = enum_4 = zzx;
        zzhkArray[24] = enum_4 = zzy;
        zzhkArray[25] = enum_4 = zzz;
        zzhkArray[26] = enum_4 = zzA;
        zzhkArray[27] = enum_4 = zzB;
        zzhkArray[28] = enum_4 = zzC;
        zzhkArray[29] = enum_4 = zzD;
        zzhkArray[30] = enum_4 = zzE;
        zzhkArray[31] = enum_4 = zzF;
        zzhkArray[32] = enum_4 = zzG;
        zzhkArray[33] = enum_4 = zzH;
        zzhkArray[34] = enum_4 = zzI;
        zzhkArray[35] = enum_4 = zzJ;
        zzhkArray[36] = enum_4 = zzK;
        zzhkArray[37] = enum_4 = zzL;
        zzhkArray[38] = enum_4 = zzM;
        zzhkArray[39] = enum_4 = zzN;
        zzhkArray[40] = enum_4 = zzO;
        zzhkArray[41] = enum_4 = zzP;
        zzhkArray[42] = enum_4 = zzQ;
        zzhkArray[43] = enum_4 = zzR;
        zzhkArray[44] = enum_4 = zzS;
        zzhkArray[45] = enum_4 = zzT;
        zzhkArray[46] = enum_4 = zzU;
        zzhkArray[47] = enum_4 = zzV;
        zzhkArray[48] = enum_4 = zzW;
        zzhkArray[49] = enum_4 = zzX;
        enum_4 = zzY;
        int n23 = 50;
        zzhkArray[n23] = enum_4;
        zzad = zzhkArray;
        zzhkArray = zzhk.values();
        int n24 = zzhkArray.length;
        Object object3 = new zzhk[n24];
        zzac = object3;
        for (int i10 = 0; i10 < n24; ++i10) {
            object3 = zzhkArray[i10];
            zzhk[] zzhkArray2 = zzac;
            n12 = object3.zzaa;
            zzhkArray2[n12] = object3;
        }
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private zzhk(zzid object) {
        void var4_2;
        void var5_3;
        void var2_-1;
        void var1_-1;
        this.zzaa = (int)object;
        this.zzZ = var5_3;
        Object object2 = zzid.zza;
        boolean bl2 = var4_2 + -1;
        boolean bl3 = true;
        if (bl2 != bl3) {
            object = 3;
            if (bl2 != object) {
                bl2 = false;
                object2 = null;
                this.zzab = null;
            } else {
                object2 = var5_3.zza();
                this.zzab = object2;
            }
        } else {
            object2 = var5_3.zza();
            this.zzab = object2;
        }
        if (var4_2 == bl3) {
            var5_3.ordinal();
        }
    }

    public static zzhk[] values() {
        return (zzhk[])zzad.clone();
    }

    public final int zza() {
        return this.zzaa;
    }
}

