/*
 * Decompiled with CFR 0.151.
 */
package d.v.c.s0.y6;

import com.zhiyun.protocol.utils.Axis;
import java.util.ArrayList;
import java.util.List;

public class f1 {
    public final List a;
    public final List b;
    public final List c;
    public final List d;
    public final List e;
    public final List f;
    public final List g;
    public final List h;
    public final List i;

    public f1() {
        ArrayList<Axis> arrayList;
        this.a = arrayList = new ArrayList<Axis>();
        float f10 = -90.0f;
        Axis axis = new Axis(0.0f, 0.0f, f10);
        arrayList.add(axis);
        float f11 = -60.0f;
        axis = new Axis(0.0f, 0.0f, f11);
        arrayList.add(axis);
        float f12 = -30.0f;
        axis = new Axis(0.0f, 0.0f, f12);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 0.0f);
        arrayList.add(axis);
        float f13 = 30.0f;
        axis = new Axis(0.0f, 0.0f, f13);
        arrayList.add(axis);
        float f14 = 60.0f;
        axis = new Axis(0.0f, 0.0f, f14);
        arrayList.add(axis);
        float f15 = 90.0f;
        axis = new Axis(0.0f, 0.0f, f15);
        arrayList.add(axis);
        this.b = arrayList = new ArrayList<Axis>();
        axis = new Axis(0.0f, 0.0f, -120.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, -96.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, -72.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, -48.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, -24.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 0.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 24.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 48.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 72.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 96.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 120.0f);
        arrayList.add(axis);
        this.c = arrayList = new ArrayList<Axis>();
        axis = new Axis(f13, 0.0f, f12);
        arrayList.add(axis);
        axis = new Axis(f13, 0.0f, 0.0f);
        arrayList.add(axis);
        axis = new Axis(f13, 0.0f, f13);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f13);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 0.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f12);
        arrayList.add(axis);
        axis = new Axis(f12, 0.0f, f12);
        arrayList.add(axis);
        axis = new Axis(f12, 0.0f, 0.0f);
        arrayList.add(axis);
        axis = new Axis(f12, 0.0f, f13);
        arrayList.add(axis);
        this.d = arrayList = new ArrayList<Axis>();
        axis = new Axis(f13, 0.0f, f13);
        arrayList.add(axis);
        axis = new Axis(f13, 0.0f, 0.0f);
        arrayList.add(axis);
        axis = new Axis(f13, 0.0f, f12);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f12);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 0.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f13);
        arrayList.add(axis);
        axis = new Axis(f12, 0.0f, f13);
        arrayList.add(axis);
        axis = new Axis(f12, 0.0f, 0.0f);
        arrayList.add(axis);
        axis = new Axis(f12, 0.0f, f12);
        arrayList.add(axis);
        this.e = arrayList = new ArrayList<Axis>();
        axis = new Axis(0.0f, 0.0f, f12);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 0.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f13);
        arrayList.add(axis);
        this.f = arrayList = new ArrayList<Axis>();
        float f16 = -45.0f;
        axis = new Axis(0.0f, 0.0f, f16);
        arrayList.add(axis);
        float f17 = -15.0f;
        axis = new Axis(0.0f, 0.0f, f17);
        arrayList.add(axis);
        float f18 = 15.0f;
        axis = new Axis(0.0f, 0.0f, f18);
        arrayList.add(axis);
        float f19 = 45.0f;
        axis = new Axis(0.0f, 0.0f, f19);
        arrayList.add(axis);
        this.g = arrayList = new ArrayList<Axis>();
        axis = new Axis(0.0f, 0.0f, f11);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f12);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 0.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f13);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f14);
        arrayList.add(axis);
        this.h = arrayList = new ArrayList<Axis>();
        axis = new Axis(0.0f, 0.0f, -75.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f16);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f17);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f18);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f19);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 75.0f);
        arrayList.add(axis);
        this.i = arrayList = new ArrayList<Axis>();
        axis = new Axis(0.0f, 0.0f, f10);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f11);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f12);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, 0.0f);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f13);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f14);
        arrayList.add(axis);
        axis = new Axis(0.0f, 0.0f, f15);
        arrayList.add(axis);
    }
}

