/*
 * Decompiled with CFR 0.151.
 */
package com.xiaomi.push;

/*
 * Duplicate member names - consider using --renamedupmembers true
 */
public final class hr
extends Enum {
    public static final /* enum */ hr A;
    public static final /* enum */ hr B;
    public static final /* enum */ hr C;
    public static final /* enum */ hr D;
    public static final /* enum */ hr E;
    public static final /* enum */ hr F;
    public static final /* enum */ hr G;
    public static final /* enum */ hr H;
    public static final /* enum */ hr I;
    public static final /* enum */ hr J;
    public static final /* enum */ hr K;
    public static final /* enum */ hr L;
    public static final /* enum */ hr M;
    public static final /* enum */ hr N;
    public static final /* enum */ hr O;
    public static final /* enum */ hr P;
    public static final /* enum */ hr Q;
    public static final /* enum */ hr R;
    public static final /* enum */ hr S;
    public static final /* enum */ hr T;
    public static final /* enum */ hr U;
    public static final /* enum */ hr V;
    public static final /* enum */ hr W;
    public static final /* enum */ hr X;
    public static final /* enum */ hr Y;
    public static final /* enum */ hr Z;
    public static final /* enum */ hr a;
    private static final /* synthetic */ hr[] a;
    public static final /* enum */ hr aA;
    public static final /* enum */ hr aB;
    public static final /* enum */ hr aC;
    public static final /* enum */ hr aD;
    public static final /* enum */ hr aE;
    public static final /* enum */ hr aF;
    public static final /* enum */ hr aG;
    public static final /* enum */ hr aH;
    public static final /* enum */ hr aI;
    public static final /* enum */ hr aJ;
    public static final /* enum */ hr aK;
    public static final /* enum */ hr aL;
    public static final /* enum */ hr aM;
    public static final /* enum */ hr aN;
    public static final /* enum */ hr aO;
    public static final /* enum */ hr aP;
    public static final /* enum */ hr aQ;
    public static final /* enum */ hr aR;
    public static final /* enum */ hr aS;
    public static final /* enum */ hr aT;
    public static final /* enum */ hr aU;
    public static final /* enum */ hr aV;
    public static final /* enum */ hr aW;
    public static final /* enum */ hr aX;
    public static final /* enum */ hr aY;
    public static final /* enum */ hr aZ;
    public static final /* enum */ hr aa;
    public static final /* enum */ hr ab;
    public static final /* enum */ hr ac;
    public static final /* enum */ hr ad;
    public static final /* enum */ hr ae;
    public static final /* enum */ hr af;
    public static final /* enum */ hr ag;
    public static final /* enum */ hr ah;
    public static final /* enum */ hr ai;
    public static final /* enum */ hr aj;
    public static final /* enum */ hr ak;
    public static final /* enum */ hr al;
    public static final /* enum */ hr am;
    public static final /* enum */ hr an;
    public static final /* enum */ hr ao;
    public static final /* enum */ hr ap;
    public static final /* enum */ hr aq;
    public static final /* enum */ hr ar;
    public static final /* enum */ hr as;
    public static final /* enum */ hr at;
    public static final /* enum */ hr au;
    public static final /* enum */ hr av;
    public static final /* enum */ hr aw;
    public static final /* enum */ hr ax;
    public static final /* enum */ hr ay;
    public static final /* enum */ hr az;
    public static final /* enum */ hr b;
    public static final /* enum */ hr ba;
    public static final /* enum */ hr bb;
    public static final /* enum */ hr bc;
    public static final /* enum */ hr bd;
    public static final /* enum */ hr be;
    public static final /* enum */ hr bf;
    public static final /* enum */ hr bg;
    public static final /* enum */ hr bh;
    public static final /* enum */ hr bi;
    public static final /* enum */ hr c;
    public static final /* enum */ hr d;
    public static final /* enum */ hr e;
    public static final /* enum */ hr f;
    public static final /* enum */ hr g;
    public static final /* enum */ hr h;
    public static final /* enum */ hr i;
    public static final /* enum */ hr j;
    public static final /* enum */ hr k;
    public static final /* enum */ hr l;
    public static final /* enum */ hr m;
    public static final /* enum */ hr n;
    public static final /* enum */ hr o;
    public static final /* enum */ hr p;
    public static final /* enum */ hr q;
    public static final /* enum */ hr r;
    public static final /* enum */ hr s;
    public static final /* enum */ hr t;
    public static final /* enum */ hr u;
    public static final /* enum */ hr v;
    public static final /* enum */ hr w;
    public static final /* enum */ hr x;
    public static final /* enum */ hr y;
    public static final /* enum */ hr z;
    private final int a;

    static {
        hr hr2;
        int n10 = 1;
        hr[] hrArray = new hr("UploadSwitch", 0, n10);
        a = hrArray;
        int n11 = 2;
        hrArray = new hr("UploadFrequency", n10, n11);
        b = hrArray;
        int n12 = 3;
        hrArray = new hr("ScreenSizeCollectionSwitch", n11, n12);
        c = hrArray;
        int n13 = 4;
        hrArray = new hr("MacCollectionSwitch", n12, n13);
        d = hrArray;
        int n14 = 5;
        hrArray = new hr("IMSICollectionSwitch", n13, n14);
        e = hrArray;
        int n15 = 6;
        hrArray = new hr("AndroidVnCollectionSwitch", n14, n15);
        f = hrArray;
        int n16 = 7;
        hrArray = new hr("AndroidVcCollectionSwitch", n15, n16);
        g = hrArray;
        int n17 = 8;
        hrArray = new hr("AndroidIdCollectionSwitch", n16, n17);
        h = hrArray;
        int n18 = 9;
        hrArray = new hr("DeviceInfoCollectionFrequency", n17, n18);
        i = hrArray;
        int n19 = 10;
        hrArray = new hr("AppInstallListCollectionSwitch", n18, n19);
        j = hrArray;
        int n20 = 11;
        hrArray = new hr("AppInstallListCollectionFrequency", n19, n20);
        k = hrArray;
        int n21 = 12;
        hrArray = new hr("AppActiveListCollectionSwitch", n20, n21);
        l = hrArray;
        int n22 = 13;
        hrArray = new hr("AppActiveListCollectionFrequency", n21, n22);
        m = hrArray;
        int n23 = 14;
        hrArray = new hr("BluetoothCollectionSwitch", n22, n23);
        n = hrArray;
        n22 = 15;
        hrArray = new hr("BluetoothCollectionFrequency", n23, n22);
        o = hrArray;
        n23 = 16;
        hrArray = new hr("LocationCollectionSwitch", n22, n23);
        p = hrArray;
        n22 = 17;
        hrArray = new hr("LocationCollectionFrequency", n23, n22);
        q = hrArray;
        n23 = 18;
        hrArray = new hr("AccountCollectionSwitch", n22, n23);
        r = hrArray;
        n22 = 19;
        hrArray = new hr("AccountCollectionFrequency", n23, n22);
        s = hrArray;
        n23 = 20;
        hrArray = new hr("WifiCollectionSwitch", n22, n23);
        t = hrArray;
        n22 = 21;
        hrArray = new hr("WifiCollectionFrequency", n23, n22);
        u = hrArray;
        n23 = 22;
        hrArray = new hr("CellularCollectionSwitch", n22, n23);
        v = hrArray;
        n22 = 23;
        hrArray = new hr("CellularCollectionFrequency", n23, n22);
        w = hrArray;
        hrArray = new hr("TopAppCollectionSwitch", n22, 24);
        x = hrArray;
        hrArray = new hr("TopAppCollectionFrequency", 24, 25);
        y = hrArray;
        hrArray = new hr("DataCollectionSwitch", 25, 26);
        z = hrArray;
        hrArray = new hr("OcVersionCheckFrequency", 26, 27);
        A = hrArray;
        hrArray = new hr("SyncInfoFrequency", 27, 28);
        B = hrArray;
        hrArray = new hr("UploadNotificationInfoFrequency", 28, 29);
        C = hrArray;
        hrArray = new hr("UploadNotificationInfoMaxNum", 29, 30);
        D = hrArray;
        hrArray = new hr("CollectionNotificationInfoBaseSwitch", 30, 31);
        E = hrArray;
        hrArray = new hr("CollectionNotificationInfoAppSwitch", 31, 32);
        F = hrArray;
        hrArray = new hr("CollectionNotificationInfoRemovedSwitch", 32, 33);
        G = hrArray;
        hrArray = new hr("ForegroundServiceSwitch", 33, 34);
        H = hrArray;
        hrArray = new hr("SyncMIIDFrequency", 34, 35);
        I = hrArray;
        hrArray = new hr("Upload4GSwitch", 35, 36);
        J = hrArray;
        hrArray = new hr("Upload4GFrequency", 36, 37);
        K = hrArray;
        hrArray = new hr("Upload3GSwitch", 37, 38);
        L = hrArray;
        hrArray = new hr("Upload3GFrequency", 38, 39);
        M = hrArray;
        hrArray = new hr("ShieldTypeConfig", 39, 40);
        N = hrArray;
        hrArray = new hr("UploadWIFIGeoLocFrequency", 40, 41);
        O = hrArray;
        hrArray = new hr("UploadNOWIFIGeoLocFrequency", 41, 42);
        P = hrArray;
        hrArray = new hr("BroadcastActionCollectionSwitch", 42, 43);
        Q = hrArray;
        hrArray = new hr("BroadcastActionCollectionFrequency", 43, 44);
        R = hrArray;
        hrArray = new hr("UploadGeoLocSwitch", 44, 45);
        S = hrArray;
        hrArray = new hr("ServiceBootMode", 45, 46);
        T = hrArray;
        hrArray = new hr("AppPermissionCollectionSwitch", 46, 47);
        U = hrArray;
        hrArray = new hr("AppPermissionCollectionFrequency", 47, 48);
        V = hrArray;
        hrArray = new hr("WifiDevicesMacCollectionSwitch", 48, 49);
        W = hrArray;
        hrArray = new hr("WifiDevicesMacCollectionFrequency", 49, 50);
        X = hrArray;
        hrArray = new hr("WifiDevicesMacWifiUnchangedCollectionFrequency", 50, 51);
        Y = hrArray;
        hrArray = new hr("AggregationSdkMonitorSwitch", 51, 52);
        Z = hrArray;
        hrArray = new hr("AggregationSdkMonitorFrequency", 52, 53);
        aa = hrArray;
        hrArray = new hr("AggregationSdkMonitorDepth", 53, 54);
        ab = hrArray;
        hrArray = new hr("UploadGeoAppLocSwitch", 54, 55);
        ac = hrArray;
        hrArray = new hr("ThirdPushControlSwitch", 55, 56);
        ad = hrArray;
        hrArray = new hr("ThirdPushComponentKeyWords", 56, 57);
        ae = hrArray;
        hrArray = new hr("ThirdPushWhiteList", 57, 58);
        af = hrArray;
        hrArray = new hr("XmsfScanWhitelist", 58, 59);
        ag = hrArray;
        hrArray = new hr("IccidCollectionSwitch", 59, 60);
        ah = hrArray;
        hrArray = new hr("LimitThridPushStrategyMode", 60, 61);
        ai = hrArray;
        hrArray = new hr("GlobalPushChannelException", 61, 62);
        aj = hrArray;
        hrArray = new hr("TinyDataUploadSwitch", 62, 63);
        ak = hrArray;
        hrArray = new hr("TinyDataUploadFrequency", 63, 64);
        al = hrArray;
        hrArray = new hr("GlobalRegionIOSwitch", 64, 65);
        am = hrArray;
        hrArray = new hr("GlobalRegionIOWait", 65, 66);
        an = hrArray;
        hrArray = new hr("AggregatePushSwitch", 66, 67);
        ao = hrArray;
        hrArray = new hr("ActivityTSSwitch", 67, 68);
        ap = hrArray;
        hrArray = new hr("OperatorSwitch", 68, 69);
        aq = hrArray;
        hrArray = new hr("DeviceIdSwitch", 69, 70);
        ar = hrArray;
        hrArray = new hr("DeviceBaseInfoCollectionFrequency", 70, 71);
        as = hrArray;
        hrArray = new hr("UsageStatsCollectionFrequency", 71, 72);
        at = hrArray;
        hrArray = new hr("UsageStatsCollectionWhiteList", 72, 73);
        au = hrArray;
        hrArray = new hr("ForceHandleCrashSwitch", 73, 74);
        av = hrArray;
        hrArray = new hr("Crash4GUploadSwitch", 74, 75);
        aw = hrArray;
        hrArray = new hr("Crash4GUploadFrequency", 75, 76);
        ax = hrArray;
        hrArray = new hr("CrashWIFIUploadFrequency", 76, 77);
        ay = hrArray;
        hrArray = new hr("EventUploadSwitch", 77, 78);
        az = hrArray;
        hrArray = new hr("PerfUploadSwitch", 78, 79);
        aA = hrArray;
        hrArray = new hr("EventUploadFrequency", 79, 80);
        aB = hrArray;
        hrArray = new hr("PerfUploadFrequency", 80, 81);
        aC = hrArray;
        hrArray = new hr("BatteryCollectionSwitch", 81, 82);
        aD = hrArray;
        hrArray = new hr("BatteryCollectionFrequency", 82, 83);
        aE = hrArray;
        hrArray = new hr("AwakeInfoUploadWaySwitch", 83, 84);
        aF = hrArray;
        hrArray = new hr("AwakeAppPingSwitch", 84, 85);
        aG = hrArray;
        hrArray = new hr("AwakeAppPingFrequency", 85, 86);
        aH = hrArray;
        hrArray = new hr("StorageCollectionSwitch", 86, 87);
        aI = hrArray;
        hrArray = new hr("StorageCollectionFrequency", 87, 88);
        aJ = hrArray;
        hrArray = new hr("PopupDialogWhiteList", 88, 94);
        aK = hrArray;
        hrArray = new hr("PopupDialogContent", 89, 95);
        aL = hrArray;
        hrArray = new hr("PopupDialogSwitch", 90, 96);
        aM = hrArray;
        hrArray = new hr("FallDownTimeRange", 91, 97);
        aN = hrArray;
        hrArray = new hr("AppIsInstalledCollectionSwitch", 92, 98);
        aO = hrArray;
        hrArray = new hr("AppIsInstalledCollectionFrequency", 93, 99);
        aP = hrArray;
        hrArray = new hr("AppIsInstalledList", 94, 100);
        aQ = hrArray;
        hrArray = new hr("TopNotificationUpdateFrequency", 95, 101);
        aR = hrArray;
        hrArray = new hr("TopNotificationUpdatePeriod", 96, 102);
        aS = hrArray;
        hrArray = new hr("TopNotificationUpdateSwitch", 97, 103);
        aT = hrArray;
        hrArray = new hr("EventUploadNewSwitch", 98, 104);
        aU = hrArray;
        hrArray = new hr("ScreenOnOrChargingTinyDataUploadSwitch", 99, 105);
        aV = hrArray;
        hrArray = new hr("NotificationAutoGroupSwitch", 100, 106);
        aW = hrArray;
        hrArray = new hr("LatestNotificationNotIntoGroupSwitch", 101, 107);
        aX = hrArray;
        hrArray = new hr("DCJobMutualSwitch", 102, 108);
        aY = hrArray;
        hrArray = new hr("StatDataUploadFrequency", 103, 120);
        aZ = hrArray;
        hrArray = new hr("StatDataUploadNum", 104, 121);
        ba = hrArray;
        hrArray = new hr("StatDataProcessFrequency", 105, 122);
        bb = hrArray;
        hrArray = new hr("StatDataSwitch", 106, 123);
        bc = hrArray;
        hrArray = new hr("StatDataUploadWay", 107, 124);
        bd = hrArray;
        hrArray = new hr("StatDataDeleteFrequency", 108, 125);
        be = hrArray;
        hrArray = new hr("CollectionDataPluginVersion", 109, 1001);
        bf = hrArray;
        hrArray = new hr("CollectionPluginDownloadUrl", 110, 1002);
        bg = hrArray;
        hrArray = new hr("CollectionPluginMd5", 111, 1003);
        bh = hrArray;
        hrArray = new hr("CollectionPluginForceStop", 112, 1004);
        bi = hrArray;
        hrArray = new hr[113];
        hrArray[0] = hr2 = a;
        hrArray[n10] = hr2 = b;
        hrArray[n11] = hr2 = c;
        hrArray[n12] = hr2 = d;
        hrArray[n13] = hr2 = e;
        hrArray[n14] = hr2 = f;
        hrArray[n15] = hr2 = g;
        hrArray[n16] = hr2 = h;
        hrArray[n17] = hr2 = i;
        hrArray[n18] = hr2 = j;
        hrArray[n19] = hr2 = k;
        hrArray[n20] = hr2 = l;
        hrArray[n21] = hr2 = m;
        hrArray[13] = hr2 = n;
        hrArray[14] = hr2 = o;
        hrArray[15] = hr2 = p;
        hrArray[16] = hr2 = q;
        hrArray[17] = hr2 = r;
        hrArray[18] = hr2 = s;
        hrArray[19] = hr2 = t;
        hrArray[20] = hr2 = u;
        hrArray[21] = hr2 = v;
        hrArray[22] = hr2 = w;
        hrArray[23] = hr2 = x;
        hrArray[24] = hr2 = y;
        hrArray[25] = hr2 = z;
        hrArray[26] = hr2 = A;
        hrArray[27] = hr2 = B;
        hrArray[28] = hr2 = C;
        hrArray[29] = hr2 = D;
        hrArray[30] = hr2 = E;
        hrArray[31] = hr2 = F;
        hrArray[32] = hr2 = G;
        hrArray[33] = hr2 = H;
        hrArray[34] = hr2 = I;
        hrArray[35] = hr2 = J;
        hrArray[36] = hr2 = K;
        hrArray[37] = hr2 = L;
        hrArray[38] = hr2 = M;
        hrArray[39] = hr2 = N;
        hrArray[40] = hr2 = O;
        hrArray[41] = hr2 = P;
        hrArray[42] = hr2 = Q;
        hrArray[43] = hr2 = R;
        hrArray[44] = hr2 = S;
        hrArray[45] = hr2 = T;
        hrArray[46] = hr2 = U;
        hrArray[47] = hr2 = V;
        hrArray[48] = hr2 = W;
        hrArray[49] = hr2 = X;
        hrArray[50] = hr2 = Y;
        hrArray[51] = hr2 = Z;
        hrArray[52] = hr2 = aa;
        hrArray[53] = hr2 = ab;
        hrArray[54] = hr2 = ac;
        hrArray[55] = hr2 = ad;
        hrArray[56] = hr2 = ae;
        hrArray[57] = hr2 = af;
        hrArray[58] = hr2 = ag;
        hrArray[59] = hr2 = ah;
        hrArray[60] = hr2 = ai;
        hrArray[61] = hr2 = aj;
        hrArray[62] = hr2 = ak;
        hrArray[63] = hr2 = al;
        hrArray[64] = hr2 = am;
        hrArray[65] = hr2 = an;
        hrArray[66] = hr2 = ao;
        hrArray[67] = hr2 = ap;
        hrArray[68] = hr2 = aq;
        hrArray[69] = hr2 = ar;
        hrArray[70] = hr2 = as;
        hrArray[71] = hr2 = at;
        hrArray[72] = hr2 = au;
        hrArray[73] = hr2 = av;
        hrArray[74] = hr2 = aw;
        hrArray[75] = hr2 = ax;
        hrArray[76] = hr2 = ay;
        hrArray[77] = hr2 = az;
        hrArray[78] = hr2 = aA;
        hrArray[79] = hr2 = aB;
        hrArray[80] = hr2 = aC;
        hrArray[81] = hr2 = aD;
        hrArray[82] = hr2 = aE;
        hrArray[83] = hr2 = aF;
        hrArray[84] = hr2 = aG;
        hrArray[85] = hr2 = aH;
        hrArray[86] = hr2 = aI;
        hrArray[87] = hr2 = aJ;
        hrArray[88] = hr2 = aK;
        hrArray[89] = hr2 = aL;
        hrArray[90] = hr2 = aM;
        hrArray[91] = hr2 = aN;
        hrArray[92] = hr2 = aO;
        hrArray[93] = hr2 = aP;
        hrArray[94] = hr2 = aQ;
        hrArray[95] = hr2 = aR;
        hrArray[96] = hr2 = aS;
        hrArray[97] = hr2 = aT;
        hrArray[98] = hr2 = aU;
        hrArray[99] = hr2 = aV;
        hrArray[100] = hr2 = aW;
        hrArray[101] = hr2 = aX;
        hrArray[102] = hr2 = aY;
        hrArray[103] = hr2 = aZ;
        hrArray[104] = hr2 = ba;
        hrArray[105] = hr2 = bb;
        hrArray[106] = hr2 = bc;
        hrArray[107] = hr2 = bd;
        hrArray[108] = hr2 = be;
        hrArray[109] = hr2 = bf;
        hrArray[110] = hr2 = bg;
        hrArray[111] = hr2 = bh;
        hrArray[112] = hr2 = bi;
        a = hrArray;
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private hr() {
        void var3_1;
        void var2_-1;
        void var1_-1;
        this.a = var3_1;
    }

    public static hr valueOf(String string2) {
        return Enum.valueOf(hr.class, string2);
    }

    public static hr[] values() {
        return (hr[])a.clone();
    }

    public int a() {
        return this.a;
    }
}

