/*
 * Decompiled with CFR 0.151.
 */
package com.google.android.gms.internal.mlkit_vision_face;

import com.google.android.gms.internal.mlkit_vision_face.zzca;
import com.google.android.gms.internal.mlkit_vision_face.zzcc;
import com.google.android.gms.internal.mlkit_vision_face.zzgf;
import com.google.android.gms.internal.mlkit_vision_face.zzgh;
import com.google.android.gms.internal.mlkit_vision_face.zzgi;

public final class zzcb
extends Enum
implements zzgf {
    public static final /* enum */ zzcb zza;
    private static final /* enum */ zzcb zzaa;
    private static final /* enum */ zzcb zzab;
    private static final /* enum */ zzcb zzac;
    private static final /* enum */ zzcb zzad;
    private static final /* enum */ zzcb zzae;
    private static final /* enum */ zzcb zzaf;
    private static final /* enum */ zzcb zzag;
    private static final /* enum */ zzcb zzah;
    private static final /* enum */ zzcb zzai;
    private static final /* enum */ zzcb zzaj;
    private static final /* enum */ zzcb zzak;
    private static final /* enum */ zzcb zzal;
    private static final /* enum */ zzcb zzam;
    private static final /* enum */ zzcb zzan;
    private static final /* enum */ zzcb zzao;
    private static final /* enum */ zzcb zzap;
    private static final /* enum */ zzcb zzaq;
    private static final /* enum */ zzcb zzar;
    private static final /* enum */ zzcb zzas;
    private static final /* enum */ zzcb zzat;
    private static final /* enum */ zzcb zzau;
    private static final /* enum */ zzcb zzav;
    private static final /* enum */ zzcb zzaw;
    private static final /* enum */ zzcb zzax;
    private static final /* enum */ zzcb zzay;
    private static final /* enum */ zzcb zzaz;
    public static final /* enum */ zzcb zzb;
    private static final /* enum */ zzcb zzba;
    private static final /* enum */ zzcb zzbb;
    private static final /* enum */ zzcb zzbc;
    private static final /* enum */ zzcb zzbd;
    private static final /* enum */ zzcb zzbe;
    private static final /* enum */ zzcb zzbf;
    private static final /* enum */ zzcb zzbg;
    private static final /* enum */ zzcb zzbh;
    private static final /* enum */ zzcb zzbi;
    private static final /* enum */ zzcb zzbj;
    private static final /* enum */ zzcb zzbk;
    private static final /* enum */ zzcb zzbl;
    private static final /* enum */ zzcb zzbm;
    private static final /* enum */ zzcb zzbn;
    private static final /* enum */ zzcb zzbo;
    private static final /* enum */ zzcb zzbp;
    private static final /* enum */ zzcb zzbq;
    private static final /* enum */ zzcb zzbr;
    private static final /* enum */ zzcb zzbs;
    private static final /* enum */ zzcb zzbt;
    private static final /* enum */ zzcb zzbu;
    private static final /* enum */ zzcb zzbv;
    private static final /* enum */ zzcb zzbw;
    private static final /* enum */ zzcb zzbx;
    private static final /* enum */ zzcb zzby;
    private static final /* enum */ zzcb zzbz;
    public static final /* enum */ zzcb zzc;
    private static final /* enum */ zzcb zzca;
    private static final /* enum */ zzcb zzcb;
    private static final /* enum */ zzcb zzcc;
    private static final /* enum */ zzcb zzcd;
    private static final /* enum */ zzcb zzce;
    private static final /* enum */ zzcb zzcf;
    private static final /* enum */ zzcb zzcg;
    private static final /* enum */ zzcb zzch;
    private static final /* enum */ zzcb zzci;
    private static final /* enum */ zzcb zzcj;
    private static final /* enum */ zzcb zzck;
    private static final /* enum */ zzcb zzcl;
    private static final /* enum */ zzcb zzcm;
    private static final /* enum */ zzcb zzcn;
    private static final /* enum */ zzcb zzco;
    private static final /* enum */ zzcb zzcp;
    private static final /* enum */ zzcb zzcq;
    private static final /* enum */ zzcb zzcr;
    private static final /* enum */ zzcb zzcs;
    private static final /* enum */ zzcb zzct;
    private static final /* enum */ zzcb zzcu;
    private static final /* enum */ zzcb zzcv;
    private static final /* enum */ zzcb zzcw;
    private static final /* enum */ zzcb zzcx;
    private static final /* enum */ zzcb zzcy;
    private static final /* enum */ zzcb zzcz;
    private static final /* enum */ zzcb zzd;
    private static final /* enum */ zzcb zzda;
    private static final /* enum */ zzcb zzdb;
    private static final /* enum */ zzcb zzdc;
    private static final /* enum */ zzcb zzdd;
    private static final /* enum */ zzcb zzde;
    private static final /* enum */ zzcb zzdf;
    private static final /* enum */ zzcb zzdg;
    private static final /* enum */ zzcb zzdh;
    private static final /* enum */ zzcb zzdi;
    private static final /* enum */ zzcb zzdj;
    private static final /* enum */ zzcb zzdk;
    private static final /* enum */ zzcb zzdl;
    private static final /* enum */ zzcb zzdm;
    private static final /* enum */ zzcb zzdn;
    private static final /* enum */ zzcb zzdo;
    private static final /* enum */ zzcb zzdp;
    private static final /* enum */ zzcb zzdq;
    private static final zzgi zzdr;
    private static final /* synthetic */ zzcb[] zzdt;
    private static final /* enum */ zzcb zze;
    private static final /* enum */ zzcb zzf;
    private static final /* enum */ zzcb zzg;
    private static final /* enum */ zzcb zzh;
    private static final /* enum */ zzcb zzi;
    private static final /* enum */ zzcb zzj;
    private static final /* enum */ zzcb zzk;
    private static final /* enum */ zzcb zzl;
    private static final /* enum */ zzcb zzm;
    private static final /* enum */ zzcb zzn;
    private static final /* enum */ zzcb zzo;
    private static final /* enum */ zzcb zzp;
    private static final /* enum */ zzcb zzq;
    private static final /* enum */ zzcb zzr;
    private static final /* enum */ zzcb zzs;
    private static final /* enum */ zzcb zzt;
    private static final /* enum */ zzcb zzu;
    private static final /* enum */ zzcb zzv;
    private static final /* enum */ zzcb zzw;
    private static final /* enum */ zzcb zzx;
    private static final /* enum */ zzcb zzy;
    private static final /* enum */ zzcb zzz;
    private final int zzds;

    static {
        zzcb zzcb2;
        Object object = new zzcb("UNKNOWN_EVENT", 0, 0);
        zzd = object;
        int n10 = 1;
        object = new zzcb("ON_DEVICE_FACE_DETECT", n10, n10);
        zza = object;
        int n11 = 2;
        object = new zzcb("ON_DEVICE_FACE_CREATE", n11, n11);
        zzb = object;
        int n12 = 3;
        object = new zzcb("ON_DEVICE_FACE_CLOSE", n12, n12);
        zze = object;
        int n13 = 11;
        object = new zzcb("ON_DEVICE_TEXT_DETECT", 4, n13);
        zzf = object;
        int n14 = 12;
        object = new zzcb("ON_DEVICE_TEXT_CREATE", 5, n14);
        zzg = object;
        int n15 = 13;
        object = new zzcb("ON_DEVICE_TEXT_CLOSE", 6, n15);
        zzh = object;
        int n16 = 21;
        object = new zzcb("ON_DEVICE_BARCODE_DETECT", 7, n16);
        zzi = object;
        int n17 = 22;
        object = new zzcb("ON_DEVICE_BARCODE_CREATE", 8, n17);
        zzj = object;
        int n18 = 23;
        object = new zzcb("ON_DEVICE_BARCODE_CLOSE", 9, n18);
        zzk = object;
        object = new zzcb("ON_DEVICE_IMAGE_LABEL_DETECT", 10, 141);
        zzl = object;
        object = new zzcb("ON_DEVICE_IMAGE_LABEL_CREATE", n13, 142);
        zzm = object;
        object = new zzcb("ON_DEVICE_IMAGE_LABEL_CLOSE", n14, 143);
        zzn = object;
        object = new zzcb("ON_DEVICE_IMAGE_LABEL_LOAD", n15, 144);
        zzo = object;
        object = new zzcb("ON_DEVICE_SMART_REPLY_DETECT", 14, 151);
        zzp = object;
        object = new zzcb("ON_DEVICE_SMART_REPLY_CREATE", 15, 152);
        zzq = object;
        object = new zzcb("ON_DEVICE_SMART_REPLY_CLOSE", 16, 153);
        zzr = object;
        object = new zzcb("ON_DEVICE_SMART_REPLY_BLACKLIST_UPDATE", 17, 154);
        zzs = object;
        object = new zzcb("ON_DEVICE_LANGUAGE_IDENTIFICATION_DETECT", 18, 161);
        zzt = object;
        object = new zzcb("ON_DEVICE_LANGUAGE_IDENTIFICATION_CREATE", 19, 162);
        zzu = object;
        object = new zzcb("ON_DEVICE_LANGUAGE_IDENTIFICATION_LOAD", 20, 164);
        zzv = object;
        object = new zzcb("ON_DEVICE_LANGUAGE_IDENTIFICATION_CLOSE", n16, 163);
        zzw = object;
        object = new zzcb("ON_DEVICE_TRANSLATOR_TRANSLATE", n17, 171);
        zzx = object;
        object = new zzcb("ON_DEVICE_TRANSLATOR_CREATE", n18, 172);
        zzy = object;
        object = new zzcb("ON_DEVICE_TRANSLATOR_LOAD", 24, 173);
        zzz = object;
        object = new zzcb("ON_DEVICE_TRANSLATOR_CLOSE", 25, 174);
        zzaa = object;
        object = new zzcb("ON_DEVICE_TRANSLATOR_DOWNLOAD", 26, 175);
        zzab = object;
        object = new zzcb("ON_DEVICE_ENTITY_EXTRACTION_ANNOTATE", 27, 241);
        zzac = object;
        object = new zzcb("ON_DEVICE_ENTITY_EXTRACTION_CREATE", 28, 242);
        zzad = object;
        object = new zzcb("ON_DEVICE_ENTITY_EXTRACTION_LOAD", 29, 243);
        zzae = object;
        object = new zzcb("ON_DEVICE_ENTITY_EXTRACTION_CLOSE", 30, 244);
        zzaf = object;
        int n19 = 31;
        object = new zzcb("ON_DEVICE_ENTITY_EXTRACTION_DOWNLOAD", n19, 245);
        zzag = object;
        int n20 = 32;
        object = new zzcb("ON_DEVICE_OBJECT_CREATE", n20, 191);
        zzah = object;
        int n21 = 33;
        object = new zzcb("ON_DEVICE_OBJECT_LOAD", n21, 192);
        zzai = object;
        object = new zzcb("ON_DEVICE_OBJECT_INFERENCE", 34, 193);
        zzaj = object;
        object = new zzcb("ON_DEVICE_OBJECT_CLOSE", 35, 194);
        zzak = object;
        object = new zzcb("ON_DEVICE_DI_CREATE", 36, 311);
        zzal = object;
        object = new zzcb("ON_DEVICE_DI_LOAD", 37, 312);
        zzam = object;
        object = new zzcb("ON_DEVICE_DI_DOWNLOAD", 38, 313);
        zzan = object;
        object = new zzcb("ON_DEVICE_DI_RECOGNIZE", 39, 314);
        zzao = object;
        object = new zzcb("ON_DEVICE_DI_CLOSE", 40, 315);
        zzap = object;
        n18 = 41;
        object = new zzcb("ON_DEVICE_POSE_CREATE", n18, 321);
        zzaq = object;
        int n22 = 42;
        object = new zzcb("ON_DEVICE_POSE_LOAD", n22, 322);
        zzar = object;
        n17 = 43;
        object = new zzcb("ON_DEVICE_POSE_INFERENCE", n17, 323);
        zzas = object;
        object = new zzcb("ON_DEVICE_POSE_CLOSE", 44, 324);
        zzat = object;
        object = new zzcb("ON_DEVICE_SEGMENTATION_CREATE", 45, 331);
        zzau = object;
        object = new zzcb("ON_DEVICE_SEGMENTATION_LOAD", 46, 332);
        zzav = object;
        object = new zzcb("ON_DEVICE_SEGMENTATION_INFERENCE", 47, 333);
        zzaw = object;
        object = new zzcb("ON_DEVICE_SEGMENTATION_CLOSE", 48, 334);
        zzax = object;
        object = new zzcb("CUSTOM_OBJECT_CREATE", 49, 341);
        zzay = object;
        object = new zzcb("CUSTOM_OBJECT_LOAD", 50, 342);
        zzaz = object;
        n15 = 51;
        object = new zzcb("CUSTOM_OBJECT_INFERENCE", n15, 343);
        zzba = object;
        n16 = 52;
        object = new zzcb("CUSTOM_OBJECT_CLOSE", n16, 344);
        zzbb = object;
        n14 = 53;
        object = new zzcb("CUSTOM_IMAGE_LABEL_CREATE", n14, 351);
        zzbc = object;
        object = new zzcb("CUSTOM_IMAGE_LABEL_LOAD", 54, 352);
        zzbd = object;
        object = new zzcb("CUSTOM_IMAGE_LABEL_DETECT", 55, 353);
        zzbe = object;
        object = new zzcb("CUSTOM_IMAGE_LABEL_CLOSE", 56, 354);
        zzbf = object;
        object = new zzcb("CLOUD_FACE_DETECT", 57, n19);
        zzbg = object;
        object = new zzcb("CLOUD_FACE_CREATE", 58, n20);
        zzbh = object;
        object = new zzcb("CLOUD_FACE_CLOSE", 59, n21);
        zzbi = object;
        object = new zzcb("CLOUD_CROP_HINTS_CREATE", 60, n18);
        zzbj = object;
        n12 = 61;
        object = new zzcb("CLOUD_CROP_HINTS_DETECT", n12, n22);
        zzbk = object;
        n13 = 62;
        object = new zzcb("CLOUD_CROP_HINTS_CLOSE", n13, n17);
        zzbl = object;
        n17 = 63;
        object = new zzcb("CLOUD_DOCUMENT_TEXT_CREATE", n17, n15);
        zzbm = object;
        object = new zzcb("CLOUD_DOCUMENT_TEXT_DETECT", 64, n16);
        zzbn = object;
        object = new zzcb("CLOUD_DOCUMENT_TEXT_CLOSE", 65, n14);
        zzbo = object;
        object = new zzcb("CLOUD_IMAGE_PROPERTIES_CREATE", 66, n12);
        zzbp = object;
        object = new zzcb("CLOUD_IMAGE_PROPERTIES_DETECT", 67, n13);
        zzbq = object;
        object = new zzcb("CLOUD_IMAGE_PROPERTIES_CLOSE", 68, n17);
        zzbr = object;
        object = new zzcb("CLOUD_IMAGE_LABEL_CREATE", 69, 71);
        zzbs = object;
        object = new zzcb("CLOUD_IMAGE_LABEL_DETECT", 70, 72);
        zzbt = object;
        object = new zzcb("CLOUD_IMAGE_LABEL_CLOSE", 71, 73);
        zzbu = object;
        object = new zzcb("CLOUD_LANDMARK_CREATE", 72, 81);
        zzbv = object;
        object = new zzcb("CLOUD_LANDMARK_DETECT", 73, 82);
        zzbw = object;
        object = new zzcb("CLOUD_LANDMARK_CLOSE", 74, 83);
        zzbx = object;
        object = new zzcb("CLOUD_LOGO_CREATE", 75, 91);
        zzby = object;
        object = new zzcb("CLOUD_LOGO_DETECT", 76, 92);
        zzbz = object;
        object = new zzcb("CLOUD_LOGO_CLOSE", 77, 93);
        zzca = object;
        object = new zzcb("CLOUD_SAFE_SEARCH_CREATE", 78, 111);
        zzcb = object;
        object = new zzcb("CLOUD_SAFE_SEARCH_DETECT", 79, 112);
        zzcc = object;
        object = new zzcb("CLOUD_SAFE_SEARCH_CLOSE", 80, 113);
        zzcd = object;
        object = new zzcb("CLOUD_TEXT_CREATE", 81, 121);
        zzce = object;
        object = new zzcb("CLOUD_TEXT_DETECT", 82, 122);
        zzcf = object;
        object = new zzcb("CLOUD_TEXT_CLOSE", 83, 123);
        zzcg = object;
        object = new zzcb("CLOUD_WEB_SEARCH_CREATE", 84, 131);
        zzch = object;
        object = new zzcb("CLOUD_WEB_SEARCH_DETECT", 85, 132);
        zzci = object;
        object = new zzcb("CLOUD_WEB_SEARCH_CLOSE", 86, 133);
        zzcj = object;
        object = new zzcb("CUSTOM_MODEL_RUN", 87, 102);
        zzck = object;
        object = new zzcb("CUSTOM_MODEL_CREATE", 88, 103);
        zzcl = object;
        object = new zzcb("CUSTOM_MODEL_CLOSE", 89, 104);
        zzcm = object;
        object = new zzcb("CUSTOM_MODEL_LOAD", 90, 105);
        zzcn = object;
        object = new zzcb("AUTOML_IMAGE_LABELING_RUN", 91, 181);
        zzco = object;
        object = new zzcb("AUTOML_IMAGE_LABELING_CREATE", 92, 182);
        zzcp = object;
        object = new zzcb("AUTOML_IMAGE_LABELING_CLOSE", 93, 183);
        zzcq = object;
        object = new zzcb("AUTOML_IMAGE_LABELING_LOAD", 94, 184);
        zzcr = object;
        object = new zzcb("MODEL_DOWNLOAD", 95, 100);
        zzcs = object;
        object = new zzcb("MODEL_UPDATE", 96, 101);
        zzct = object;
        object = new zzcb("REMOTE_MODEL_IS_DOWNLOADED", 97, 251);
        zzcu = object;
        object = new zzcb("REMOTE_MODEL_DELETE_ON_DEVICE", 98, 252);
        zzcv = object;
        object = new zzcb("ACCELERATION_ANALYTICS", 99, 260);
        zzcw = object;
        object = new zzcb("AGGREGATED_AUTO_ML_IMAGE_LABELING_INFERENCE", 100, 200);
        zzcx = object;
        object = new zzcb("AGGREGATED_CUSTOM_MODEL_INFERENCE", 101, 201);
        zzcy = object;
        object = new zzcb("AGGREGATED_ON_DEVICE_BARCODE_DETECTION", 102, 202);
        zzcz = object;
        object = new zzcb("AGGREGATED_ON_DEVICE_FACE_DETECTION", 103, 203);
        zzc = object;
        object = new zzcb("AGGREGATED_ON_DEVICE_IMAGE_LABEL_DETECTION", 104, 204);
        zzda = object;
        object = new zzcb("AGGREGATED_ON_DEVICE_OBJECT_INFERENCE", 105, 205);
        zzdb = object;
        object = new zzcb("AGGREGATED_ON_DEVICE_TEXT_DETECTION", 106, 206);
        zzdc = object;
        object = new zzcb("AGGREGATED_ON_DEVICE_POSE_DETECTION", 107, 207);
        zzdd = object;
        object = new zzcb("AGGREGATED_ON_DEVICE_SEGMENTATION", 108, 208);
        zzde = object;
        object = new zzcb("AGGREGATED_CUSTOM_OBJECT_INFERENCE", 109, 209);
        zzdf = object;
        object = new zzcb("AGGREGATED_CUSTOM_IMAGE_LABEL_DETECTION", 110, 210);
        zzdg = object;
        object = new zzcb("REMOTE_CONFIG_FETCH", 111, 271);
        zzdh = object;
        object = new zzcb("REMOTE_CONFIG_ACTIVATE", 112, 272);
        zzdi = object;
        object = new zzcb("REMOTE_CONFIG_FRC_FETCH", 113, 281);
        zzdj = object;
        object = new zzcb("INSTALLATION_ID_INIT", 114, 291);
        zzdk = object;
        object = new zzcb("INSTALLATION_ID_REGISTER_NEW_ID", 115, 292);
        zzdl = object;
        object = new zzcb("INSTALLATION_ID_REFRESH_TEMPORARY_TOKEN", 116, 293);
        zzdm = object;
        object = new zzcb("INSTALLATION_ID_FIS_CREATE_INSTALLATION", 117, 301);
        zzdn = object;
        object = new zzcb("INSTALLATION_ID_FIS_GENERATE_AUTH_TOKEN", 118, 302);
        zzdo = object;
        object = new zzcb("INPUT_IMAGE_CONSTRUCTION", 119, 361);
        zzdp = object;
        object = new zzcb("HANDLE_LEAKED", 120, 371);
        zzdq = object;
        object = new zzcb[121];
        object[0] = zzcb2 = zzd;
        object[n10] = zzcb2 = zza;
        object[n11] = zzcb2 = zzb;
        object[3] = zzcb2 = zze;
        object[4] = zzcb2 = zzf;
        object[5] = zzcb2 = zzg;
        object[6] = zzcb2 = zzh;
        object[7] = zzcb2 = zzi;
        object[8] = zzcb2 = zzj;
        object[9] = zzcb2 = zzk;
        object[10] = zzcb2 = zzl;
        object[11] = zzcb2 = zzm;
        object[12] = zzcb2 = zzn;
        object[13] = zzcb2 = zzo;
        object[14] = zzcb2 = zzp;
        object[15] = zzcb2 = zzq;
        object[16] = zzcb2 = zzr;
        object[17] = zzcb2 = zzs;
        object[18] = zzcb2 = zzt;
        object[19] = zzcb2 = zzu;
        object[20] = zzcb2 = zzv;
        object[21] = zzcb2 = zzw;
        object[22] = zzcb2 = zzx;
        object[23] = zzcb2 = zzy;
        object[24] = zzcb2 = zzz;
        object[25] = zzcb2 = zzaa;
        object[26] = zzcb2 = zzab;
        object[27] = zzcb2 = zzac;
        object[28] = zzcb2 = zzad;
        object[29] = zzcb2 = zzae;
        object[30] = zzcb2 = zzaf;
        object[n19] = zzcb2 = zzag;
        object[n20] = zzcb2 = zzah;
        object[n21] = zzcb2 = zzai;
        object[34] = zzcb2 = zzaj;
        object[35] = zzcb2 = zzak;
        object[36] = zzcb2 = zzal;
        object[37] = zzcb2 = zzam;
        object[38] = zzcb2 = zzan;
        object[39] = zzcb2 = zzao;
        object[40] = zzcb2 = zzap;
        object[n18] = zzcb2 = zzaq;
        object[n22] = zzcb2 = zzar;
        object[43] = zzcb2 = zzas;
        object[44] = zzcb2 = zzat;
        object[45] = zzcb2 = zzau;
        object[46] = zzcb2 = zzav;
        object[47] = zzcb2 = zzaw;
        object[48] = zzcb2 = zzax;
        object[49] = zzcb2 = zzay;
        object[50] = zzcb2 = zzaz;
        object[51] = zzcb2 = zzba;
        object[n16] = zzcb2 = zzbb;
        object[n14] = zzcb2 = zzbc;
        object[54] = zzcb2 = zzbd;
        object[55] = zzcb2 = zzbe;
        object[56] = zzcb2 = zzbf;
        object[57] = zzcb2 = zzbg;
        object[58] = zzcb2 = zzbh;
        object[59] = zzcb2 = zzbi;
        object[60] = zzcb2 = zzbj;
        object[n12] = zzcb2 = zzbk;
        object[n13] = zzcb2 = zzbl;
        object[63] = zzcb2 = zzbm;
        object[64] = zzcb2 = zzbn;
        object[65] = zzcb2 = zzbo;
        object[66] = zzcb2 = zzbp;
        object[67] = zzcb2 = zzbq;
        object[68] = zzcb2 = zzbr;
        object[69] = zzcb2 = zzbs;
        object[70] = zzcb2 = zzbt;
        object[71] = zzcb2 = zzbu;
        object[72] = zzcb2 = zzbv;
        object[73] = zzcb2 = zzbw;
        object[74] = zzcb2 = zzbx;
        object[75] = zzcb2 = zzby;
        object[76] = zzcb2 = zzbz;
        object[77] = zzcb2 = zzca;
        object[78] = zzcb2 = zzcb;
        object[79] = zzcb2 = zzcc;
        object[80] = zzcb2 = zzcd;
        object[81] = zzcb2 = zzce;
        object[82] = zzcb2 = zzcf;
        object[83] = zzcb2 = zzcg;
        object[84] = zzcb2 = zzch;
        object[85] = zzcb2 = zzci;
        object[86] = zzcb2 = zzcj;
        object[87] = zzcb2 = zzck;
        object[88] = zzcb2 = zzcl;
        object[89] = zzcb2 = zzcm;
        object[90] = zzcb2 = zzcn;
        object[91] = zzcb2 = zzco;
        object[92] = zzcb2 = zzcp;
        object[93] = zzcb2 = zzcq;
        object[94] = zzcb2 = zzcr;
        object[95] = zzcb2 = zzcs;
        object[96] = zzcb2 = zzct;
        object[97] = zzcb2 = zzcu;
        object[98] = zzcb2 = zzcv;
        object[99] = zzcb2 = zzcw;
        object[100] = zzcb2 = zzcx;
        object[101] = zzcb2 = zzcy;
        object[102] = zzcb2 = zzcz;
        object[103] = zzcb2 = zzc;
        object[104] = zzcb2 = zzda;
        object[105] = zzcb2 = zzdb;
        object[106] = zzcb2 = zzdc;
        object[107] = zzcb2 = zzdd;
        object[108] = zzcb2 = zzde;
        object[109] = zzcb2 = zzdf;
        object[110] = zzcb2 = zzdg;
        object[111] = zzcb2 = zzdh;
        object[112] = zzcb2 = zzdi;
        object[113] = zzcb2 = zzdj;
        object[114] = zzcb2 = zzdk;
        object[115] = zzcb2 = zzdl;
        object[116] = zzcb2 = zzdm;
        object[117] = zzcb2 = zzdn;
        object[118] = zzcb2 = zzdo;
        object[119] = zzcb2 = zzdp;
        object[120] = zzcb2 = zzdq;
        zzdt = object;
        zzdr = object = new zzca();
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private zzcb() {
        void var3_1;
        void var2_-1;
        void var1_-1;
        this.zzds = var3_1;
    }

    public static zzcb[] values() {
        return (zzcb[])zzdt.clone();
    }

    public static zzgh zzb() {
        return com.google.android.gms.internal.mlkit_vision_face.zzcc.zza;
    }

    public final String toString() {
        StringBuilder stringBuilder = new StringBuilder("<");
        String string2 = zzcb.class.getName();
        stringBuilder.append(string2);
        stringBuilder.append('@');
        string2 = Integer.toHexString(System.identityHashCode(this));
        stringBuilder.append(string2);
        stringBuilder.append(" number=");
        int n10 = this.zzds;
        stringBuilder.append(n10);
        stringBuilder.append(" name=");
        string2 = this.name();
        stringBuilder.append(string2);
        stringBuilder.append('>');
        return stringBuilder.toString();
    }

    public final int zza() {
        return this.zzds;
    }
}

