/*
 * Decompiled with CFR 0.151.
 * 
 * Could not load the following classes:
 *  android.content.Context
 *  android.os.Handler
 */
package com.google.android.exoplayer2.upstream;

import android.content.Context;
import android.os.Handler;
import com.google.android.exoplayer2.upstream.BandwidthMeter;
import com.google.android.exoplayer2.upstream.BandwidthMeter$EventListener;
import com.google.android.exoplayer2.upstream.BandwidthMeter$EventListener$EventDispatcher;
import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.upstream.DataSpec;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter$1;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter$Builder;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter$ConnectivityActionReceiver;
import com.google.android.exoplayer2.upstream.TransferListener;
import com.google.android.exoplayer2.util.Assertions;
import com.google.android.exoplayer2.util.Clock;
import com.google.android.exoplayer2.util.SlidingPercentile;
import com.google.android.exoplayer2.util.Util;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableListMultimap;
import com.google.common.collect.ImmutableListMultimap$Builder;
import com.google.common.collect.ImmutableMap;
import java.io.Serializable;
import java.util.Map;

public final class DefaultBandwidthMeter
implements BandwidthMeter,
TransferListener {
    private static final int BYTES_TRANSFERRED_FOR_ESTIMATE = 524288;
    private static final int COUNTRY_GROUP_INDEX_2G = 1;
    private static final int COUNTRY_GROUP_INDEX_3G = 2;
    private static final int COUNTRY_GROUP_INDEX_4G = 3;
    private static final int COUNTRY_GROUP_INDEX_5G_NSA = 4;
    private static final int COUNTRY_GROUP_INDEX_WIFI = 0;
    public static final ImmutableListMultimap DEFAULT_INITIAL_BITRATE_COUNTRY_GROUPS = DefaultBandwidthMeter.createInitialBitrateCountryGroupAssignment();
    public static final long DEFAULT_INITIAL_BITRATE_ESTIMATE = 1000000L;
    public static final ImmutableList DEFAULT_INITIAL_BITRATE_ESTIMATES_2G;
    public static final ImmutableList DEFAULT_INITIAL_BITRATE_ESTIMATES_3G;
    public static final ImmutableList DEFAULT_INITIAL_BITRATE_ESTIMATES_4G;
    public static final ImmutableList DEFAULT_INITIAL_BITRATE_ESTIMATES_5G_NSA;
    public static final ImmutableList DEFAULT_INITIAL_BITRATE_ESTIMATES_WIFI;
    public static final int DEFAULT_SLIDING_WINDOW_MAX_WEIGHT = 2000;
    private static final int ELAPSED_MILLIS_FOR_ESTIMATE = 2000;
    private static DefaultBandwidthMeter singletonInstance;
    private long bitrateEstimate;
    private final Clock clock;
    private final Context context;
    private final BandwidthMeter$EventListener$EventDispatcher eventDispatcher;
    private final ImmutableMap initialBitrateEstimates;
    private long lastReportedBitrateEstimate;
    private int networkType;
    private int networkTypeOverride;
    private boolean networkTypeOverrideSet;
    private long sampleBytesTransferred;
    private long sampleStartTimeMs;
    private final SlidingPercentile slidingPercentile;
    private int streamCount;
    private long totalBytesTransferred;
    private long totalElapsedTimeMs;

    static {
        Long l10 = 6100000L;
        Long l11 = 3800000L;
        Long l12 = 0x200B20L;
        Long l13 = 1300000L;
        Long l14 = 590000L;
        DEFAULT_INITIAL_BITRATE_ESTIMATES_WIFI = ImmutableList.of(l10, l11, l12, l13, l14);
        l10 = 218000L;
        l11 = 159000L;
        l12 = 145000L;
        l14 = 130000L;
        Long l15 = 112000L;
        DEFAULT_INITIAL_BITRATE_ESTIMATES_2G = ImmutableList.of(l10, l11, l12, l14, l15);
        l10 = 2200000L;
        l11 = 930000L;
        l12 = 730000L;
        l14 = 530000L;
        DEFAULT_INITIAL_BITRATE_ESTIMATES_3G = ImmutableList.of(l10, l13, l11, l12, l14);
        l10 = 4800000L;
        l11 = 2700000L;
        l12 = 1800000L;
        l13 = 1200000L;
        l14 = 630000L;
        DEFAULT_INITIAL_BITRATE_ESTIMATES_4G = ImmutableList.of(l10, l11, l12, l13, l14);
        l10 = 12000000L;
        l11 = 8800000L;
        l13 = 5900000L;
        l14 = 3500000L;
        DEFAULT_INITIAL_BITRATE_ESTIMATES_5G_NSA = ImmutableList.of(l10, l11, l13, l14, l12);
    }

    public DefaultBandwidthMeter() {
        ImmutableMap immutableMap = ImmutableMap.of();
        Clock clock = Clock.DEFAULT;
        this(null, immutableMap, 2000, clock, false);
    }

    private DefaultBandwidthMeter(Context object, Map object2, int n10, Clock clock, boolean bl2) {
        long l10;
        int n11;
        Context context = object == null ? null : object.getApplicationContext();
        this.context = context;
        object2 = ImmutableMap.copyOf((Map)object2);
        this.initialBitrateEstimates = object2;
        this.eventDispatcher = object2 = new BandwidthMeter$EventListener$EventDispatcher();
        this.slidingPercentile = object2 = new SlidingPercentile(n10);
        this.clock = clock;
        if (object == null) {
            n11 = 0;
            object2 = null;
        } else {
            n11 = Util.getNetworkType((Context)object);
        }
        this.networkType = n11;
        this.bitrateEstimate = l10 = this.getInitialBitrateEstimateForNetworkType(n11);
        if (object != null && bl2) {
            object = DefaultBandwidthMeter$ConnectivityActionReceiver.getInstance((Context)object);
            ((DefaultBandwidthMeter$ConnectivityActionReceiver)((Object)object)).register(this);
        }
    }

    public /* synthetic */ DefaultBandwidthMeter(Context context, Map map, int n10, Clock clock, boolean bl2, DefaultBandwidthMeter$1 defaultBandwidthMeter$1) {
        this(context, map, n10, clock, bl2);
    }

    public static /* synthetic */ void access$100(DefaultBandwidthMeter defaultBandwidthMeter) {
        defaultBandwidthMeter.onConnectivityAction();
    }

    private static ImmutableListMultimap createInitialBitrateCountryGroupAssignment() {
        Integer n10;
        ImmutableListMultimap$Builder immutableListMultimap$Builder = ImmutableListMultimap.builder();
        int n11 = 5;
        Object[] objectArray = new Integer[n11];
        int n12 = 1;
        Integer n13 = n12;
        Integer n14 = 0;
        objectArray[0] = n13;
        int n15 = 2;
        objectArray[n12] = n10 = Integer.valueOf(n15);
        objectArray[n15] = n14;
        int n16 = 3;
        Integer n17 = n16;
        objectArray[n16] = n14;
        int n18 = 4;
        Integer n19 = n18;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AD", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n13;
        immutableListMultimap$Builder.putAll((Object)"AE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AF", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AI", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AL", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n19;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n19;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AS", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n17;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AT", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n13;
        objectArray[n18] = n13;
        immutableListMultimap$Builder.putAll((Object)"AU", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AW", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AX", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"AZ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BB", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n14;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BD", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BF", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n14;
        objectArray[n15] = n10;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BH", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BI", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BJ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BL", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n14;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BN", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n17;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BQ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n19;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BS", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n14;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BT", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BW", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n14;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BY", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"BZ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n17;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n17;
        immutableListMultimap$Builder.putAll((Object)"CA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n17;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CD", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CF", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n14;
        immutableListMultimap$Builder.putAll((Object)"CH", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CI", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CK", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n13;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CL", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n17;
        immutableListMultimap$Builder.putAll((Object)"CN", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n19;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n17;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CU", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n17;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CV", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CW", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CY", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"CZ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n14;
        immutableListMultimap$Builder.putAll((Object)"DE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n13;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"DJ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"DK", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"DM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"DO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"DZ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n19;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"EC", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"EE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"EG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"EH", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"ER", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"ES", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"ET", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n14;
        immutableListMultimap$Builder.putAll((Object)"FI", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n14;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"FJ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"FK", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n19;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"FM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"FO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n14;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"FR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GB", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GD", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n14;
        objectArray[n15] = n13;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GF", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GH", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GI", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GL", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n17;
        objectArray[n15] = n10;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n17;
        objectArray[n15] = n19;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GN", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GP", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GQ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GT", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GU", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GW", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"GY", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"HK", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n14;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"HN", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"HR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n17;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"HT", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"HU", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"ID", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"IE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n14;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"IL", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"IM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n13;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"IN", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"IO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n19;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"IQ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"IR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"IS", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"IT", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"JE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"JM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"JO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n13;
        objectArray[n18] = n17;
        immutableListMultimap$Builder.putAll((Object)"JP", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"KE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n14;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"KG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n14;
        objectArray[n15] = n19;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"KH", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"KI", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"KM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"KN", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"KP", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n13;
        immutableListMultimap$Builder.putAll((Object)"KR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n17;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n13;
        immutableListMultimap$Builder.putAll((Object)"KW", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"KY", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"KZ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LB", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LC", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LI", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n14;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LK", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LS", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LT", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LU", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LV", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n19;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"LY", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n13;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MC", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MD", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"ME", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MF", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MH", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n14;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MK", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"ML", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n17;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n19;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MN", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MP", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MQ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n14;
        objectArray[n15] = n19;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MS", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MT", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n13;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MU", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n17;
        objectArray[n15] = n13;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MV", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n13;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MW", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n19;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MX", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n14;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MY", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"MZ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n17;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"NA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n14;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"NC", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"NE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"NF", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"NG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n13;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"NI", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n19;
        objectArray[n16] = n10;
        objectArray[n18] = n14;
        immutableListMultimap$Builder.putAll((Object)"NL", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"NO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n14;
        objectArray[n15] = n19;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"NP", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"NR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"NU", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n19;
        immutableListMultimap$Builder.putAll((Object)"NZ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"OM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n17;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PF", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n17;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n14;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n19;
        immutableListMultimap$Builder.putAll((Object)"PH", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PK", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n14;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PL", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n19;
        immutableListMultimap$Builder.putAll((Object)"PR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PS", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PT", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PW", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n14;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"PY", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n17;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"QA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n14;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"RE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n13;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"RO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"RS", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"RU", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n17;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"RW", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n19;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SB", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n14;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SC", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SD", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n19;
        immutableListMultimap$Builder.putAll((Object)"SG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SH", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SI", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SJ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SK", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n17;
        objectArray[n15] = n17;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SL", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SN", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n17;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n13;
        objectArray[n15] = n19;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SS", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"ST", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n13;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SV", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SX", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n17;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SY", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n19;
        objectArray[n15] = n17;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"SZ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TC", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TD", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n17;
        objectArray[n15] = n19;
        objectArray[n16] = n17;
        objectArray[n18] = n14;
        immutableListMultimap$Builder.putAll((Object)"TH", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TJ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n13;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TL", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TM", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n13;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TN", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n19;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TO", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TR", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n17;
        objectArray[n15] = n13;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TT", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TV", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n14;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n13;
        immutableListMultimap$Builder.putAll((Object)"TW", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n17;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"TZ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n17;
        objectArray[n15] = n14;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"UA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"UG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n17;
        objectArray[n16] = n17;
        objectArray[n18] = n17;
        immutableListMultimap$Builder.putAll((Object)"US", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n13;
        objectArray[n15] = n13;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"UY", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n14;
        objectArray[n15] = n17;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"UZ", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"VC", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"VE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"VG", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"VI", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n14;
        objectArray[n12] = n13;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"VN", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n13;
        objectArray[n15] = n17;
        objectArray[n16] = n13;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"VU", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n13;
        objectArray[n15] = n19;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"WS", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n13;
        objectArray[n12] = n13;
        objectArray[n15] = n13;
        objectArray[n16] = n14;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"XK", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n19;
        objectArray[n12] = n19;
        objectArray[n15] = n19;
        objectArray[n16] = n19;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"YE", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n13;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"YT", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n10;
        objectArray[n12] = n17;
        objectArray[n15] = n10;
        objectArray[n16] = n10;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"ZA", objectArray);
        objectArray = new Integer[n11];
        objectArray[0] = n17;
        objectArray[n12] = n10;
        objectArray[n15] = n10;
        objectArray[n16] = n17;
        objectArray[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"ZM", objectArray);
        Object[] objectArray2 = new Integer[n11];
        objectArray2[0] = n17;
        objectArray2[n12] = n17;
        objectArray2[n15] = n17;
        objectArray2[n16] = n17;
        objectArray2[n18] = n10;
        immutableListMultimap$Builder.putAll((Object)"ZW", objectArray2);
        return immutableListMultimap$Builder.build();
    }

    private long getInitialBitrateEstimateForNetworkType(int n10) {
        Serializable serializable = this.initialBitrateEstimates;
        Serializable serializable2 = Integer.valueOf(n10);
        if ((serializable2 = (Long)serializable.get(serializable2)) == null) {
            serializable2 = this.initialBitrateEstimates;
            serializable = Integer.valueOf(0);
            serializable2 = (Long)((ImmutableMap)serializable2).get(serializable);
        }
        if (serializable2 == null) {
            long l10 = 1000000L;
            serializable2 = Long.valueOf(l10);
        }
        return (Long)serializable2;
    }

    public static DefaultBandwidthMeter getSingletonInstance(Context object) {
        Class<DefaultBandwidthMeter> clazz = DefaultBandwidthMeter.class;
        synchronized (clazz) {
            Object object2 = singletonInstance;
            if (object2 == null) {
                object2 = new DefaultBandwidthMeter$Builder((Context)object);
                object = ((DefaultBandwidthMeter$Builder)object2).build();
                singletonInstance = object;
            }
            object = singletonInstance;
            return object;
        }
    }

    private static boolean isTransferAtFullNetworkSpeed(DataSpec dataSpec, boolean bl2) {
        boolean bl3;
        if (bl2 && !(bl3 = dataSpec.isFlagSet((int)((bl2 = 8) ? 1 : 0)))) {
            bl3 = true;
        } else {
            bl3 = false;
            dataSpec = null;
        }
        return bl3;
    }

    private void maybeNotifyBandwidthSample(int n10, long l10, long l11) {
        long l12;
        long l13;
        long l14;
        long l15;
        if (n10 == 0 && (l15 = (l14 = l10 - (l13 = 0L)) == 0L ? 0 : (l14 < 0L ? -1 : 1)) == false && (l15 = (l12 = l11 - (l13 = this.lastReportedBitrateEstimate)) == 0L ? 0 : (l12 < 0L ? -1 : 1)) == false) {
            return;
        }
        this.lastReportedBitrateEstimate = l11;
        this.eventDispatcher.bandwidthSample(n10, l10, l11);
    }

    /*
     * Enabled aggressive block sorting
     * Enabled unnecessary exception pruning
     * Enabled aggressive exception aggregation
     */
    private void onConnectivityAction() {
        synchronized (this) {
            Object object;
            int n10 = this.networkTypeOverrideSet;
            int n11 = 0;
            if (n10 != 0) {
                n10 = this.networkTypeOverride;
            } else {
                object = this.context;
                if (object == null) {
                    n10 = 0;
                    object = null;
                } else {
                    n10 = Util.getNetworkType((Context)object);
                }
            }
            int n12 = this.networkType;
            if (n12 == n10) {
                return;
            }
            this.networkType = n10;
            n12 = 1;
            if (n10 != n12 && n10 != 0 && n10 != (n12 = 8)) {
                long l10;
                long l11;
                this.bitrateEstimate = l11 = this.getInitialBitrateEstimateForNetworkType(n10);
                object = this.clock;
                l11 = object.elapsedRealtime();
                n10 = this.streamCount;
                if (n10 > 0) {
                    l10 = this.sampleStartTimeMs;
                    l10 = l11 - l10;
                    n11 = (int)l10;
                }
                long l12 = this.sampleBytesTransferred;
                long l13 = this.bitrateEstimate;
                this.maybeNotifyBandwidthSample(n11, l12, l13);
                this.sampleStartTimeMs = l11;
                this.sampleBytesTransferred = l10 = 0L;
                this.totalBytesTransferred = l10;
                this.totalElapsedTimeMs = l10;
                object = this.slidingPercentile;
                ((SlidingPercentile)object).reset();
                return;
            }
            return;
        }
    }

    public void addEventListener(Handler handler, BandwidthMeter$EventListener bandwidthMeter$EventListener) {
        Assertions.checkNotNull(handler);
        Assertions.checkNotNull(bandwidthMeter$EventListener);
        this.eventDispatcher.addListener(handler, bandwidthMeter$EventListener);
    }

    public long getBitrateEstimate() {
        synchronized (this) {
            long l10 = this.bitrateEstimate;
            return l10;
        }
    }

    public TransferListener getTransferListener() {
        return this;
    }

    public void onBytesTransferred(DataSource dataSource, DataSpec dataSpec, boolean bl2, int n10) {
        synchronized (this) {
            block5: {
                boolean bl3 = DefaultBandwidthMeter.isTransferAtFullNetworkSpeed(dataSpec, bl2);
                if (bl3) break block5;
                return;
            }
            long l10 = this.sampleBytesTransferred;
            long l11 = n10;
            l10 += l11;
            this.sampleBytesTransferred = l10;
            return;
        }
    }

    /*
     * WARNING - void declaration
     * Enabled aggressive block sorting
     * Enabled unnecessary exception pruning
     * Enabled aggressive exception aggregation
     */
    public void onTransferEnd(DataSource object, DataSpec dataSpec, boolean bl2) {
        synchronized (this) {
            float f10;
            void var3_3;
            void var2_2;
            int n10 = DefaultBandwidthMeter.isTransferAtFullNetworkSpeed((DataSpec)var2_2, (boolean)var3_3);
            if (n10 == 0) {
                return;
            }
            n10 = this.streamCount;
            int n11 = 1;
            float f11 = Float.MIN_VALUE;
            if (n10 > 0) {
                n10 = n11;
                f10 = f11;
            } else {
                n10 = 0;
                f10 = 0.0f;
                object = null;
            }
            Assertions.checkState(n10 != 0);
            object = this.clock;
            long l10 = object.elapsedRealtime();
            long l11 = this.sampleStartTimeMs;
            l11 = l10 - l11;
            int n12 = (int)l11;
            l11 = this.totalElapsedTimeMs;
            long l12 = n12;
            this.totalElapsedTimeMs = l11 += l12;
            l11 = this.totalBytesTransferred;
            l12 = this.sampleBytesTransferred;
            this.totalBytesTransferred = l11 += l12;
            if (n12 > 0) {
                long l13;
                f10 = l12;
                bl2 = 1174011904;
                f10 *= 8000.0f;
                float f12 = n12;
                SlidingPercentile slidingPercentile = this.slidingPercentile;
                double d10 = l12;
                d10 = Math.sqrt(d10);
                int n13 = (int)d10;
                slidingPercentile.addSample(n13, f10 /= f12);
                l11 = this.totalElapsedTimeMs;
                l12 = 2000L;
                n10 = (int)(l11 == l12 ? 0 : (l11 < l12 ? -1 : 1));
                if (n10 >= 0 || (n10 = (int)((l13 = (l11 = this.totalBytesTransferred) - (l12 = 524288L)) == 0L ? 0 : (l13 < 0L ? -1 : 1))) >= 0) {
                    object = this.slidingPercentile;
                    int n14 = 0x3F000000;
                    f12 = 0.5f;
                    f10 = ((SlidingPercentile)object).getPercentile(f12);
                    this.bitrateEstimate = l11 = (long)f10;
                }
                l12 = this.sampleBytesTransferred;
                long l14 = this.bitrateEstimate;
                this.maybeNotifyBandwidthSample(n12, l12, l14);
                this.sampleStartTimeMs = l10;
                this.sampleBytesTransferred = l10 = 0L;
            }
            this.streamCount = n10 = this.streamCount - n11;
            return;
        }
    }

    public void onTransferInitializing(DataSource dataSource, DataSpec dataSpec, boolean bl2) {
    }

    /*
     * WARNING - void declaration
     * Enabled aggressive block sorting
     * Enabled unnecessary exception pruning
     * Enabled aggressive exception aggregation
     */
    public void onTransferStart(DataSource object, DataSpec dataSpec, boolean bl2) {
        synchronized (this) {
            void var3_3;
            void var2_2;
            int n10 = DefaultBandwidthMeter.isTransferAtFullNetworkSpeed((DataSpec)var2_2, (boolean)var3_3);
            if (n10 == 0) {
                return;
            }
            n10 = this.streamCount;
            if (n10 == 0) {
                long l10;
                object = this.clock;
                this.sampleStartTimeMs = l10 = object.elapsedRealtime();
            }
            this.streamCount = n10 = this.streamCount + 1;
            return;
        }
    }

    public void removeEventListener(BandwidthMeter$EventListener bandwidthMeter$EventListener) {
        this.eventDispatcher.removeListener(bandwidthMeter$EventListener);
    }

    public void setNetworkTypeOverride(int n10) {
        synchronized (this) {
            this.networkTypeOverride = n10;
            n10 = 1;
            this.networkTypeOverrideSet = n10;
            this.onConnectivityAction();
            return;
        }
    }
}

