/*
 * Decompiled with CFR 0.151.
 * 
 * Could not load the following classes:
 *  android.content.Context
 *  android.text.TextUtils
 */
package com.mob.commons;

import android.content.Context;
import android.text.TextUtils;
import com.mob.MobSDK;
import com.mob.tools.proguard.EverythingKeeper;
import com.mob.tools.utils.SharePrefrenceHelper;

public final class InternationalDomain
extends Enum
implements EverythingKeeper {
    private static final /* synthetic */ InternationalDomain[] $VALUES;
    public static final /* enum */ InternationalDomain AD;
    public static final /* enum */ InternationalDomain AE;
    public static final /* enum */ InternationalDomain AF;
    public static final /* enum */ InternationalDomain AG;
    public static final /* enum */ InternationalDomain AI;
    public static final /* enum */ InternationalDomain AL;
    public static final /* enum */ InternationalDomain AM;
    public static final /* enum */ InternationalDomain AO;
    public static final /* enum */ InternationalDomain AR;
    public static final /* enum */ InternationalDomain AT;
    public static final /* enum */ InternationalDomain AU;
    public static final /* enum */ InternationalDomain AZ;
    public static final /* enum */ InternationalDomain BB;
    public static final /* enum */ InternationalDomain BD;
    public static final /* enum */ InternationalDomain BE;
    public static final /* enum */ InternationalDomain BF;
    public static final /* enum */ InternationalDomain BG;
    public static final /* enum */ InternationalDomain BH;
    public static final /* enum */ InternationalDomain BI;
    public static final /* enum */ InternationalDomain BJ;
    public static final /* enum */ InternationalDomain BL;
    public static final /* enum */ InternationalDomain BM;
    public static final /* enum */ InternationalDomain BN;
    public static final /* enum */ InternationalDomain BO;
    public static final /* enum */ InternationalDomain BR;
    public static final /* enum */ InternationalDomain BS;
    public static final /* enum */ InternationalDomain BW;
    public static final /* enum */ InternationalDomain BY;
    public static final /* enum */ InternationalDomain BZ;
    public static final /* enum */ InternationalDomain CA;
    public static final /* enum */ InternationalDomain CF;
    public static final /* enum */ InternationalDomain CG;
    public static final /* enum */ InternationalDomain CH;
    public static final /* enum */ InternationalDomain CK;
    public static final /* enum */ InternationalDomain CL;
    public static final /* enum */ InternationalDomain CM;
    public static final /* enum */ InternationalDomain CN;
    public static final /* enum */ InternationalDomain CO;
    public static final /* enum */ InternationalDomain CR;
    public static final /* enum */ InternationalDomain CS;
    public static final /* enum */ InternationalDomain CU;
    public static final /* enum */ InternationalDomain CY;
    public static final /* enum */ InternationalDomain CZ;
    public static final /* enum */ InternationalDomain DE;
    public static final /* enum */ InternationalDomain DEFAULT;
    public static final /* enum */ InternationalDomain DJ;
    public static final /* enum */ InternationalDomain DK;
    public static final /* enum */ InternationalDomain DO;
    public static final /* enum */ InternationalDomain DZ;
    public static final /* enum */ InternationalDomain EC;
    public static final /* enum */ InternationalDomain EE;
    public static final /* enum */ InternationalDomain EG;
    public static final /* enum */ InternationalDomain ES;
    public static final /* enum */ InternationalDomain ET;
    public static final /* enum */ InternationalDomain FI;
    public static final /* enum */ InternationalDomain FJ;
    public static final /* enum */ InternationalDomain FR;
    public static final /* enum */ InternationalDomain GA;
    public static final /* enum */ InternationalDomain GB;
    public static final /* enum */ InternationalDomain GD;
    public static final /* enum */ InternationalDomain GE;
    public static final /* enum */ InternationalDomain GF;
    public static final /* enum */ InternationalDomain GH;
    public static final /* enum */ InternationalDomain GI;
    public static final /* enum */ InternationalDomain GM;
    public static final /* enum */ InternationalDomain GN;
    public static final /* enum */ InternationalDomain GR;
    public static final /* enum */ InternationalDomain GT;
    public static final /* enum */ InternationalDomain GU;
    public static final /* enum */ InternationalDomain GY;
    public static final /* enum */ InternationalDomain HK;
    public static final /* enum */ InternationalDomain HN;
    public static final /* enum */ InternationalDomain HT;
    public static final /* enum */ InternationalDomain HU;
    public static final /* enum */ InternationalDomain ID;
    public static final /* enum */ InternationalDomain IE;
    public static final /* enum */ InternationalDomain IL;
    public static final /* enum */ InternationalDomain IN;
    public static final /* enum */ InternationalDomain IQ;
    public static final /* enum */ InternationalDomain IR;
    public static final /* enum */ InternationalDomain IS;
    public static final /* enum */ InternationalDomain IT;
    public static final /* enum */ InternationalDomain JM;
    public static final /* enum */ InternationalDomain JO;
    public static final /* enum */ InternationalDomain JP;
    public static final /* enum */ InternationalDomain KE;
    public static final /* enum */ InternationalDomain KG;
    public static final /* enum */ InternationalDomain KH;
    public static final /* enum */ InternationalDomain KP;
    public static final /* enum */ InternationalDomain KR;
    public static final /* enum */ InternationalDomain KT;
    public static final /* enum */ InternationalDomain KW;
    public static final /* enum */ InternationalDomain KZ;
    public static final /* enum */ InternationalDomain LA;
    public static final /* enum */ InternationalDomain LB;
    public static final /* enum */ InternationalDomain LC;
    public static final /* enum */ InternationalDomain LI;
    public static final /* enum */ InternationalDomain LK;
    public static final /* enum */ InternationalDomain LR;
    public static final /* enum */ InternationalDomain LS;
    public static final /* enum */ InternationalDomain LT;
    public static final /* enum */ InternationalDomain LU;
    public static final /* enum */ InternationalDomain LV;
    public static final /* enum */ InternationalDomain LY;
    public static final /* enum */ InternationalDomain MA;
    public static final /* enum */ InternationalDomain MC;
    public static final /* enum */ InternationalDomain MD;
    public static final /* enum */ InternationalDomain MG;
    public static final /* enum */ InternationalDomain ML;
    public static final /* enum */ InternationalDomain MM;
    public static final /* enum */ InternationalDomain MN;
    public static final /* enum */ InternationalDomain MO;
    public static final /* enum */ InternationalDomain MS;
    public static final /* enum */ InternationalDomain MT;
    public static final /* enum */ InternationalDomain MU;
    public static final /* enum */ InternationalDomain MV;
    public static final /* enum */ InternationalDomain MW;
    public static final /* enum */ InternationalDomain MX;
    public static final /* enum */ InternationalDomain MY;
    public static final /* enum */ InternationalDomain MZ;
    public static final /* enum */ InternationalDomain NA;
    public static final /* enum */ InternationalDomain NE;
    public static final /* enum */ InternationalDomain NG;
    public static final /* enum */ InternationalDomain NI;
    public static final /* enum */ InternationalDomain NL;
    public static final /* enum */ InternationalDomain NO;
    public static final /* enum */ InternationalDomain NP;
    public static final /* enum */ InternationalDomain NR;
    public static final /* enum */ InternationalDomain NZ;
    public static final /* enum */ InternationalDomain OM;
    public static final /* enum */ InternationalDomain PA;
    public static final /* enum */ InternationalDomain PE;
    public static final /* enum */ InternationalDomain PF;
    public static final /* enum */ InternationalDomain PG;
    public static final /* enum */ InternationalDomain PH;
    public static final /* enum */ InternationalDomain PK;
    public static final /* enum */ InternationalDomain PL;
    public static final /* enum */ InternationalDomain PR;
    public static final /* enum */ InternationalDomain PT;
    public static final /* enum */ InternationalDomain PY;
    public static final /* enum */ InternationalDomain QA;
    public static final /* enum */ InternationalDomain RO;
    public static final /* enum */ InternationalDomain RU;
    public static final /* enum */ InternationalDomain SA;
    public static final /* enum */ InternationalDomain SB;
    public static final /* enum */ InternationalDomain SC;
    public static final /* enum */ InternationalDomain SD;
    public static final /* enum */ InternationalDomain SE;
    public static final /* enum */ InternationalDomain SG;
    public static final /* enum */ InternationalDomain SI;
    public static final /* enum */ InternationalDomain SK;
    public static final /* enum */ InternationalDomain SL;
    public static final /* enum */ InternationalDomain SM;
    public static final /* enum */ InternationalDomain SN;
    public static final /* enum */ InternationalDomain SO;
    public static final /* enum */ InternationalDomain SR;
    public static final /* enum */ InternationalDomain ST;
    public static final /* enum */ InternationalDomain SV;
    public static final /* enum */ InternationalDomain SY;
    public static final /* enum */ InternationalDomain SZ;
    public static final /* enum */ InternationalDomain TD;
    public static final /* enum */ InternationalDomain TG;
    public static final /* enum */ InternationalDomain TH;
    public static final /* enum */ InternationalDomain TJ;
    public static final /* enum */ InternationalDomain TM;
    public static final /* enum */ InternationalDomain TN;
    public static final /* enum */ InternationalDomain TO;
    public static final /* enum */ InternationalDomain TR;
    public static final /* enum */ InternationalDomain TT;
    public static final /* enum */ InternationalDomain TW;
    public static final /* enum */ InternationalDomain TZ;
    public static final /* enum */ InternationalDomain UA;
    public static final /* enum */ InternationalDomain UG;
    public static final /* enum */ InternationalDomain US;
    public static final /* enum */ InternationalDomain UY;
    public static final /* enum */ InternationalDomain UZ;
    public static final /* enum */ InternationalDomain VC;
    public static final /* enum */ InternationalDomain VE;
    public static final /* enum */ InternationalDomain VN;
    public static final /* enum */ InternationalDomain YE;
    public static final /* enum */ InternationalDomain YU;
    public static final /* enum */ InternationalDomain ZA;
    public static final /* enum */ InternationalDomain ZM;
    public static final /* enum */ InternationalDomain ZR;
    public static final /* enum */ InternationalDomain ZW;
    private static SharePrefrenceHelper sp;
    private String domain;
    private String region;

    static {
        InternationalDomain internationalDomain;
        InternationalDomain[] internationalDomainArray = new InternationalDomain("AD", 0, "ad", "Andorra");
        AD = internationalDomainArray;
        int n10 = 1;
        internationalDomainArray = new InternationalDomain("AE", n10, "ae", "United Arab Emirates");
        AE = internationalDomainArray;
        int n11 = 2;
        internationalDomainArray = new InternationalDomain("AF", n11, "af", "Afghanistan");
        AF = internationalDomainArray;
        int n12 = 3;
        internationalDomainArray = new InternationalDomain("AG", n12, "ag", "Antigua and Barbuda");
        AG = internationalDomainArray;
        int n13 = 4;
        internationalDomainArray = new InternationalDomain("AI", n13, "ai", "Anguilla");
        AI = internationalDomainArray;
        int n14 = 5;
        internationalDomainArray = new InternationalDomain("AL", n14, "al", "Albania");
        AL = internationalDomainArray;
        int n15 = 6;
        internationalDomainArray = new InternationalDomain("AM", n15, "am", "Armenia");
        AM = internationalDomainArray;
        int n16 = 7;
        internationalDomainArray = new InternationalDomain("AO", n16, "ao", "Angola");
        AO = internationalDomainArray;
        int n17 = 8;
        internationalDomainArray = new InternationalDomain("AR", n17, "ar", "Argentina");
        AR = internationalDomainArray;
        int n18 = 9;
        internationalDomainArray = new InternationalDomain("AT", n18, "at", "Austria");
        AT = internationalDomainArray;
        int n19 = 10;
        internationalDomainArray = new InternationalDomain("AU", n19, "au", "Australia");
        AU = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("AZ", 11, "az", "Azerbaijan");
        AZ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BB", 12, "bb", "Barbados");
        BB = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BD", 13, "bd", "Bangladesh");
        BD = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BE", 14, "be", "Belgium");
        BE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BF", 15, "bf", "Burkina-faso");
        BF = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BG", 16, "bg", "Bulgaria");
        BG = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BH", 17, "bh", "Bahrain");
        BH = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BI", 18, "bi", "Burundi");
        BI = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BJ", 19, "bj", "Benin");
        BJ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BL", 20, "bl", "Palestine");
        BL = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BM", 21, "bm", "Bermuda Is.");
        BM = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BN", 22, "bn", "Brunei");
        BN = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BO", 23, "bo", "Bolivia");
        BO = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BR", 24, "br", "Brazil");
        BR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BS", 25, "bs", "Bahamas");
        BS = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BW", 26, "bw", "Botswana");
        BW = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BY", 27, "by", "Belarus");
        BY = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("BZ", 28, "bz", "Belize");
        BZ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CA", 29, "ca", "Canada");
        CA = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CF", 30, "cf", "Central African Republic");
        CF = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CG", 31, "cg", "Congo");
        CG = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CH", 32, "ch", "Switzerland");
        CH = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CK", 33, "ck", "Cook Is.");
        CK = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CL", 34, "cl", "Chile");
        CL = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CM", 35, "cm", "Cameroon");
        CM = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CN", 36, "cn", "China");
        CN = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CO", 37, "co", "Colombia");
        CO = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CR", 38, "cr", "Costa Rica");
        CR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CS", 39, "cs", "Czech");
        CS = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CU", 40, "cu", "Cuba");
        CU = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CY", 41, "cy", "Cyprus");
        CY = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("CZ", 42, "cz", "Czech Republic");
        CZ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("DE", 43, "de", "Germany");
        DE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("DJ", 44, "dj", "Djibouti");
        DJ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("DK", 45, "dk", "Denmark");
        DK = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("DO", 46, "do", "Dominica Rep.");
        DO = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("DZ", 47, "dz", "Algeria");
        DZ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("EC", 48, "ec", "Ecuador");
        EC = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("EE", 49, "ee", "Estonia");
        EE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("EG", 50, "eg", "Egypt");
        EG = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("ES", 51, "es", "Spain");
        ES = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("ET", 52, "et", "Ethiopia");
        ET = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("FI", 53, "fi", "Finland");
        FI = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("FJ", 54, "fj", "Fiji");
        FJ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("FR", 55, "fr", "France");
        FR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GA", 56, "ga", "Gabon");
        GA = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GB", 57, "gb", "United Kiongdom");
        GB = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GD", 58, "gd", "Grenada");
        GD = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GE", 59, "ge", "Georgia");
        GE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GF", 60, "gf", "French Guiana");
        GF = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GH", 61, "gh", "Ghana");
        GH = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GI", 62, "gi", "Gibraltar");
        GI = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GM", 63, "gm", "Gambia");
        GM = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GN", 64, "gn", "Guinea");
        GN = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GR", 65, "gr", "Greece");
        GR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GT", 66, "gt", "Guatemala");
        GT = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GU", 67, "gu", "Guam");
        GU = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("GY", 68, "gy", "Guyana");
        GY = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("HK", 69, "hk", "Hongkong");
        HK = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("HN", 70, "hn", "Honduras");
        HN = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("HT", 71, "ht", "Haiti");
        HT = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("HU", 72, "hu", "Hungary");
        HU = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("ID", 73, "id", "Indonesia");
        ID = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("IE", 74, "ie", "Ireland");
        IE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("IL", 75, "il", "Israel");
        IL = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("IN", 76, "in", "India");
        IN = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("IQ", 77, "iq", "Iraq");
        IQ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("IR", 78, "ir", "Iran");
        IR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("IS", 79, "is", "Iceland");
        IS = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("IT", 80, "it", "Italy");
        IT = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("JM", 81, "jm", "Jamaica");
        JM = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("JO", 82, "jo", "Jordan");
        JO = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("JP", 83, "jp", "Japan");
        JP = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("KE", 84, "ke", "Kenya");
        KE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("KG", 85, "kg", "Kyrgyzstan");
        KG = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("KH", 86, "kh", "Kampuchea (Cambodia )");
        KH = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("KP", 87, "kp", "North Korea");
        KP = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("KR", 88, "kr", "Korea");
        KR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("KT", 89, "kt", "Republic of Ivory Coast");
        KT = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("KW", 90, "kw", "Kuwait");
        KW = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("KZ", 91, "kz", "Kazakstan");
        KZ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LA", 92, "la", "Laos");
        LA = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LB", 93, "lb", "Lebanon");
        LB = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LC", 94, "lc", "St.Lucia");
        LC = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LI", 95, "li", "Liechtenstein");
        LI = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LK", 96, "lk", "Sri Lanka");
        LK = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LR", 97, "lr", "Liberia");
        LR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LS", 98, "ls", "Lesotho");
        LS = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LT", 99, "lt", "Lithuania");
        LT = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LU", 100, "lu", "Luxembourg");
        LU = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LV", 101, "lv", "Latvia");
        LV = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("LY", 102, "ly", "Libya");
        LY = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MA", 103, "ma", "Morocco");
        MA = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MC", 104, "mc", "Monaco");
        MC = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MD", 105, "md", "Moldova, Republic of");
        MD = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MG", 106, "mg", "Madagascar");
        MG = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("ML", 107, "ml", "Mali");
        ML = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MM", 108, "mm", "Burma");
        MM = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MN", 109, "mn", "Mongolia");
        MN = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MO", 110, "mo", "Macao");
        MO = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MS", 111, "ms", "Montserrat Is");
        MS = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MT", 112, "mt", "Malta");
        MT = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MU", 113, "mu", "Mauritius");
        MU = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MV", 114, "mv", "Maldives");
        MV = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MW", 115, "mw", "Malawi");
        MW = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MX", 116, "mx", "Mexico");
        MX = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MY", 117, "my", "Malaysia");
        MY = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("MZ", 118, "mz", "Mozambique");
        MZ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("NA", 119, "na", "Namibia");
        NA = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("NE", 120, "ne", "Niger");
        NE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("NG", 121, "ng", "Nigeria");
        NG = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("NI", 122, "ni", "Nicaragua");
        NI = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("NL", 123, "nl", "Netherlands");
        NL = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("NO", 124, "no", "Norway");
        NO = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("NP", 125, "np", "Nepal");
        NP = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("NR", 126, "nr", "Nauru");
        NR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("NZ", 127, "nz", "New Zealand");
        NZ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("OM", 128, "om", "Oman");
        OM = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("PA", 129, "pa", "Panama");
        PA = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("PE", 130, "pe", "Peru");
        PE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("PF", 131, "pf", "French Polynesia");
        PF = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("PG", 132, "pg", "Papua New Cuinea");
        PG = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("PH", 133, "ph", "Philippines");
        PH = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("PK", 134, "pk", "Pakistan");
        PK = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("PL", 135, "pl", "Poland");
        PL = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("PR", 136, "pr", "Puerto Rico");
        PR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("PT", 137, "pt", "Portugal");
        PT = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("PY", 138, "py", "Paraguay");
        PY = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("QA", 139, "qa", "Qatar");
        QA = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("RO", 140, "ro", "Romania");
        RO = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("RU", 141, "ru", "Russia");
        RU = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SA", 142, "sa", "Saudi Arabia");
        SA = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SB", 143, "sb", "Solomon Is");
        SB = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SC", 144, "sc", "Seychelles");
        SC = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SD", 145, "sd", "Sudan");
        SD = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SE", 146, "se", "Sweden");
        SE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SG", 147, "sg", "Singapore");
        SG = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SI", 148, "si", "Slovenia");
        SI = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SK", 149, "sk", "Slovakia");
        SK = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SL", 150, "sl", "Sierra Leone");
        SL = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SM", 151, "sm", "San Marino");
        SM = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SN", 152, "sn", "Senegal");
        SN = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SO", 153, "so", "Somali");
        SO = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SR", 154, "sr", "Suriname");
        SR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("ST", 155, "st", "Sao Tome and Principe");
        ST = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SV", 156, "sv", "EI Salvador");
        SV = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SY", 157, "sy", "Syria");
        SY = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("SZ", 158, "sz", "Swaziland");
        SZ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TD", 159, "td", "Chad");
        TD = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TG", 160, "tg", "Togo");
        TG = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TH", 161, "th", "Thailand");
        TH = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TJ", 162, "tj", "Tajikstan");
        TJ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TM", 163, "tm", "Turkmenistan");
        TM = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TN", 164, "tn", "Tunisia");
        TN = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TO", 165, "to", "Tonga");
        TO = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TR", 166, "tr", "Turkey");
        TR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TT", 167, "tt", "Trinidad and Tobago");
        TT = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TW", 168, "tw", "Taiwan");
        TW = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("TZ", 169, "tz", "Tanzania");
        TZ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("UA", 170, "ua", "Ukraine");
        UA = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("UG", 171, "ug", "Uganda");
        UG = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("US", 172, "us", "United States of America");
        US = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("UY", 173, "uy", "Uruguay");
        UY = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("UZ", 174, "uz", "Uzbekistan");
        UZ = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("VC", 175, "vc", "Saint Vincent");
        VC = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("VE", 176, "ve", "Venezuela");
        VE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("VN", 177, "vn", "Vietnam");
        VN = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("YE", 178, "ye", "Yemen");
        YE = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("YU", 179, "yu", "Yugoslavia");
        YU = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("ZA", 180, "za", "South Africa");
        ZA = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("ZM", 181, "zm", "Zambia");
        ZM = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("ZR", 182, "zr", "Zaire");
        ZR = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("ZW", 183, "zw", "Zimbabwe");
        ZW = internationalDomainArray;
        internationalDomainArray = new InternationalDomain("DEFAULT", 184, null, null);
        DEFAULT = internationalDomainArray;
        internationalDomainArray = new InternationalDomain[185];
        internationalDomainArray[0] = internationalDomain = AD;
        internationalDomainArray[n10] = internationalDomain = AE;
        internationalDomainArray[n11] = internationalDomain = AF;
        internationalDomainArray[n12] = internationalDomain = AG;
        internationalDomainArray[n13] = internationalDomain = AI;
        internationalDomainArray[n14] = internationalDomain = AL;
        internationalDomainArray[n15] = internationalDomain = AM;
        internationalDomainArray[n16] = internationalDomain = AO;
        internationalDomainArray[n17] = internationalDomain = AR;
        internationalDomainArray[n18] = internationalDomain = AT;
        internationalDomainArray[n19] = internationalDomain = AU;
        internationalDomainArray[11] = internationalDomain = AZ;
        internationalDomainArray[12] = internationalDomain = BB;
        internationalDomainArray[13] = internationalDomain = BD;
        internationalDomainArray[14] = internationalDomain = BE;
        internationalDomainArray[15] = internationalDomain = BF;
        internationalDomainArray[16] = internationalDomain = BG;
        internationalDomainArray[17] = internationalDomain = BH;
        internationalDomainArray[18] = internationalDomain = BI;
        internationalDomainArray[19] = internationalDomain = BJ;
        internationalDomainArray[20] = internationalDomain = BL;
        internationalDomainArray[21] = internationalDomain = BM;
        internationalDomainArray[22] = internationalDomain = BN;
        internationalDomainArray[23] = internationalDomain = BO;
        internationalDomainArray[24] = internationalDomain = BR;
        internationalDomainArray[25] = internationalDomain = BS;
        internationalDomainArray[26] = internationalDomain = BW;
        internationalDomainArray[27] = internationalDomain = BY;
        internationalDomainArray[28] = internationalDomain = BZ;
        internationalDomainArray[29] = internationalDomain = CA;
        internationalDomainArray[30] = internationalDomain = CF;
        internationalDomainArray[31] = internationalDomain = CG;
        internationalDomainArray[32] = internationalDomain = CH;
        internationalDomainArray[33] = internationalDomain = CK;
        internationalDomainArray[34] = internationalDomain = CL;
        internationalDomainArray[35] = internationalDomain = CM;
        internationalDomainArray[36] = internationalDomain = CN;
        internationalDomainArray[37] = internationalDomain = CO;
        internationalDomainArray[38] = internationalDomain = CR;
        internationalDomainArray[39] = internationalDomain = CS;
        internationalDomainArray[40] = internationalDomain = CU;
        internationalDomainArray[41] = internationalDomain = CY;
        internationalDomainArray[42] = internationalDomain = CZ;
        internationalDomainArray[43] = internationalDomain = DE;
        internationalDomainArray[44] = internationalDomain = DJ;
        internationalDomainArray[45] = internationalDomain = DK;
        internationalDomainArray[46] = internationalDomain = DO;
        internationalDomainArray[47] = internationalDomain = DZ;
        internationalDomainArray[48] = internationalDomain = EC;
        internationalDomainArray[49] = internationalDomain = EE;
        internationalDomainArray[50] = internationalDomain = EG;
        internationalDomainArray[51] = internationalDomain = ES;
        internationalDomainArray[52] = internationalDomain = ET;
        internationalDomainArray[53] = internationalDomain = FI;
        internationalDomainArray[54] = internationalDomain = FJ;
        internationalDomainArray[55] = internationalDomain = FR;
        internationalDomainArray[56] = internationalDomain = GA;
        internationalDomainArray[57] = internationalDomain = GB;
        internationalDomainArray[58] = internationalDomain = GD;
        internationalDomainArray[59] = internationalDomain = GE;
        internationalDomainArray[60] = internationalDomain = GF;
        internationalDomainArray[61] = internationalDomain = GH;
        internationalDomainArray[62] = internationalDomain = GI;
        internationalDomainArray[63] = internationalDomain = GM;
        internationalDomainArray[64] = internationalDomain = GN;
        internationalDomainArray[65] = internationalDomain = GR;
        internationalDomainArray[66] = internationalDomain = GT;
        internationalDomainArray[67] = internationalDomain = GU;
        internationalDomainArray[68] = internationalDomain = GY;
        internationalDomainArray[69] = internationalDomain = HK;
        internationalDomainArray[70] = internationalDomain = HN;
        internationalDomainArray[71] = internationalDomain = HT;
        internationalDomainArray[72] = internationalDomain = HU;
        internationalDomainArray[73] = internationalDomain = ID;
        internationalDomainArray[74] = internationalDomain = IE;
        internationalDomainArray[75] = internationalDomain = IL;
        internationalDomainArray[76] = internationalDomain = IN;
        internationalDomainArray[77] = internationalDomain = IQ;
        internationalDomainArray[78] = internationalDomain = IR;
        internationalDomainArray[79] = internationalDomain = IS;
        internationalDomainArray[80] = internationalDomain = IT;
        internationalDomainArray[81] = internationalDomain = JM;
        internationalDomainArray[82] = internationalDomain = JO;
        internationalDomainArray[83] = internationalDomain = JP;
        internationalDomainArray[84] = internationalDomain = KE;
        internationalDomainArray[85] = internationalDomain = KG;
        internationalDomainArray[86] = internationalDomain = KH;
        internationalDomainArray[87] = internationalDomain = KP;
        internationalDomainArray[88] = internationalDomain = KR;
        internationalDomainArray[89] = internationalDomain = KT;
        internationalDomainArray[90] = internationalDomain = KW;
        internationalDomainArray[91] = internationalDomain = KZ;
        internationalDomainArray[92] = internationalDomain = LA;
        internationalDomainArray[93] = internationalDomain = LB;
        internationalDomainArray[94] = internationalDomain = LC;
        internationalDomainArray[95] = internationalDomain = LI;
        internationalDomainArray[96] = internationalDomain = LK;
        internationalDomainArray[97] = internationalDomain = LR;
        internationalDomainArray[98] = internationalDomain = LS;
        internationalDomainArray[99] = internationalDomain = LT;
        internationalDomainArray[100] = internationalDomain = LU;
        internationalDomainArray[101] = internationalDomain = LV;
        internationalDomainArray[102] = internationalDomain = LY;
        internationalDomainArray[103] = internationalDomain = MA;
        internationalDomainArray[104] = internationalDomain = MC;
        internationalDomainArray[105] = internationalDomain = MD;
        internationalDomainArray[106] = internationalDomain = MG;
        internationalDomainArray[107] = internationalDomain = ML;
        internationalDomainArray[108] = internationalDomain = MM;
        internationalDomainArray[109] = internationalDomain = MN;
        internationalDomainArray[110] = internationalDomain = MO;
        internationalDomainArray[111] = internationalDomain = MS;
        internationalDomainArray[112] = internationalDomain = MT;
        internationalDomainArray[113] = internationalDomain = MU;
        internationalDomainArray[114] = internationalDomain = MV;
        internationalDomainArray[115] = internationalDomain = MW;
        internationalDomainArray[116] = internationalDomain = MX;
        internationalDomainArray[117] = internationalDomain = MY;
        internationalDomainArray[118] = internationalDomain = MZ;
        internationalDomainArray[119] = internationalDomain = NA;
        internationalDomainArray[120] = internationalDomain = NE;
        internationalDomainArray[121] = internationalDomain = NG;
        internationalDomainArray[122] = internationalDomain = NI;
        internationalDomainArray[123] = internationalDomain = NL;
        internationalDomainArray[124] = internationalDomain = NO;
        internationalDomainArray[125] = internationalDomain = NP;
        internationalDomainArray[126] = internationalDomain = NR;
        internationalDomainArray[127] = internationalDomain = NZ;
        internationalDomainArray[128] = internationalDomain = OM;
        internationalDomainArray[129] = internationalDomain = PA;
        internationalDomainArray[130] = internationalDomain = PE;
        internationalDomainArray[131] = internationalDomain = PF;
        internationalDomainArray[132] = internationalDomain = PG;
        internationalDomainArray[133] = internationalDomain = PH;
        internationalDomainArray[134] = internationalDomain = PK;
        internationalDomainArray[135] = internationalDomain = PL;
        internationalDomainArray[136] = internationalDomain = PR;
        internationalDomainArray[137] = internationalDomain = PT;
        internationalDomainArray[138] = internationalDomain = PY;
        internationalDomainArray[139] = internationalDomain = QA;
        internationalDomainArray[140] = internationalDomain = RO;
        internationalDomainArray[141] = internationalDomain = RU;
        internationalDomainArray[142] = internationalDomain = SA;
        internationalDomainArray[143] = internationalDomain = SB;
        internationalDomainArray[144] = internationalDomain = SC;
        internationalDomainArray[145] = internationalDomain = SD;
        internationalDomainArray[146] = internationalDomain = SE;
        internationalDomainArray[147] = internationalDomain = SG;
        internationalDomainArray[148] = internationalDomain = SI;
        internationalDomainArray[149] = internationalDomain = SK;
        internationalDomainArray[150] = internationalDomain = SL;
        internationalDomainArray[151] = internationalDomain = SM;
        internationalDomainArray[152] = internationalDomain = SN;
        internationalDomainArray[153] = internationalDomain = SO;
        internationalDomainArray[154] = internationalDomain = SR;
        internationalDomainArray[155] = internationalDomain = ST;
        internationalDomainArray[156] = internationalDomain = SV;
        internationalDomainArray[157] = internationalDomain = SY;
        internationalDomainArray[158] = internationalDomain = SZ;
        internationalDomainArray[159] = internationalDomain = TD;
        internationalDomainArray[160] = internationalDomain = TG;
        internationalDomainArray[161] = internationalDomain = TH;
        internationalDomainArray[162] = internationalDomain = TJ;
        internationalDomainArray[163] = internationalDomain = TM;
        internationalDomainArray[164] = internationalDomain = TN;
        internationalDomainArray[165] = internationalDomain = TO;
        internationalDomainArray[166] = internationalDomain = TR;
        internationalDomainArray[167] = internationalDomain = TT;
        internationalDomainArray[168] = internationalDomain = TW;
        internationalDomainArray[169] = internationalDomain = TZ;
        internationalDomainArray[170] = internationalDomain = UA;
        internationalDomainArray[171] = internationalDomain = UG;
        internationalDomainArray[172] = internationalDomain = US;
        internationalDomainArray[173] = internationalDomain = UY;
        internationalDomainArray[174] = internationalDomain = UZ;
        internationalDomainArray[175] = internationalDomain = VC;
        internationalDomainArray[176] = internationalDomain = VE;
        internationalDomainArray[177] = internationalDomain = VN;
        internationalDomainArray[178] = internationalDomain = YE;
        internationalDomainArray[179] = internationalDomain = YU;
        internationalDomainArray[180] = internationalDomain = ZA;
        internationalDomainArray[181] = internationalDomain = ZM;
        internationalDomainArray[182] = internationalDomain = ZR;
        internationalDomainArray[183] = internationalDomain = ZW;
        internationalDomainArray[184] = internationalDomain = DEFAULT;
        $VALUES = internationalDomainArray;
    }

    /*
     * WARNING - void declaration
     */
    private InternationalDomain() {
        void var4_2;
        void var3_1;
        void var2_-1;
        void var1_-1;
        this.domain = var3_1;
        this.region = var4_2;
    }

    public static InternationalDomain domainOf(String string2) {
        if (string2 == null) {
            return DEFAULT;
        }
        for (InternationalDomain internationalDomain : InternationalDomain.values()) {
            String string3 = internationalDomain.domain;
            boolean bl2 = string2.equalsIgnoreCase(string3);
            if (!bl2) continue;
            return internationalDomain;
        }
        return DEFAULT;
    }

    /*
     * Enabled aggressive block sorting
     * Enabled unnecessary exception pruning
     * Enabled aggressive exception aggregation
     */
    public static InternationalDomain readFromBuffer() {
        Class<InternationalDomain> clazz = InternationalDomain.class;
        synchronized (clazz) {
            Object object;
            Object object2 = sp;
            if (object2 == null) {
                object = MobSDK.getContext();
                object2 = new SharePrefrenceHelper((Context)object);
                sp = object2;
                object = "domain";
                int n10 = 1;
                ((SharePrefrenceHelper)object2).open((String)object, n10);
            }
            object2 = sp;
            object = "domain";
            boolean bl2 = TextUtils.isEmpty((CharSequence)(object2 = ((SharePrefrenceHelper)object2).getString((String)object)));
            if (bl2) {
                return null;
            }
            object = "null";
            bl2 = ((String)object).equalsIgnoreCase((String)object2);
            if (!bl2) return InternationalDomain.domainOf((String)object2);
            return DEFAULT;
        }
    }

    /*
     * Enabled aggressive block sorting
     * Enabled unnecessary exception pruning
     * Enabled aggressive exception aggregation
     */
    public static void saveBuffer(InternationalDomain object) {
        Class<InternationalDomain> clazz = InternationalDomain.class;
        synchronized (clazz) {
            Object object2 = sp;
            if (object2 == null) {
                Context context = MobSDK.getContext();
                sp = object2 = new SharePrefrenceHelper(context);
                String string2 = "domain";
                int n10 = 1;
                ((SharePrefrenceHelper)object2).open(string2, n10);
            }
            if (object == null) {
                object = sp;
                object2 = "domain";
                String string3 = "null";
                ((SharePrefrenceHelper)object).putString((String)object2, string3);
            } else {
                object2 = sp;
                String string4 = "domain";
                object = ((InternationalDomain)object).domain;
                ((SharePrefrenceHelper)object2).putString(string4, (String)object);
            }
            return;
        }
    }

    public static InternationalDomain valueOf(String string2) {
        return Enum.valueOf(InternationalDomain.class, string2);
    }

    public static InternationalDomain[] values() {
        return (InternationalDomain[])$VALUES.clone();
    }

    public String getDomain() {
        return this.domain;
    }

    public String getRegion() {
        return this.region;
    }
}

