/*
 * Decompiled with CFR 0.151.
 * 
 * Could not load the following classes:
 *  android.content.ContentResolver
 *  android.content.Context
 *  android.net.Uri
 */
package com.google.android.gms.measurement.internal;

import android.content.ContentResolver;
import android.content.Context;
import android.net.Uri;
import com.google.android.gms.internal.measurement.zzen;
import com.google.android.gms.internal.measurement.zzex;
import com.google.android.gms.measurement.internal.zzau;
import com.google.android.gms.measurement.internal.zzav;
import com.google.android.gms.measurement.internal.zzaw;
import com.google.android.gms.measurement.internal.zzax;
import com.google.android.gms.measurement.internal.zzay;
import com.google.android.gms.measurement.internal.zzaz;
import com.google.android.gms.measurement.internal.zzba;
import com.google.android.gms.measurement.internal.zzbb;
import com.google.android.gms.measurement.internal.zzbc;
import com.google.android.gms.measurement.internal.zzbd;
import com.google.android.gms.measurement.internal.zzbe;
import com.google.android.gms.measurement.internal.zzbf;
import com.google.android.gms.measurement.internal.zzbg;
import com.google.android.gms.measurement.internal.zzbh;
import com.google.android.gms.measurement.internal.zzbi;
import com.google.android.gms.measurement.internal.zzbj;
import com.google.android.gms.measurement.internal.zzbk;
import com.google.android.gms.measurement.internal.zzbl;
import com.google.android.gms.measurement.internal.zzbm;
import com.google.android.gms.measurement.internal.zzbn;
import com.google.android.gms.measurement.internal.zzbo;
import com.google.android.gms.measurement.internal.zzbp;
import com.google.android.gms.measurement.internal.zzbq;
import com.google.android.gms.measurement.internal.zzbr;
import com.google.android.gms.measurement.internal.zzbs;
import com.google.android.gms.measurement.internal.zzbt;
import com.google.android.gms.measurement.internal.zzbu;
import com.google.android.gms.measurement.internal.zzbv;
import com.google.android.gms.measurement.internal.zzbw;
import com.google.android.gms.measurement.internal.zzbx;
import com.google.android.gms.measurement.internal.zzby;
import com.google.android.gms.measurement.internal.zzbz;
import com.google.android.gms.measurement.internal.zzca;
import com.google.android.gms.measurement.internal.zzcb;
import com.google.android.gms.measurement.internal.zzcc;
import com.google.android.gms.measurement.internal.zzcd;
import com.google.android.gms.measurement.internal.zzce;
import com.google.android.gms.measurement.internal.zzcf;
import com.google.android.gms.measurement.internal.zzcg;
import com.google.android.gms.measurement.internal.zzch;
import com.google.android.gms.measurement.internal.zzci;
import com.google.android.gms.measurement.internal.zzcj;
import com.google.android.gms.measurement.internal.zzck;
import com.google.android.gms.measurement.internal.zzcl;
import com.google.android.gms.measurement.internal.zzcm;
import com.google.android.gms.measurement.internal.zzcn;
import com.google.android.gms.measurement.internal.zzco;
import com.google.android.gms.measurement.internal.zzcp;
import com.google.android.gms.measurement.internal.zzcq;
import com.google.android.gms.measurement.internal.zzcr;
import com.google.android.gms.measurement.internal.zzcs;
import com.google.android.gms.measurement.internal.zzct;
import com.google.android.gms.measurement.internal.zzcu;
import com.google.android.gms.measurement.internal.zzcv;
import com.google.android.gms.measurement.internal.zzcw;
import com.google.android.gms.measurement.internal.zzcx;
import com.google.android.gms.measurement.internal.zzcy;
import com.google.android.gms.measurement.internal.zzcz;
import com.google.android.gms.measurement.internal.zzda;
import com.google.android.gms.measurement.internal.zzdb;
import com.google.android.gms.measurement.internal.zzdc;
import com.google.android.gms.measurement.internal.zzdd;
import com.google.android.gms.measurement.internal.zzde;
import com.google.android.gms.measurement.internal.zzdf;
import com.google.android.gms.measurement.internal.zzdg;
import com.google.android.gms.measurement.internal.zzdh;
import com.google.android.gms.measurement.internal.zzdi;
import com.google.android.gms.measurement.internal.zzdj;
import com.google.android.gms.measurement.internal.zzdk;
import com.google.android.gms.measurement.internal.zzdl;
import com.google.android.gms.measurement.internal.zzdm;
import com.google.android.gms.measurement.internal.zzdn;
import com.google.android.gms.measurement.internal.zzdo;
import com.google.android.gms.measurement.internal.zzdp;
import com.google.android.gms.measurement.internal.zzdq;
import com.google.android.gms.measurement.internal.zzdr;
import com.google.android.gms.measurement.internal.zzdt;
import com.google.android.gms.measurement.internal.zzdv;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public final class zzdw {
    public static final zzdv zzA;
    public static final zzdv zzB;
    public static final zzdv zzC;
    public static final zzdv zzD;
    public static final zzdv zzE;
    public static final zzdv zzF;
    public static final zzdv zzG;
    public static final zzdv zzH;
    public static final zzdv zzI;
    public static final zzdv zzJ;
    public static final zzdv zzK;
    public static final zzdv zzL;
    public static final zzdv zzM;
    public static final zzdv zzN;
    public static final zzdv zzO;
    public static final zzdv zzP;
    public static final zzdv zzQ;
    public static final zzdv zzR;
    public static final zzdv zzS;
    public static final zzdv zzT;
    public static final zzdv zzU;
    public static final zzdv zzV;
    public static final zzdv zzW;
    public static final zzdv zzX;
    public static final zzdv zzY;
    public static final zzdv zzZ;
    public static final zzdv zza;
    public static final zzdv zzaA;
    public static final zzdv zzaB;
    private static final List zzaC;
    private static final Set zzaD;
    public static final zzdv zzaa;
    public static final zzdv zzab;
    public static final zzdv zzac;
    public static final zzdv zzad;
    public static final zzdv zzae;
    public static final zzdv zzaf;
    public static final zzdv zzag;
    public static final zzdv zzah;
    public static final zzdv zzai;
    public static final zzdv zzaj;
    public static final zzdv zzak;
    public static final zzdv zzal;
    public static final zzdv zzam;
    public static final zzdv zzan;
    public static final zzdv zzao;
    public static final zzdv zzap;
    public static final zzdv zzaq;
    public static final zzdv zzar;
    public static final zzdv zzas;
    public static final zzdv zzat;
    public static final zzdv zzau;
    public static final zzdv zzav;
    public static final zzdv zzaw;
    public static final zzdv zzax;
    public static final zzdv zzay;
    public static final zzdv zzaz;
    public static final zzdv zzb;
    public static final zzdv zzc;
    public static final zzdv zzd;
    public static final zzdv zze;
    public static final zzdv zzf;
    public static final zzdv zzg;
    public static final zzdv zzh;
    public static final zzdv zzi;
    public static final zzdv zzj;
    public static final zzdv zzk;
    public static final zzdv zzl;
    public static final zzdv zzm;
    public static final zzdv zzn;
    public static final zzdv zzo;
    public static final zzdv zzp;
    public static final zzdv zzq;
    public static final zzdv zzr;
    public static final zzdv zzs;
    public static final zzdv zzt;
    public static final zzdv zzu;
    public static final zzdv zzv;
    public static final zzdv zzw;
    public static final zzdv zzx;
    public static final zzdv zzy;
    public static final zzdv zzz;

    static {
        Object object = new ArrayList();
        zzaC = Collections.synchronizedList(object);
        object = new HashSet();
        zzaD = Collections.synchronizedSet(object);
        object = 10000L;
        Object object2 = com.google.android.gms.measurement.internal.zzau.zza;
        zza = zzdw.zzb("measurement.ad_id_cache_time", object, object, (zzdt)object2);
        object2 = 86400000L;
        Object object3 = zzbf.zza;
        zzb = zzdw.zzb("measurement.monitoring.sample_period_millis", object2, object2, (zzdt)object3);
        object3 = 3600000L;
        Object object4 = zzbq.zza;
        zzc = zzdw.zzb("measurement.config.cache_time", object2, object3, (zzdt)object4);
        object4 = zzcb.zza;
        Object object5 = "https";
        zzd = zzdw.zzb("measurement.config.url_scheme", object5, object5, (zzdt)object4);
        object4 = zzcm.zza;
        object5 = "app-measurement.com";
        zze = zzdw.zzb("measurement.config.url_authority", object5, object5, (zzdt)object4);
        object4 = 100;
        Object object6 = zzcx.zza;
        zzf = zzdw.zzb("measurement.upload.max_bundles", object4, object4, (zzdt)object6);
        object6 = 65536;
        object5 = zzdi.zza;
        zzg = zzdw.zzb("measurement.upload.max_batch_size", object6, object6, (zzdt)object5);
        object5 = zzdp.zza;
        zzh = zzdw.zzb("measurement.upload.max_bundle_size", object6, object6, (zzdt)object5);
        object6 = 1000;
        object5 = zzdq.zza;
        zzi = zzdw.zzb("measurement.upload.max_events_per_bundle", object6, object6, (zzdt)object5);
        object5 = 100000;
        Object object7 = zzdr.zza;
        zzj = zzdw.zzb("measurement.upload.max_events_per_day", object5, object5, (zzdt)object7);
        object7 = com.google.android.gms.measurement.internal.zzav.zza;
        zzk = zzdw.zzb("measurement.upload.max_error_events_per_day", object6, object6, (zzdt)object7);
        object6 = 50000;
        object7 = com.google.android.gms.measurement.internal.zzaw.zza;
        zzl = zzdw.zzb("measurement.upload.max_public_events_per_day", object6, object6, (zzdt)object7);
        object6 = 10000;
        object7 = com.google.android.gms.measurement.internal.zzax.zza;
        zzm = zzdw.zzb("measurement.upload.max_conversions_per_day", object6, object6, (zzdt)object7);
        object6 = 10;
        object7 = com.google.android.gms.measurement.internal.zzay.zza;
        zzn = zzdw.zzb("measurement.upload.max_realtime_events_per_day", object6, object6, (zzdt)object7);
        object6 = com.google.android.gms.measurement.internal.zzaz.zza;
        zzo = zzdw.zzb("measurement.store.max_stored_events_per_app", object5, object5, (zzdt)object6);
        object6 = zzba.zza;
        object7 = "https://app-measurement.com/a";
        zzp = zzdw.zzb("measurement.upload.url", object7, object7, (zzdt)object6);
        object6 = 43200000L;
        object5 = zzbb.zza;
        zzq = zzdw.zzb("measurement.upload.backoff_period", object6, object6, (zzdt)object5);
        object6 = zzbc.zza;
        zzr = zzdw.zzb("measurement.upload.window_interval", object3, object3, (zzdt)object6);
        object6 = zzbd.zza;
        zzs = zzdw.zzb("measurement.upload.interval", object3, object3, (zzdt)object6);
        object3 = zzbe.zza;
        zzt = zzdw.zzb("measurement.upload.realtime_upload_interval", object, object, (zzdt)object3);
        object = 1000L;
        object3 = zzbg.zza;
        zzu = zzdw.zzb("measurement.upload.debug_upload_interval", object, object, (zzdt)object3);
        object = 500L;
        object3 = zzbh.zza;
        zzv = zzdw.zzb("measurement.upload.minimum_delay", object, object, (zzdt)object3);
        object = 60000L;
        object3 = zzbi.zza;
        zzw = zzdw.zzb("measurement.alarm_manager.minimum_interval", object, object, (zzdt)object3);
        object = zzbj.zza;
        zzx = zzdw.zzb("measurement.upload.stale_data_deletion_interval", object2, object2, (zzdt)object);
        object = 604800000L;
        object2 = zzbk.zza;
        zzy = zzdw.zzb("measurement.upload.refresh_blacklisted_config_interval", object, object, (zzdt)object2);
        object2 = 15000L;
        object3 = zzbl.zza;
        zzz = zzdw.zzb("measurement.upload.initial_upload_delay_time", object2, object2, (zzdt)object3);
        object2 = 1800000L;
        object3 = zzbm.zza;
        zzA = zzdw.zzb("measurement.upload.retry_time", object2, object2, (zzdt)object3);
        object2 = 6;
        object3 = zzbn.zza;
        zzB = zzdw.zzb("measurement.upload.retry_count", object2, object2, (zzdt)object3);
        object2 = 2419200000L;
        object3 = zzbo.zza;
        zzC = zzdw.zzb("measurement.upload.max_queue_time", object2, object2, (zzdt)object3);
        object2 = 4;
        object3 = zzbp.zza;
        zzD = zzdw.zzb("measurement.lifetimevalue.max_currency_tracked", object2, object2, (zzdt)object3);
        object2 = 200;
        object3 = zzbr.zza;
        zzE = zzdw.zzb("measurement.audience.filter_result_max_count", object2, object2, (zzdt)object3);
        object2 = 25;
        zzF = zzdw.zzb("measurement.upload.max_public_user_properties", object2, object2, null);
        object3 = 500;
        zzG = zzdw.zzb("measurement.upload.max_event_name_cardinality", object3, object3, null);
        zzH = zzdw.zzb("measurement.upload.max_public_event_params", object2, object2, null);
        object2 = 5000L;
        object3 = zzbs.zza;
        zzI = zzdw.zzb("measurement.service_client.idle_disconnect_millis", object2, object2, (zzdt)object3);
        object2 = Boolean.FALSE;
        object3 = zzbt.zza;
        zzJ = zzdw.zzb("measurement.test.boolean_flag", object2, object2, (zzdt)object3);
        object3 = zzbu.zza;
        object7 = "---";
        zzK = zzdw.zzb("measurement.test.string_flag", object7, object7, (zzdt)object3);
        object3 = (long)-1;
        object5 = zzbv.zza;
        zzL = zzdw.zzb("measurement.test.long_flag", object3, object3, (zzdt)object5);
        object3 = -2;
        object5 = zzbw.zza;
        zzM = zzdw.zzb("measurement.test.int_flag", object3, object3, (zzdt)object5);
        object3 = -3.0;
        object5 = zzbx.zza;
        zzN = zzdw.zzb("measurement.test.double_flag", object3, object3, (zzdt)object5);
        object3 = 50;
        object5 = zzby.zza;
        zzO = zzdw.zzb("measurement.experiment.max_ids", object3, object3, (zzdt)object5);
        object3 = zzbz.zza;
        zzP = zzdw.zzb("measurement.max_bundles_per_iteration", object4, object4, (zzdt)object3);
        object3 = zzca.zza;
        zzQ = zzdw.zzb("measurement.sdk.attribution.cache.ttl", object, object, (zzdt)object3);
        object = zzcc.zza;
        zzR = zzdw.zzb("measurement.validation.internal_limits_internal_event_params", object2, object2, (zzdt)object);
        object = Boolean.TRUE;
        object3 = zzcd.zza;
        zzS = zzdw.zzb("measurement.collection.firebase_global_collection_flag_enabled", object, object, (zzdt)object3);
        object3 = zzce.zza;
        zzT = zzdw.zzb("measurement.collection.redundant_engagement_removal_enabled", object2, object2, (zzdt)object3);
        object3 = zzcf.zza;
        zzU = zzdw.zzb("measurement.collection.log_event_and_bundle_v2", object, object, (zzdt)object3);
        zzV = zzdw.zzb("measurement.quality.checksum", object2, object2, null);
        object3 = zzcg.zza;
        zzW = zzdw.zzb("measurement.sdk.dynamite.allow_remote_dynamite3", object, object, (zzdt)object3);
        object3 = zzch.zza;
        zzX = zzdw.zzb("measurement.sdk.collection.validate_param_names_alphabetical", object, object, (zzdt)object3);
        object3 = zzci.zza;
        zzY = zzdw.zzb("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", object2, object2, (zzdt)object3);
        object3 = zzcj.zza;
        zzZ = zzdw.zzb("measurement.audience.refresh_event_count_filters_timestamp", object2, object2, (zzdt)object3);
        object3 = zzck.zza;
        zzaa = zzdw.zzb("measurement.audience.use_bundle_timestamp_for_event_count_filters", object2, object2, (zzdt)object3);
        object3 = zzcl.zza;
        zzab = zzdw.zzb("measurement.sdk.collection.retrieve_deeplink_from_bow_2", object, object, (zzdt)object3);
        object3 = zzcn.zza;
        zzac = zzdw.zzb("measurement.sdk.collection.last_deep_link_referrer2", object, object, (zzdt)object3);
        object3 = zzco.zza;
        zzad = zzdw.zzb("measurement.sdk.collection.last_deep_link_referrer_campaign2", object2, object2, (zzdt)object3);
        object3 = zzcp.zza;
        zzae = zzdw.zzb("measurement.sdk.collection.last_gclid_from_referrer2", object2, object2, (zzdt)object3);
        object3 = zzcq.zza;
        zzaf = zzdw.zzb("measurement.sdk.collection.enable_extend_user_property_size", object, object, (zzdt)object3);
        object3 = zzcr.zza;
        zzag = zzdw.zzb("measurement.upload.file_lock_state_check", object2, object2, (zzdt)object3);
        object3 = zzcs.zza;
        zzah = zzdw.zzb("measurement.ga.ga_app_id", object2, object2, (zzdt)object3);
        object3 = zzct.zza;
        zzai = zzdw.zzb("measurement.lifecycle.app_in_background_parameter", object2, object2, (zzdt)object3);
        object3 = zzcu.zza;
        zzaj = zzdw.zzb("measurement.integration.disable_firebase_instance_id", object2, object2, (zzdt)object3);
        object3 = zzcv.zza;
        zzak = zzdw.zzb("measurement.lifecycle.app_backgrounded_engagement", object2, object2, (zzdt)object3);
        object3 = zzcw.zza;
        zzal = zzdw.zzb("measurement.collection.service.update_with_analytics_fix", object2, object2, (zzdt)object3);
        object3 = zzcy.zza;
        zzam = zzdw.zzb("measurement.service.use_appinfo_modified", object2, object2, (zzdt)object3);
        object3 = zzcz.zza;
        zzan = zzdw.zzb("measurement.client.firebase_feature_rollout.v1.enable", object, object, (zzdt)object3);
        object3 = zzda.zza;
        zzao = zzdw.zzb("measurement.client.sessions.check_on_reset_and_enable2", object, object, (zzdt)object3);
        object3 = zzdb.zza;
        zzap = zzdw.zzb("measurement.scheduler.task_thread.cleanup_on_exit", object2, object2, (zzdt)object3);
        object3 = zzdc.zza;
        zzaq = zzdw.zzb("measurement.upload.file_truncate_fix", object2, object2, (zzdt)object3);
        object3 = zzdd.zza;
        zzar = zzdw.zzb("measurement.sdk.referrer.delayed_install_referrer_api", object2, object2, (zzdt)object3);
        object3 = zzde.zza;
        zzas = zzdw.zzb("measurement.sdk.screen.disabling_automatic_reporting", object, object, (zzdt)object3);
        object3 = zzdf.zza;
        zzat = zzdw.zzb("measurement.sdk.screen.manual_screen_view_logging", object, object, (zzdt)object3);
        object3 = zzdg.zza;
        zzau = zzdw.zzb("measurement.collection.synthetic_data_mitigation", object2, object2, (zzdt)object3);
        object3 = zzdh.zza;
        zzav = zzdw.zzb("measurement.androidId.delete_feature", object, object, (zzdt)object3);
        object3 = zzdj.zza;
        zzaw = zzdw.zzb("measurement.client.consent_state_v1", object, object, (zzdt)object3);
        object3 = zzdk.zza;
        zzax = zzdw.zzb("measurement.client.3p_consent_state_v1", object, object, (zzdt)object3);
        object3 = zzdl.zza;
        zzay = zzdw.zzb("measurement.service.consent_state_v1_W36", object, object, (zzdt)object3);
        object3 = 203590;
        object4 = zzdm.zza;
        zzaz = zzdw.zzb("measurement.service.storage_consent_support_version", object3, object3, (zzdt)object4);
        object3 = zzdn.zza;
        zzaA = zzdw.zzb("measurement.service.directly_maybe_log_error_events", object2, object2, (zzdt)object3);
        object2 = zzdo.zza;
        zzaB = zzdw.zzb("measurement.client.safer_resources", object, object, (zzdt)object2);
    }

    public static Map zza(Context object) {
        object = object.getContentResolver();
        Uri uri = zzex.zza("com.google.android.gms.measurement");
        object = (object = zzen.zza((ContentResolver)object, uri)) == null ? Collections.emptyMap() : object.zzb();
        return object;
    }

    public static zzdv zzb(String string2, Object object, Object object2, zzdt zzdt2) {
        zzdv zzdv2 = new zzdv(string2, object, object2, zzdt2, null);
        zzaC.add(zzdv2);
        return zzdv2;
    }

    public static /* synthetic */ List zzc() {
        return zzaC;
    }
}

