/*
 * Decompiled with CFR 0.151.
 */
package androidx.vectordrawable.graphics.drawable;

public class AndroidResources {
    public static final int FAST_OUT_LINEAR_IN = 17563663;
    public static final int FAST_OUT_SLOW_IN = 17563661;
    public static final int LINEAR_OUT_SLOW_IN = 17563662;
    public static final int[] STYLEABLE_ANIMATED_VECTOR_DRAWABLE;
    public static final int STYLEABLE_ANIMATED_VECTOR_DRAWABLE_DRAWABLE = 0;
    public static final int[] STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET;
    public static final int STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET_ANIMATION = 1;
    public static final int STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET_NAME = 0;
    public static final int[] STYLEABLE_ANIMATOR;
    public static final int STYLEABLE_ANIMATOR_DURATION = 1;
    public static final int STYLEABLE_ANIMATOR_INTERPOLATOR = 0;
    public static final int STYLEABLE_ANIMATOR_REPEAT_COUNT = 3;
    public static final int STYLEABLE_ANIMATOR_REPEAT_MODE = 4;
    public static final int[] STYLEABLE_ANIMATOR_SET;
    public static final int STYLEABLE_ANIMATOR_SET_ORDERING = 0;
    public static final int STYLEABLE_ANIMATOR_START_OFFSET = 2;
    public static final int STYLEABLE_ANIMATOR_VALUE_FROM = 5;
    public static final int STYLEABLE_ANIMATOR_VALUE_TO = 6;
    public static final int STYLEABLE_ANIMATOR_VALUE_TYPE = 7;
    public static final int[] STYLEABLE_KEYFRAME;
    public static final int STYLEABLE_KEYFRAME_FRACTION = 3;
    public static final int STYLEABLE_KEYFRAME_INTERPOLATOR = 1;
    public static final int STYLEABLE_KEYFRAME_VALUE = 0;
    public static final int STYLEABLE_KEYFRAME_VALUE_TYPE = 2;
    public static final int[] STYLEABLE_PATH_INTERPOLATOR;
    public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_X_1 = 0;
    public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_X_2 = 2;
    public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_Y_1 = 1;
    public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_Y_2 = 3;
    public static final int STYLEABLE_PATH_INTERPOLATOR_PATH_DATA = 4;
    public static final int[] STYLEABLE_PROPERTY_ANIMATOR;
    public static final int STYLEABLE_PROPERTY_ANIMATOR_PATH_DATA = 1;
    public static final int STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_NAME = 0;
    public static final int STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_X_NAME = 2;
    public static final int STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_Y_NAME = 3;
    public static final int[] STYLEABLE_PROPERTY_VALUES_HOLDER;
    public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_PROPERTY_NAME = 3;
    public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_FROM = 0;
    public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_TO = 1;
    public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_TYPE = 2;
    public static final int STYLEABLE_VECTOR_DRAWABLE_ALPHA = 4;
    public static final int STYLEABLE_VECTOR_DRAWABLE_AUTO_MIRRORED = 5;
    public static final int[] STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH;
    public static final int STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_FILLTYPE = 2;
    public static final int STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_NAME = 0;
    public static final int STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_PATH_DATA = 1;
    public static final int[] STYLEABLE_VECTOR_DRAWABLE_GROUP;
    public static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_NAME = 0;
    public static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_X = 1;
    public static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_Y = 2;
    public static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_ROTATION = 5;
    public static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_X = 3;
    public static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_Y = 4;
    public static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_X = 6;
    public static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_Y = 7;
    public static final int STYLEABLE_VECTOR_DRAWABLE_HEIGHT = 2;
    public static final int STYLEABLE_VECTOR_DRAWABLE_NAME = 0;
    public static final int[] STYLEABLE_VECTOR_DRAWABLE_PATH;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_FILL_ALPHA = 12;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_FILL_COLOR = 1;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_NAME = 0;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_PATH_DATA = 2;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_ALPHA = 11;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_COLOR = 3;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_CAP = 8;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_JOIN = 9;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_MITER_LIMIT = 10;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_WIDTH = 4;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_END = 6;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_FILLTYPE = 13;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_OFFSET = 7;
    public static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_START = 5;
    public static final int STYLEABLE_VECTOR_DRAWABLE_TINT = 1;
    public static final int STYLEABLE_VECTOR_DRAWABLE_TINT_MODE = 6;
    public static final int[] STYLEABLE_VECTOR_DRAWABLE_TYPE_ARRAY;
    public static final int STYLEABLE_VECTOR_DRAWABLE_VIEWPORT_HEIGHT = 8;
    public static final int STYLEABLE_VECTOR_DRAWABLE_VIEWPORT_WIDTH = 7;
    public static final int STYLEABLE_VECTOR_DRAWABLE_WIDTH = 3;

    static {
        int[] nArray;
        int[] nArray2;
        int[] nArray3 = nArray2 = new int[9];
        int[] nArray4 = nArray2;
        nArray3[0] = 0x1010003;
        nArray4[1] = 0x1010121;
        nArray3[2] = 0x1010155;
        nArray4[3] = 16843097;
        nArray3[4] = 16843551;
        nArray4[5] = 16843754;
        nArray3[6] = 16843771;
        nArray4[7] = 16843778;
        nArray4[8] = 16843779;
        STYLEABLE_VECTOR_DRAWABLE_TYPE_ARRAY = nArray2;
        int n10 = 8;
        int[] nArray5 = nArray = new int[n10];
        int[] nArray6 = nArray;
        nArray5[0] = 0x1010003;
        nArray6[1] = 16843189;
        nArray5[2] = 16843190;
        nArray6[3] = 16843556;
        nArray5[4] = 16843557;
        nArray6[5] = 16843558;
        nArray5[6] = 16843866;
        nArray6[7] = 16843867;
        STYLEABLE_VECTOR_DRAWABLE_GROUP = nArray;
        int[] nArray7 = nArray = new int[14];
        int[] nArray8 = nArray;
        nArray7[0] = 0x1010003;
        nArray8[1] = 0x1010404;
        nArray7[2] = 16843781;
        nArray8[3] = 16843782;
        nArray7[4] = 16843783;
        nArray8[5] = 16843784;
        nArray7[6] = 16843785;
        nArray8[7] = 16843786;
        nArray7[8] = 16843787;
        nArray8[9] = 16843788;
        nArray7[10] = 16843789;
        nArray8[11] = 16843979;
        nArray7[12] = 16843980;
        nArray8[13] = 16844062;
        STYLEABLE_VECTOR_DRAWABLE_PATH = nArray;
        int[] nArray9 = nArray = new int[3];
        nArray[0] = 0x1010003;
        nArray9[1] = 16843781;
        nArray9[2] = 16844062;
        STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH = nArray;
        int n11 = 1;
        int[] nArray10 = new int[n11];
        nArray10[0] = 0x1010199;
        STYLEABLE_ANIMATED_VECTOR_DRAWABLE = nArray10;
        nArray10 = new int[]{0x1010003, 16843213};
        STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET = nArray10;
        int[] nArray11 = nArray2 = new int[n10];
        int[] nArray12 = nArray2;
        nArray11[0] = 0x1010141;
        nArray12[1] = 16843160;
        nArray11[2] = 16843198;
        nArray12[3] = 16843199;
        nArray11[4] = 0x10101C0;
        nArray12[5] = 16843486;
        nArray11[6] = 16843487;
        nArray12[7] = 16843488;
        STYLEABLE_ANIMATOR = nArray2;
        nArray2 = new int[n11];
        nArray2[0] = 16843490;
        STYLEABLE_ANIMATOR_SET = nArray2;
        n10 = 4;
        int[] nArray13 = nArray = new int[n10];
        int[] nArray14 = nArray;
        nArray13[0] = 16843486;
        nArray14[1] = 16843487;
        nArray13[2] = 16843488;
        nArray14[3] = 16843489;
        STYLEABLE_PROPERTY_VALUES_HOLDER = nArray;
        int[] nArray15 = nArray = new int[n10];
        int[] nArray16 = nArray;
        nArray15[0] = 16842788;
        nArray16[1] = 0x1010141;
        nArray15[2] = 16843488;
        nArray16[3] = 16843992;
        STYLEABLE_KEYFRAME = nArray;
        int[] nArray17 = nArray2 = new int[n10];
        int[] nArray18 = nArray2;
        nArray17[0] = 16843489;
        nArray18[1] = 16843781;
        nArray17[2] = 16843892;
        nArray18[3] = 16843893;
        STYLEABLE_PROPERTY_ANIMATOR = nArray2;
        int[] nArray19 = nArray2 = new int[5];
        int[] nArray20 = nArray2;
        nArray19[0] = 16843772;
        nArray20[1] = 16843773;
        nArray19[2] = 16843774;
        nArray20[3] = 16843775;
        nArray20[4] = 16843781;
        STYLEABLE_PATH_INTERPOLATOR = nArray2;
    }

    private AndroidResources() {
    }
}

