/*
 * Decompiled with CFR 0.151.
 */
package androidx.appcompat.resources;

public final class R$styleable {
    public static final int[] AnimatedStateListDrawableCompat;
    public static final int AnimatedStateListDrawableCompat_android_constantSize = 3;
    public static final int AnimatedStateListDrawableCompat_android_dither = 0;
    public static final int AnimatedStateListDrawableCompat_android_enterFadeDuration = 4;
    public static final int AnimatedStateListDrawableCompat_android_exitFadeDuration = 5;
    public static final int AnimatedStateListDrawableCompat_android_variablePadding = 2;
    public static final int AnimatedStateListDrawableCompat_android_visible = 1;
    public static final int[] AnimatedStateListDrawableItem;
    public static final int AnimatedStateListDrawableItem_android_drawable = 1;
    public static final int AnimatedStateListDrawableItem_android_id = 0;
    public static final int[] AnimatedStateListDrawableTransition;
    public static final int AnimatedStateListDrawableTransition_android_drawable = 0;
    public static final int AnimatedStateListDrawableTransition_android_fromId = 2;
    public static final int AnimatedStateListDrawableTransition_android_reversible = 3;
    public static final int AnimatedStateListDrawableTransition_android_toId = 1;
    public static final int[] ColorStateListItem;
    public static final int ColorStateListItem_alpha = 2;
    public static final int ColorStateListItem_android_alpha = 1;
    public static final int ColorStateListItem_android_color = 0;
    public static final int[] FontFamily;
    public static final int[] FontFamilyFont;
    public static final int FontFamilyFont_android_font = 0;
    public static final int FontFamilyFont_android_fontStyle = 2;
    public static final int FontFamilyFont_android_fontVariationSettings = 4;
    public static final int FontFamilyFont_android_fontWeight = 1;
    public static final int FontFamilyFont_android_ttcIndex = 3;
    public static final int FontFamilyFont_font = 5;
    public static final int FontFamilyFont_fontStyle = 6;
    public static final int FontFamilyFont_fontVariationSettings = 7;
    public static final int FontFamilyFont_fontWeight = 8;
    public static final int FontFamilyFont_ttcIndex = 9;
    public static final int FontFamily_fontProviderAuthority = 0;
    public static final int FontFamily_fontProviderCerts = 1;
    public static final int FontFamily_fontProviderFetchStrategy = 2;
    public static final int FontFamily_fontProviderFetchTimeout = 3;
    public static final int FontFamily_fontProviderPackage = 4;
    public static final int FontFamily_fontProviderQuery = 5;
    public static final int FontFamily_fontProviderSystemFontFamily = 6;
    public static final int[] GradientColor;
    public static final int[] GradientColorItem;
    public static final int GradientColorItem_android_color = 0;
    public static final int GradientColorItem_android_offset = 1;
    public static final int GradientColor_android_centerColor = 7;
    public static final int GradientColor_android_centerX = 3;
    public static final int GradientColor_android_centerY = 4;
    public static final int GradientColor_android_endColor = 1;
    public static final int GradientColor_android_endX = 10;
    public static final int GradientColor_android_endY = 11;
    public static final int GradientColor_android_gradientRadius = 5;
    public static final int GradientColor_android_startColor = 0;
    public static final int GradientColor_android_startX = 8;
    public static final int GradientColor_android_startY = 9;
    public static final int GradientColor_android_tileMode = 6;
    public static final int GradientColor_android_type = 2;
    public static final int[] StateListDrawable;
    public static final int[] StateListDrawableItem;
    public static final int StateListDrawableItem_android_drawable = 0;
    public static final int StateListDrawable_android_constantSize = 3;
    public static final int StateListDrawable_android_dither = 0;
    public static final int StateListDrawable_android_enterFadeDuration = 4;
    public static final int StateListDrawable_android_exitFadeDuration = 5;
    public static final int StateListDrawable_android_variablePadding = 2;
    public static final int StateListDrawable_android_visible = 1;

    static {
        int[] nArray;
        int[] nArray2;
        int n10 = 6;
        int[] nArray3 = nArray2 = new int[n10];
        int[] nArray4 = nArray2;
        nArray3[0] = 0x101011C;
        nArray4[1] = 16843156;
        nArray3[2] = 16843157;
        nArray4[3] = 16843158;
        nArray3[4] = 16843532;
        nArray4[5] = 16843533;
        AnimatedStateListDrawableCompat = nArray2;
        int n11 = 2;
        int[] nArray5 = new int[n11];
        nArray5[0] = 0x10100D0;
        nArray5[1] = 0x1010199;
        AnimatedStateListDrawableItem = nArray5;
        int[] nArray6 = nArray5 = new int[4];
        int[] nArray7 = nArray5;
        nArray6[0] = 0x1010199;
        nArray7[1] = 16843849;
        nArray6[2] = 16843850;
        nArray7[3] = 16843851;
        AnimatedStateListDrawableTransition = nArray5;
        int[] nArray8 = nArray5 = new int[3];
        nArray5[0] = 16843173;
        nArray8[1] = 16843551;
        nArray8[2] = 2130968620;
        ColorStateListItem = nArray5;
        int[] nArray9 = nArray5 = new int[7];
        int[] nArray10 = nArray5;
        nArray9[0] = 2130968925;
        nArray10[1] = 2130968926;
        nArray9[2] = 2130968927;
        nArray10[3] = 2130968928;
        nArray9[4] = 2130968929;
        nArray10[5] = 2130968930;
        nArray10[6] = 2130968931;
        FontFamily = nArray5;
        int[] nArray11 = nArray5 = new int[10];
        int[] nArray12 = nArray5;
        nArray11[0] = 16844082;
        nArray12[1] = 16844083;
        nArray11[2] = 16844095;
        nArray12[3] = 16844143;
        nArray11[4] = 16844144;
        nArray12[5] = 2130968923;
        nArray11[6] = 2130968932;
        nArray12[7] = 2130968933;
        nArray11[8] = 2130968934;
        nArray12[9] = 2130969474;
        FontFamilyFont = nArray5;
        int[] nArray13 = nArray5 = new int[12];
        int[] nArray14 = nArray5;
        nArray13[0] = 16843165;
        nArray14[1] = 16843166;
        nArray13[2] = 0x10101A1;
        nArray14[3] = 16843170;
        nArray13[4] = 16843171;
        nArray14[5] = 16843172;
        nArray13[6] = 0x1010201;
        nArray14[7] = 16843275;
        nArray13[8] = 0x1010510;
        nArray14[9] = 0x1010511;
        nArray13[10] = 16844050;
        nArray14[11] = 16844051;
        GradientColor = nArray5;
        nArray2 = new int[n11];
        nArray2[0] = 16843173;
        nArray2[1] = 16844052;
        GradientColorItem = nArray2;
        int[] nArray15 = nArray = new int[n10];
        int[] nArray16 = nArray;
        nArray15[0] = 0x101011C;
        nArray16[1] = 16843156;
        nArray15[2] = 16843157;
        nArray16[3] = 16843158;
        nArray15[4] = 16843532;
        nArray16[5] = 16843533;
        StateListDrawable = nArray;
        nArray = new int[]{0x1010199};
        StateListDrawableItem = nArray;
    }

    private R$styleable() {
    }
}

