/*
 * Decompiled with CFR 0.151.
 */
package com.google.android.gms.internal.mlkit_common;

import com.google.android.gms.internal.mlkit_common.zzbi;
import com.google.android.gms.internal.mlkit_common.zzbj;
import com.google.android.gms.internal.mlkit_common.zzfu;
import com.google.android.gms.internal.mlkit_common.zzfv;
import com.google.android.gms.internal.mlkit_common.zzfx;

public final class zzbg
extends Enum
implements zzfv {
    public static final /* enum */ zzbg zza;
    private static final /* enum */ zzbg zzaa;
    private static final /* enum */ zzbg zzab;
    private static final /* enum */ zzbg zzac;
    private static final /* enum */ zzbg zzad;
    private static final /* enum */ zzbg zzae;
    private static final /* enum */ zzbg zzaf;
    private static final /* enum */ zzbg zzag;
    private static final /* enum */ zzbg zzah;
    private static final /* enum */ zzbg zzai;
    private static final /* enum */ zzbg zzaj;
    private static final /* enum */ zzbg zzak;
    private static final /* enum */ zzbg zzal;
    private static final /* enum */ zzbg zzam;
    private static final /* enum */ zzbg zzan;
    private static final /* enum */ zzbg zzao;
    private static final /* enum */ zzbg zzap;
    private static final /* enum */ zzbg zzaq;
    private static final /* enum */ zzbg zzar;
    private static final /* enum */ zzbg zzas;
    private static final /* enum */ zzbg zzat;
    private static final /* enum */ zzbg zzau;
    private static final /* enum */ zzbg zzav;
    private static final /* enum */ zzbg zzaw;
    private static final /* enum */ zzbg zzax;
    private static final /* enum */ zzbg zzay;
    private static final /* enum */ zzbg zzaz;
    public static final /* enum */ zzbg zzb;
    private static final /* enum */ zzbg zzba;
    private static final /* enum */ zzbg zzbb;
    private static final /* enum */ zzbg zzbc;
    private static final /* enum */ zzbg zzbd;
    private static final /* enum */ zzbg zzbe;
    private static final /* enum */ zzbg zzbf;
    private static final /* enum */ zzbg zzbg;
    private static final /* enum */ zzbg zzbh;
    private static final /* enum */ zzbg zzbi;
    private static final /* enum */ zzbg zzbj;
    private static final /* enum */ zzbg zzbk;
    private static final /* enum */ zzbg zzbl;
    private static final /* enum */ zzbg zzbm;
    private static final /* enum */ zzbg zzbn;
    private static final /* enum */ zzbg zzbo;
    private static final /* enum */ zzbg zzbp;
    private static final /* enum */ zzbg zzbq;
    private static final /* enum */ zzbg zzbr;
    private static final /* enum */ zzbg zzbs;
    private static final /* enum */ zzbg zzbt;
    private static final /* enum */ zzbg zzbu;
    private static final /* enum */ zzbg zzbv;
    private static final /* enum */ zzbg zzbw;
    private static final /* enum */ zzbg zzbx;
    private static final /* enum */ zzbg zzby;
    private static final /* enum */ zzbg zzbz;
    private static final /* enum */ zzbg zzc;
    private static final /* enum */ zzbg zzca;
    private static final /* enum */ zzbg zzcb;
    private static final /* enum */ zzbg zzcc;
    private static final /* enum */ zzbg zzcd;
    private static final /* enum */ zzbg zzce;
    private static final /* enum */ zzbg zzcf;
    private static final /* enum */ zzbg zzcg;
    private static final /* enum */ zzbg zzch;
    private static final /* enum */ zzbg zzci;
    private static final /* enum */ zzbg zzcj;
    private static final /* enum */ zzbg zzck;
    private static final /* enum */ zzbg zzcl;
    private static final /* enum */ zzbg zzcm;
    private static final /* enum */ zzbg zzcn;
    private static final /* enum */ zzbg zzco;
    private static final /* enum */ zzbg zzcp;
    private static final /* enum */ zzbg zzcq;
    private static final /* enum */ zzbg zzcr;
    private static final /* enum */ zzbg zzcs;
    private static final /* enum */ zzbg zzct;
    private static final /* enum */ zzbg zzcu;
    private static final /* enum */ zzbg zzcv;
    private static final /* enum */ zzbg zzcw;
    private static final /* enum */ zzbg zzcx;
    private static final /* enum */ zzbg zzcy;
    private static final /* enum */ zzbg zzcz;
    private static final /* enum */ zzbg zzd;
    private static final /* enum */ zzbg zzda;
    private static final /* enum */ zzbg zzdb;
    private static final /* enum */ zzbg zzdc;
    private static final /* enum */ zzbg zzdd;
    private static final /* enum */ zzbg zzde;
    private static final /* enum */ zzbg zzdf;
    private static final /* enum */ zzbg zzdg;
    private static final /* enum */ zzbg zzdh;
    private static final /* enum */ zzbg zzdi;
    private static final /* enum */ zzbg zzdj;
    private static final /* enum */ zzbg zzdk;
    private static final /* enum */ zzbg zzdl;
    private static final /* enum */ zzbg zzdm;
    private static final /* enum */ zzbg zzdn;
    private static final /* enum */ zzbg zzdo;
    private static final /* enum */ zzbg zzdp;
    private static final /* enum */ zzbg zzdq;
    private static final zzfu zzdr;
    private static final /* synthetic */ zzbg[] zzdt;
    private static final /* enum */ zzbg zze;
    private static final /* enum */ zzbg zzf;
    private static final /* enum */ zzbg zzg;
    private static final /* enum */ zzbg zzh;
    private static final /* enum */ zzbg zzi;
    private static final /* enum */ zzbg zzj;
    private static final /* enum */ zzbg zzk;
    private static final /* enum */ zzbg zzl;
    private static final /* enum */ zzbg zzm;
    private static final /* enum */ zzbg zzn;
    private static final /* enum */ zzbg zzo;
    private static final /* enum */ zzbg zzp;
    private static final /* enum */ zzbg zzq;
    private static final /* enum */ zzbg zzr;
    private static final /* enum */ zzbg zzs;
    private static final /* enum */ zzbg zzt;
    private static final /* enum */ zzbg zzu;
    private static final /* enum */ zzbg zzv;
    private static final /* enum */ zzbg zzw;
    private static final /* enum */ zzbg zzx;
    private static final /* enum */ zzbg zzy;
    private static final /* enum */ zzbg zzz;
    private final int zzds;

    static {
        zzbg zzbg2;
        Object object = new zzbg("UNKNOWN_EVENT", 0, 0);
        zzc = object;
        int n10 = 1;
        object = new zzbg("ON_DEVICE_FACE_DETECT", n10, n10);
        zzd = object;
        int n11 = 2;
        object = new zzbg("ON_DEVICE_FACE_CREATE", n11, n11);
        zze = object;
        int n12 = 3;
        object = new zzbg("ON_DEVICE_FACE_CLOSE", n12, n12);
        zzf = object;
        int n13 = 11;
        object = new zzbg("ON_DEVICE_TEXT_DETECT", 4, n13);
        zzg = object;
        int n14 = 12;
        object = new zzbg("ON_DEVICE_TEXT_CREATE", 5, n14);
        zzh = object;
        int n15 = 13;
        object = new zzbg("ON_DEVICE_TEXT_CLOSE", 6, n15);
        zzi = object;
        int n16 = 21;
        object = new zzbg("ON_DEVICE_BARCODE_DETECT", 7, n16);
        zzj = object;
        int n17 = 22;
        object = new zzbg("ON_DEVICE_BARCODE_CREATE", 8, n17);
        zzk = object;
        int n18 = 23;
        object = new zzbg("ON_DEVICE_BARCODE_CLOSE", 9, n18);
        zzl = object;
        object = new zzbg("ON_DEVICE_IMAGE_LABEL_DETECT", 10, 141);
        zzm = object;
        object = new zzbg("ON_DEVICE_IMAGE_LABEL_CREATE", n13, 142);
        zzn = object;
        object = new zzbg("ON_DEVICE_IMAGE_LABEL_CLOSE", n14, 143);
        zzo = object;
        object = new zzbg("ON_DEVICE_IMAGE_LABEL_LOAD", n15, 144);
        zzp = object;
        object = new zzbg("ON_DEVICE_SMART_REPLY_DETECT", 14, 151);
        zzq = object;
        object = new zzbg("ON_DEVICE_SMART_REPLY_CREATE", 15, 152);
        zzr = object;
        object = new zzbg("ON_DEVICE_SMART_REPLY_CLOSE", 16, 153);
        zzs = object;
        object = new zzbg("ON_DEVICE_SMART_REPLY_BLACKLIST_UPDATE", 17, 154);
        zzt = object;
        object = new zzbg("ON_DEVICE_LANGUAGE_IDENTIFICATION_DETECT", 18, 161);
        zzu = object;
        object = new zzbg("ON_DEVICE_LANGUAGE_IDENTIFICATION_CREATE", 19, 162);
        zzv = object;
        object = new zzbg("ON_DEVICE_LANGUAGE_IDENTIFICATION_LOAD", 20, 164);
        zzw = object;
        object = new zzbg("ON_DEVICE_LANGUAGE_IDENTIFICATION_CLOSE", n16, 163);
        zzx = object;
        object = new zzbg("ON_DEVICE_TRANSLATOR_TRANSLATE", n17, 171);
        zzy = object;
        object = new zzbg("ON_DEVICE_TRANSLATOR_CREATE", n18, 172);
        zzz = object;
        object = new zzbg("ON_DEVICE_TRANSLATOR_LOAD", 24, 173);
        zzaa = object;
        object = new zzbg("ON_DEVICE_TRANSLATOR_CLOSE", 25, 174);
        zzab = object;
        object = new zzbg("ON_DEVICE_TRANSLATOR_DOWNLOAD", 26, 175);
        zzac = object;
        object = new zzbg("ON_DEVICE_ENTITY_EXTRACTION_ANNOTATE", 27, 241);
        zzad = object;
        object = new zzbg("ON_DEVICE_ENTITY_EXTRACTION_CREATE", 28, 242);
        zzae = object;
        object = new zzbg("ON_DEVICE_ENTITY_EXTRACTION_LOAD", 29, 243);
        zzaf = object;
        object = new zzbg("ON_DEVICE_ENTITY_EXTRACTION_CLOSE", 30, 244);
        zzag = object;
        int n19 = 31;
        object = new zzbg("ON_DEVICE_ENTITY_EXTRACTION_DOWNLOAD", n19, 245);
        zzah = object;
        int n20 = 32;
        object = new zzbg("ON_DEVICE_OBJECT_CREATE", n20, 191);
        zzai = object;
        int n21 = 33;
        object = new zzbg("ON_DEVICE_OBJECT_LOAD", n21, 192);
        zzaj = object;
        object = new zzbg("ON_DEVICE_OBJECT_INFERENCE", 34, 193);
        zzak = object;
        object = new zzbg("ON_DEVICE_OBJECT_CLOSE", 35, 194);
        zzal = object;
        object = new zzbg("ON_DEVICE_DI_CREATE", 36, 311);
        zzam = object;
        object = new zzbg("ON_DEVICE_DI_LOAD", 37, 312);
        zzan = object;
        object = new zzbg("ON_DEVICE_DI_DOWNLOAD", 38, 313);
        zzao = object;
        object = new zzbg("ON_DEVICE_DI_RECOGNIZE", 39, 314);
        zzap = object;
        object = new zzbg("ON_DEVICE_DI_CLOSE", 40, 315);
        zzaq = object;
        n18 = 41;
        object = new zzbg("ON_DEVICE_POSE_CREATE", n18, 321);
        zzar = object;
        int n22 = 42;
        object = new zzbg("ON_DEVICE_POSE_LOAD", n22, 322);
        zzas = object;
        n17 = 43;
        object = new zzbg("ON_DEVICE_POSE_INFERENCE", n17, 323);
        zzat = object;
        object = new zzbg("ON_DEVICE_POSE_CLOSE", 44, 324);
        zzau = object;
        object = new zzbg("ON_DEVICE_SEGMENTATION_CREATE", 45, 331);
        zzav = object;
        object = new zzbg("ON_DEVICE_SEGMENTATION_LOAD", 46, 332);
        zzaw = object;
        object = new zzbg("ON_DEVICE_SEGMENTATION_INFERENCE", 47, 333);
        zzax = object;
        object = new zzbg("ON_DEVICE_SEGMENTATION_CLOSE", 48, 334);
        zzay = object;
        object = new zzbg("CUSTOM_OBJECT_CREATE", 49, 341);
        zzaz = object;
        object = new zzbg("CUSTOM_OBJECT_LOAD", 50, 342);
        zzba = object;
        n15 = 51;
        object = new zzbg("CUSTOM_OBJECT_INFERENCE", n15, 343);
        zzbb = object;
        n16 = 52;
        object = new zzbg("CUSTOM_OBJECT_CLOSE", n16, 344);
        zzbc = object;
        n14 = 53;
        object = new zzbg("CUSTOM_IMAGE_LABEL_CREATE", n14, 351);
        zzbd = object;
        object = new zzbg("CUSTOM_IMAGE_LABEL_LOAD", 54, 352);
        zzbe = object;
        object = new zzbg("CUSTOM_IMAGE_LABEL_DETECT", 55, 353);
        zzbf = object;
        object = new zzbg("CUSTOM_IMAGE_LABEL_CLOSE", 56, 354);
        zzbg = object;
        object = new zzbg("CLOUD_FACE_DETECT", 57, n19);
        zzbh = object;
        object = new zzbg("CLOUD_FACE_CREATE", 58, n20);
        zzbi = object;
        object = new zzbg("CLOUD_FACE_CLOSE", 59, n21);
        zzbj = object;
        object = new zzbg("CLOUD_CROP_HINTS_CREATE", 60, n18);
        zzbk = object;
        n12 = 61;
        object = new zzbg("CLOUD_CROP_HINTS_DETECT", n12, n22);
        zzbl = object;
        n13 = 62;
        object = new zzbg("CLOUD_CROP_HINTS_CLOSE", n13, n17);
        zzbm = object;
        n17 = 63;
        object = new zzbg("CLOUD_DOCUMENT_TEXT_CREATE", n17, n15);
        zzbn = object;
        object = new zzbg("CLOUD_DOCUMENT_TEXT_DETECT", 64, n16);
        zzbo = object;
        object = new zzbg("CLOUD_DOCUMENT_TEXT_CLOSE", 65, n14);
        zzbp = object;
        object = new zzbg("CLOUD_IMAGE_PROPERTIES_CREATE", 66, n12);
        zzbq = object;
        object = new zzbg("CLOUD_IMAGE_PROPERTIES_DETECT", 67, n13);
        zzbr = object;
        object = new zzbg("CLOUD_IMAGE_PROPERTIES_CLOSE", 68, n17);
        zzbs = object;
        object = new zzbg("CLOUD_IMAGE_LABEL_CREATE", 69, 71);
        zzbt = object;
        object = new zzbg("CLOUD_IMAGE_LABEL_DETECT", 70, 72);
        zzbu = object;
        object = new zzbg("CLOUD_IMAGE_LABEL_CLOSE", 71, 73);
        zzbv = object;
        object = new zzbg("CLOUD_LANDMARK_CREATE", 72, 81);
        zzbw = object;
        object = new zzbg("CLOUD_LANDMARK_DETECT", 73, 82);
        zzbx = object;
        object = new zzbg("CLOUD_LANDMARK_CLOSE", 74, 83);
        zzby = object;
        object = new zzbg("CLOUD_LOGO_CREATE", 75, 91);
        zzbz = object;
        object = new zzbg("CLOUD_LOGO_DETECT", 76, 92);
        zzca = object;
        object = new zzbg("CLOUD_LOGO_CLOSE", 77, 93);
        zzcb = object;
        object = new zzbg("CLOUD_SAFE_SEARCH_CREATE", 78, 111);
        zzcc = object;
        object = new zzbg("CLOUD_SAFE_SEARCH_DETECT", 79, 112);
        zzcd = object;
        object = new zzbg("CLOUD_SAFE_SEARCH_CLOSE", 80, 113);
        zzce = object;
        object = new zzbg("CLOUD_TEXT_CREATE", 81, 121);
        zzcf = object;
        object = new zzbg("CLOUD_TEXT_DETECT", 82, 122);
        zzcg = object;
        object = new zzbg("CLOUD_TEXT_CLOSE", 83, 123);
        zzch = object;
        object = new zzbg("CLOUD_WEB_SEARCH_CREATE", 84, 131);
        zzci = object;
        object = new zzbg("CLOUD_WEB_SEARCH_DETECT", 85, 132);
        zzcj = object;
        object = new zzbg("CLOUD_WEB_SEARCH_CLOSE", 86, 133);
        zzck = object;
        object = new zzbg("CUSTOM_MODEL_RUN", 87, 102);
        zzcl = object;
        object = new zzbg("CUSTOM_MODEL_CREATE", 88, 103);
        zzcm = object;
        object = new zzbg("CUSTOM_MODEL_CLOSE", 89, 104);
        zzcn = object;
        object = new zzbg("CUSTOM_MODEL_LOAD", 90, 105);
        zzco = object;
        object = new zzbg("AUTOML_IMAGE_LABELING_RUN", 91, 181);
        zzcp = object;
        object = new zzbg("AUTOML_IMAGE_LABELING_CREATE", 92, 182);
        zzcq = object;
        object = new zzbg("AUTOML_IMAGE_LABELING_CLOSE", 93, 183);
        zzcr = object;
        object = new zzbg("AUTOML_IMAGE_LABELING_LOAD", 94, 184);
        zzcs = object;
        object = new zzbg("MODEL_DOWNLOAD", 95, 100);
        zza = object;
        object = new zzbg("MODEL_UPDATE", 96, 101);
        zzct = object;
        object = new zzbg("REMOTE_MODEL_IS_DOWNLOADED", 97, 251);
        zzcu = object;
        object = new zzbg("REMOTE_MODEL_DELETE_ON_DEVICE", 98, 252);
        zzcv = object;
        object = new zzbg("ACCELERATION_ANALYTICS", 99, 260);
        zzcw = object;
        object = new zzbg("AGGREGATED_AUTO_ML_IMAGE_LABELING_INFERENCE", 100, 200);
        zzcx = object;
        object = new zzbg("AGGREGATED_CUSTOM_MODEL_INFERENCE", 101, 201);
        zzcy = object;
        object = new zzbg("AGGREGATED_ON_DEVICE_BARCODE_DETECTION", 102, 202);
        zzcz = object;
        object = new zzbg("AGGREGATED_ON_DEVICE_FACE_DETECTION", 103, 203);
        zzda = object;
        object = new zzbg("AGGREGATED_ON_DEVICE_IMAGE_LABEL_DETECTION", 104, 204);
        zzdb = object;
        object = new zzbg("AGGREGATED_ON_DEVICE_OBJECT_INFERENCE", 105, 205);
        zzdc = object;
        object = new zzbg("AGGREGATED_ON_DEVICE_TEXT_DETECTION", 106, 206);
        zzdd = object;
        object = new zzbg("AGGREGATED_ON_DEVICE_POSE_DETECTION", 107, 207);
        zzde = object;
        object = new zzbg("AGGREGATED_ON_DEVICE_SEGMENTATION", 108, 208);
        zzdf = object;
        object = new zzbg("AGGREGATED_CUSTOM_OBJECT_INFERENCE", 109, 209);
        zzdg = object;
        object = new zzbg("AGGREGATED_CUSTOM_IMAGE_LABEL_DETECTION", 110, 210);
        zzdh = object;
        object = new zzbg("REMOTE_CONFIG_FETCH", 111, 271);
        zzdi = object;
        object = new zzbg("REMOTE_CONFIG_ACTIVATE", 112, 272);
        zzdj = object;
        object = new zzbg("REMOTE_CONFIG_FRC_FETCH", 113, 281);
        zzdk = object;
        object = new zzbg("INSTALLATION_ID_INIT", 114, 291);
        zzdl = object;
        object = new zzbg("INSTALLATION_ID_REGISTER_NEW_ID", 115, 292);
        zzdm = object;
        object = new zzbg("INSTALLATION_ID_REFRESH_TEMPORARY_TOKEN", 116, 293);
        zzdn = object;
        object = new zzbg("INSTALLATION_ID_FIS_CREATE_INSTALLATION", 117, 301);
        zzdo = object;
        object = new zzbg("INSTALLATION_ID_FIS_GENERATE_AUTH_TOKEN", 118, 302);
        zzdp = object;
        object = new zzbg("INPUT_IMAGE_CONSTRUCTION", 119, 361);
        zzdq = object;
        object = new zzbg("HANDLE_LEAKED", 120, 371);
        zzb = object;
        object = new zzbg[121];
        object[0] = zzbg2 = zzc;
        object[n10] = zzbg2 = zzd;
        object[n11] = zzbg2 = zze;
        object[3] = zzbg2 = zzf;
        object[4] = zzbg2 = zzg;
        object[5] = zzbg2 = zzh;
        object[6] = zzbg2 = zzi;
        object[7] = zzbg2 = zzj;
        object[8] = zzbg2 = zzk;
        object[9] = zzbg2 = zzl;
        object[10] = zzbg2 = zzm;
        object[11] = zzbg2 = zzn;
        object[12] = zzbg2 = zzo;
        object[13] = zzbg2 = zzp;
        object[14] = zzbg2 = zzq;
        object[15] = zzbg2 = zzr;
        object[16] = zzbg2 = zzs;
        object[17] = zzbg2 = zzt;
        object[18] = zzbg2 = zzu;
        object[19] = zzbg2 = zzv;
        object[20] = zzbg2 = zzw;
        object[21] = zzbg2 = zzx;
        object[22] = zzbg2 = zzy;
        object[23] = zzbg2 = zzz;
        object[24] = zzbg2 = zzaa;
        object[25] = zzbg2 = zzab;
        object[26] = zzbg2 = zzac;
        object[27] = zzbg2 = zzad;
        object[28] = zzbg2 = zzae;
        object[29] = zzbg2 = zzaf;
        object[30] = zzbg2 = zzag;
        object[n19] = zzbg2 = zzah;
        object[n20] = zzbg2 = zzai;
        object[n21] = zzbg2 = zzaj;
        object[34] = zzbg2 = zzak;
        object[35] = zzbg2 = zzal;
        object[36] = zzbg2 = zzam;
        object[37] = zzbg2 = zzan;
        object[38] = zzbg2 = zzao;
        object[39] = zzbg2 = zzap;
        object[40] = zzbg2 = zzaq;
        object[n18] = zzbg2 = zzar;
        object[n22] = zzbg2 = zzas;
        object[43] = zzbg2 = zzat;
        object[44] = zzbg2 = zzau;
        object[45] = zzbg2 = zzav;
        object[46] = zzbg2 = zzaw;
        object[47] = zzbg2 = zzax;
        object[48] = zzbg2 = zzay;
        object[49] = zzbg2 = zzaz;
        object[50] = zzbg2 = zzba;
        object[51] = zzbg2 = zzbb;
        object[n16] = zzbg2 = zzbc;
        object[n14] = zzbg2 = zzbd;
        object[54] = zzbg2 = zzbe;
        object[55] = zzbg2 = zzbf;
        object[56] = zzbg2 = zzbg;
        object[57] = zzbg2 = zzbh;
        object[58] = zzbg2 = zzbi;
        object[59] = zzbg2 = zzbj;
        object[60] = zzbg2 = zzbk;
        object[n12] = zzbg2 = zzbl;
        object[n13] = zzbg2 = zzbm;
        object[63] = zzbg2 = zzbn;
        object[64] = zzbg2 = zzbo;
        object[65] = zzbg2 = zzbp;
        object[66] = zzbg2 = zzbq;
        object[67] = zzbg2 = zzbr;
        object[68] = zzbg2 = zzbs;
        object[69] = zzbg2 = zzbt;
        object[70] = zzbg2 = zzbu;
        object[71] = zzbg2 = zzbv;
        object[72] = zzbg2 = zzbw;
        object[73] = zzbg2 = zzbx;
        object[74] = zzbg2 = zzby;
        object[75] = zzbg2 = zzbz;
        object[76] = zzbg2 = zzca;
        object[77] = zzbg2 = zzcb;
        object[78] = zzbg2 = zzcc;
        object[79] = zzbg2 = zzcd;
        object[80] = zzbg2 = zzce;
        object[81] = zzbg2 = zzcf;
        object[82] = zzbg2 = zzcg;
        object[83] = zzbg2 = zzch;
        object[84] = zzbg2 = zzci;
        object[85] = zzbg2 = zzcj;
        object[86] = zzbg2 = zzck;
        object[87] = zzbg2 = zzcl;
        object[88] = zzbg2 = zzcm;
        object[89] = zzbg2 = zzcn;
        object[90] = zzbg2 = zzco;
        object[91] = zzbg2 = zzcp;
        object[92] = zzbg2 = zzcq;
        object[93] = zzbg2 = zzcr;
        object[94] = zzbg2 = zzcs;
        object[95] = zzbg2 = zza;
        object[96] = zzbg2 = zzct;
        object[97] = zzbg2 = zzcu;
        object[98] = zzbg2 = zzcv;
        object[99] = zzbg2 = zzcw;
        object[100] = zzbg2 = zzcx;
        object[101] = zzbg2 = zzcy;
        object[102] = zzbg2 = zzcz;
        object[103] = zzbg2 = zzda;
        object[104] = zzbg2 = zzdb;
        object[105] = zzbg2 = zzdc;
        object[106] = zzbg2 = zzdd;
        object[107] = zzbg2 = zzde;
        object[108] = zzbg2 = zzdf;
        object[109] = zzbg2 = zzdg;
        object[110] = zzbg2 = zzdh;
        object[111] = zzbg2 = zzdi;
        object[112] = zzbg2 = zzdj;
        object[113] = zzbg2 = zzdk;
        object[114] = zzbg2 = zzdl;
        object[115] = zzbg2 = zzdm;
        object[116] = zzbg2 = zzdn;
        object[117] = zzbg2 = zzdo;
        object[118] = zzbg2 = zzdp;
        object[119] = zzbg2 = zzdq;
        object[120] = zzbg2 = zzb;
        zzdt = object;
        zzdr = object = new zzbj();
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private zzbg() {
        void var3_1;
        void var2_-1;
        void var1_-1;
        this.zzds = var3_1;
    }

    public static zzbg[] values() {
        return (zzbg[])zzdt.clone();
    }

    public static zzfx zzb() {
        return com.google.android.gms.internal.mlkit_common.zzbi.zza;
    }

    public final String toString() {
        StringBuilder stringBuilder = new StringBuilder("<");
        String string2 = zzbg.class.getName();
        stringBuilder.append(string2);
        stringBuilder.append('@');
        string2 = Integer.toHexString(System.identityHashCode(this));
        stringBuilder.append(string2);
        stringBuilder.append(" number=");
        int n10 = this.zzds;
        stringBuilder.append(n10);
        stringBuilder.append(" name=");
        string2 = this.name();
        stringBuilder.append(string2);
        stringBuilder.append('>');
        return stringBuilder.toString();
    }

    public final int zza() {
        return this.zzds;
    }
}

