/*
 * Decompiled with CFR 0.151.
 */
package com.zhiyun.protocol.constants;

import d.v.y.d.h;

public interface InteractCode {
    public static final int CALIBRATION_QUICK = 0;
    public static final int CALIBRATION_QUICK_PARAM_START = 21930;
    public static final int CALIBRATION_QUICK_PARAM_STOP = 42405;
    public static final int CAMERA_ZOOM = 0;
    public static final int DEMO_MODE_R = 0;
    public static final int DEMO_MODE_W = 0;
    public static final int DEVICE_CATEGORY_R = 0;
    public static final int Debug_R = 0;
    public static final int Debug_W = 0;
    public static final int FF_HIGH_16BIT = 0;
    public static final int FF_LOW_16BIT = 0;
    public static final int FF_VIRTUAL_POS = 0;
    public static final int FOCUS_CONTROL = 0;
    public static final int FUNCTION_EVENT = 0;
    public static final int GET_BATTERY_VOLTAGE = 0;
    public static final int GET_CAMERA_MANUFACTURER = 0;
    public static final int GET_MOTOR_FORCE = 0;
    public static final int GetICUBootAdr = 0;
    public static final int GetICUBootVersion = 0;
    public static final int GetICUFirmwareVersion = 0;
    public static final int GetICUHardwareVersion = 0;
    public static final int GetICUMachineVersion = 0;
    public static final int GetICUUUIDHigh = 0;
    public static final int GetICUUUIDLow = 0;
    public static final int GetIMUBootAdr = 0;
    public static final int GetIMUBootVersion = 0;
    public static final int GetIMUFirmwareVersion = 0;
    public static final int GetIMUHardwareVersion = 0;
    public static final int GetIMUMachineVersion = 0;
    public static final int GetIMUUUIDHigh = 0;
    public static final int GetIMUUUIDLow = 0;
    public static final int GetXMotorBootAdr = 0;
    public static final int GetXMotorBootVersion = 0;
    public static final int GetXMotorFirmwareVersion = 0;
    public static final int GetXMotorHardwareVersion = 0;
    public static final int GetXMotorMachineVersion = 0;
    public static final int GetXMotorUUIDHigh = 0;
    public static final int GetXMotorUUIDLow = 0;
    public static final int GetYMotorBootAdr = 0;
    public static final int GetYMotorBootVersion = 0;
    public static final int GetYMotorFirmwareVersion = 0;
    public static final int GetYMotorHardwareVersion = 0;
    public static final int GetYMotorMachineVersion = 0;
    public static final int GetYMotorUUIDHigh = 0;
    public static final int GetYMotorUUIDLow = 0;
    public static final int GetZMotorBootAdr = 0;
    public static final int GetZMotorBootVersion = 0;
    public static final int GetZMotorFirmwareVersion = 0;
    public static final int GetZMotorHardwareVersion = 0;
    public static final int GetZMotorMachineVersion = 0;
    public static final int GetZMotorUUIDHigh = 0;
    public static final int GetZMotorUUIDLow = 0;
    public static final int GyroStandardDeviation_R = 0;
    public static final int IMUAX_R = 0;
    public static final int IMUAY_R = 0;
    public static final int IMUAZ_R = 0;
    public static final int IMUControlRegister_R = 0;
    public static final int IMUControlRegister_W = 0;
    public static final int IMUGX_R = 0;
    public static final int IMUGY_R = 0;
    public static final int IMUGZ_R = 0;
    public static final int IMUStateRegister_R = 0;
    public static final int INTERACT_INVALID = 0;
    public static final int JOYSTICK_SPEED_R = 0;
    public static final int JOYSTICK_SPEED_W = 0;
    public static final int LOCATION_POINT_CONTROLLER = 0;
    public static final int LOCATION_POINT_STATE_REGISTER = 0;
    public static final int LOCATION_SET_POINT_POWERED = 0;
    public static final int MAKE_INFO_A = 0;
    public static final int MAKE_INFO_B = 0;
    public static final int MAKE_INFO_C = 0;
    public static final int MAKE_INFO_D = 0;
    public static final int MOTOR_PITCH_R = 0;
    public static final int MOTOR_PITCH_W = 0;
    public static final int MOTOR_ROLL_R = 0;
    public static final int MOTOR_ROLL_W = 0;
    public static final int MOTOR_YAW_R = 0;
    public static final int MOTOR_YAW_W = 0;
    public static final int MSC_PITCH_C = 0;
    public static final int MSC_PITCH_R = 0;
    public static final int MSC_PITCH_W = 0;
    public static final int MSC_ROLL_C = 0;
    public static final int MSC_ROLL_R = 0;
    public static final int MSC_ROLL_W = 0;
    public static final int MSC_YAW_C = 0;
    public static final int MSC_YAW_R = 0;
    public static final int MSC_YAW_W = 0;
    public static final int PHONE_CONTROL_MODE = 0;
    public static final int PITCH_ANGLE_R = 0;
    public static final int PITCH_CONTROL = 0;
    public static final int PITCH_CONTROL_MAX_RATE_R = 0;
    public static final int PITCH_CONTROL_MAX_RATE_W = 0;
    public static final int PITCH_DEADBAND_R = 0;
    public static final int PITCH_DEADBAND_W = 0;
    public static final int PITCH_FINE_TUNE_R = 0;
    public static final int PITCH_FINE_TUNE_W = 0;
    public static final int PITCH_FOLLOW_MAX_RATE_R = 0;
    public static final int PITCH_FOLLOW_MAX_RATE_W = 0;
    public static final int PITCH_ROTATE_ANGLE_CONTROL = 0;
    public static final int PITCH_SMOOTHNESS_R = 0;
    public static final int PITCH_SMOOTHNESS_W = 0;
    public static final int POINT_MOTION_TIME_HIGH_BIT = 0;
    public static final int POINT_MOTION_TIME_LOW_BIT = 0;
    public static final int PowerOff = 0;
    public static final int PowerOn = 0;
    public static final int Power_R = 0;
    public static final int Power_W = 0;
    public static final int ROCKER_DIRECTION_CONFIG_R = 0;
    public static final int ROCKER_DIRECTION_CONFIG_W = 0;
    public static final int ROLL_ANGLE_R = 0;
    public static final int ROLL_CONTROL = 0;
    public static final int ROLL_CONTROL_MAX_RATE_R = 0;
    public static final int ROLL_CONTROL_MAX_RATE_W = 0;
    public static final int ROLL_DEADBAND_R = 0;
    public static final int ROLL_DEADBAND_W = 0;
    public static final int ROLL_FINE_TUNE_R = 0;
    public static final int ROLL_FINE_TUNE_W = 0;
    public static final int ROLL_FOLLOW_MAX_RATE_R = 0;
    public static final int ROLL_FOLLOW_MAX_RATE_W = 0;
    public static final int ROLL_ROTATE_ANGLE_CONTROL = 0;
    public static final int ROLL_SMOOTHNESS_R = 0;
    public static final int ROLL_SMOOTHNESS_W = 0;
    public static final int SCENE_MODE_R = 0;
    public static final int SCENE_MODE_W = 0;
    public static final int SET_BUTTON_EVENT = 0;
    public static final int SET_CAMERA_MANUFACTURER = 0;
    public static final int SET_MOTOR_FORCE = 0;
    public static final int SWITCH_ORIENTATION = 0;
    public static final int SWITCH_ORIENTATION_PARAM_HORIZONTAL = 21930;
    public static final int SWITCH_ORIENTATION_PARAM_VERTICAL = 42405;
    public static final int Save;
    public static final int SysReset;
    public static final int TRACKING_PITCH;
    public static final int TRACKING_YAW;
    public static final int TRACK_SENSITIVITY;
    public static final int UPGRADABLE_DEVICE_ID;
    public static final int UPGRADABLE_MODULE_COUNT;
    public static final int UPGRADABLE_VERSION;
    public static final int VERSION_R;
    public static final int WORKING_STATE_R;
    public static final int WORK_MODE_CODE_R;
    public static final int WORK_MODE_CODE_W;
    public static final int XMOTOR_STATE_R;
    public static final int XMOTOR_VERSION_R;
    public static final int YAW_ANGLE_R;
    public static final int YAW_CONTROL;
    public static final int YAW_CONTROL_MAX_RATE_R;
    public static final int YAW_CONTROL_MAX_RATE_W;
    public static final int YAW_DEADBAND_R;
    public static final int YAW_DEADBAND_W;
    public static final int YAW_FOLLOW_MAX_RATE_R;
    public static final int YAW_FOLLOW_MAX_RATE_W;
    public static final int YAW_ROTATE_ANGLE_CONTROL;
    public static final int YAW_SMOOTHNESS_R;
    public static final int YAW_SMOOTHNESS_W;
    public static final int YMOTOR_STATE_R;
    public static final int YMOTOR_VERSION_R;
    public static final int ZMOTOR_STATE_R;
    public static final int ZMOTOR_VERSION_R;
    public static final int ZOOM_CONTROL;
    public static final int ZOOM_HIGH_16BIT;
    public static final int ZOOM_LOW_16BIT;
    public static final int ZOOM_VIRTUAL_POS;

    static {
        int n10 = 1;
        int n11 = 2;
        DEVICE_CATEGORY_R = h.h(0, n10, n11);
        int n12 = 4;
        VERSION_R = h.h(0, n10, n12);
        int n13 = 5;
        WORKING_STATE_R = h.h(0, n10, n13);
        GET_BATTERY_VOLTAGE = h.h(0, n10, 6);
        int n14 = 7;
        Power_R = h.h(0, n10, n14);
        int n15 = 128;
        Power_W = h.h(n15, n10, n14);
        int n16 = 9;
        Debug_R = h.h(0, n10, n16);
        Debug_W = h.h(n15, n10, n16);
        int n17 = 16;
        IMUControlRegister_R = h.h(0, n10, n17);
        IMUControlRegister_W = h.h(n15, n10, n17);
        int n18 = 17;
        IMUStateRegister_R = h.h(0, n10, n18);
        int n19 = 18;
        GyroStandardDeviation_R = h.h(0, n10, n19);
        IMUAX_R = h.h(0, n10, 28);
        IMUAY_R = h.h(0, n10, 29);
        IMUAZ_R = h.h(0, n10, 30);
        IMUGX_R = h.h(0, n10, 31);
        IMUGY_R = h.h(0, n10, 32);
        IMUGZ_R = h.h(0, n10, 33);
        PITCH_ANGLE_R = h.h(0, n10, 34);
        ROLL_ANGLE_R = h.h(0, n10, 35);
        YAW_ANGLE_R = h.h(0, n10, 36);
        PITCH_FINE_TUNE_R = h.h(0, n10, 37);
        PITCH_FINE_TUNE_W = h.h(n15, n10, 37);
        ROLL_FINE_TUNE_R = h.h(0, n10, 38);
        ROLL_FINE_TUNE_W = h.h(n15, n10, 38);
        WORK_MODE_CODE_R = h.h(0, n10, 39);
        WORK_MODE_CODE_W = h.h(n15, n10, 39);
        PITCH_DEADBAND_R = h.h(0, n10, 91);
        PITCH_DEADBAND_W = h.h(n15, n10, 91);
        ROLL_DEADBAND_R = h.h(0, n10, 92);
        ROLL_DEADBAND_W = h.h(n15, n10, 92);
        YAW_DEADBAND_R = h.h(0, n10, 93);
        YAW_DEADBAND_W = h.h(n15, n10, 93);
        PITCH_FOLLOW_MAX_RATE_R = h.h(0, n10, 94);
        PITCH_FOLLOW_MAX_RATE_W = h.h(n15, n10, 94);
        ROLL_FOLLOW_MAX_RATE_R = h.h(0, n10, 95);
        ROLL_FOLLOW_MAX_RATE_W = h.h(n15, n10, 95);
        int n20 = 96;
        YAW_FOLLOW_MAX_RATE_R = h.h(0, n10, n20);
        YAW_FOLLOW_MAX_RATE_W = h.h(n15, n10, n20);
        int n21 = 97;
        PITCH_SMOOTHNESS_R = h.h(0, n10, n21);
        PITCH_SMOOTHNESS_W = h.h(n15, n10, n21);
        int n22 = 98;
        ROLL_SMOOTHNESS_R = h.h(0, n10, n22);
        ROLL_SMOOTHNESS_W = h.h(n15, n10, n22);
        YAW_SMOOTHNESS_R = h.h(0, n10, 99);
        YAW_SMOOTHNESS_W = h.h(n15, n10, 99);
        PITCH_CONTROL_MAX_RATE_R = h.h(0, n10, 100);
        PITCH_CONTROL_MAX_RATE_W = h.h(n15, n10, 100);
        ROLL_CONTROL_MAX_RATE_R = h.h(0, n10, 101);
        ROLL_CONTROL_MAX_RATE_W = h.h(n15, n10, 101);
        YAW_CONTROL_MAX_RATE_R = h.h(0, n10, 102);
        YAW_CONTROL_MAX_RATE_W = h.h(n15, n10, 102);
        ROCKER_DIRECTION_CONFIG_R = h.h(0, n10, 103);
        ROCKER_DIRECTION_CONFIG_W = h.h(n15, n10, 103);
        GET_CAMERA_MANUFACTURER = h.h(0, n10, 104);
        SET_CAMERA_MANUFACTURER = h.h(n15, n10, 104);
        GET_MOTOR_FORCE = h.h(0, n10, 105);
        SET_MOTOR_FORCE = h.h(n15, n10, 105);
        XMOTOR_STATE_R = h.h(0, n11, n11);
        int n23 = 63;
        XMOTOR_VERSION_R = h.h(0, n11, n23);
        int n24 = 3;
        YMOTOR_STATE_R = h.h(0, n24, n11);
        YMOTOR_VERSION_R = h.h(0, n24, n23);
        ZMOTOR_STATE_R = h.h(0, n12, n11);
        ZMOTOR_VERSION_R = h.h(0, n12, n23);
        n23 = 192;
        PowerOn = h.h(n23, n10, n24);
        PowerOff = h.h(n23, n10, n12);
        Save = h.h(n23, n10, n13);
        SysReset = h.h(n23, n10, n14);
        GetIMUBootAdr = h.h(n23, n10, n17);
        GetIMUMachineVersion = h.h(n23, n10, n18);
        GetIMUBootVersion = h.h(n23, n10, n19);
        n16 = 19;
        GetIMUHardwareVersion = h.h(n23, n10, n16);
        n14 = 20;
        GetIMUUUIDLow = h.h(n23, n10, n14);
        n22 = 21;
        GetIMUUUIDHigh = h.h(n23, n10, n22);
        n21 = 22;
        GetIMUFirmwareVersion = h.h(n23, n10, n21);
        GetXMotorBootAdr = h.h(n23, n11, n17);
        GetXMotorMachineVersion = h.h(n23, n11, n18);
        GetXMotorBootVersion = h.h(n23, n11, n19);
        GetXMotorHardwareVersion = h.h(n23, n11, n16);
        GetXMotorUUIDLow = h.h(n23, n11, n14);
        GetXMotorUUIDHigh = h.h(n23, n11, n22);
        GetXMotorFirmwareVersion = h.h(n23, n11, n21);
        GetYMotorBootAdr = h.h(n23, n24, n17);
        GetYMotorMachineVersion = h.h(n23, n24, n18);
        GetYMotorBootVersion = h.h(n23, n24, n19);
        GetYMotorHardwareVersion = h.h(n23, n24, n16);
        GetYMotorUUIDLow = h.h(n23, n24, n14);
        GetYMotorUUIDHigh = h.h(n23, n24, n22);
        GetYMotorFirmwareVersion = h.h(n23, n24, n21);
        GetZMotorBootAdr = h.h(n23, n12, n17);
        GetZMotorMachineVersion = h.h(n23, n12, n18);
        GetZMotorBootVersion = h.h(n23, n12, n19);
        GetZMotorHardwareVersion = h.h(n23, n12, n16);
        GetZMotorUUIDLow = h.h(n23, n12, n14);
        GetZMotorUUIDHigh = h.h(n23, n12, n22);
        GetZMotorFirmwareVersion = h.h(n23, n12, n21);
        GetICUBootAdr = h.h(n23, n12, n17);
        GetICUMachineVersion = h.h(n23, n12, n18);
        GetICUBootVersion = h.h(n23, n12, n19);
        GetICUHardwareVersion = h.h(n23, n12, n16);
        GetICUUUIDLow = h.h(n23, n12, n14);
        GetICUUUIDHigh = h.h(n23, n12, n22);
        GetICUFirmwareVersion = h.h(n23, n12, n21);
        FUNCTION_EVENT = h.h(n23, n10, 33);
        SET_BUTTON_EVENT = h.h(n23, n10, 32);
        PHONE_CONTROL_MODE = h.h(n23, n10, 56);
        PITCH_CONTROL = h.h(n17, 0, n10);
        ROLL_CONTROL = h.h(n17, 0, n11);
        YAW_CONTROL = h.h(n17, 0, n24);
        FOCUS_CONTROL = h.h(n17, 0, n12);
        ZOOM_CONTROL = h.h(n17, 0, n13);
        n11 = 64;
        UPGRADABLE_MODULE_COUNT = h.h(n11, n10, n15);
        UPGRADABLE_DEVICE_ID = h.h(n11, n10, 129);
        UPGRADABLE_VERSION = h.h(n11, n10, 130);
        FF_LOW_16BIT = h.h(n11, n10, 80);
        FF_HIGH_16BIT = h.h(n11, n10, 81);
        FF_VIRTUAL_POS = h.h(n11, n10, 82);
        ZOOM_LOW_16BIT = h.h(n11, n10, n20);
        ZOOM_HIGH_16BIT = h.h(n11, n10, 97);
        ZOOM_VIRTUAL_POS = h.h(n11, n10, 98);
        LOCATION_SET_POINT_POWERED = h.h(n23, n10, 48);
        LOCATION_POINT_CONTROLLER = h.h(n23, n10, 49);
        LOCATION_POINT_STATE_REGISTER = h.h(n23, n10, 50);
        PITCH_ROTATE_ANGLE_CONTROL = h.h(n23, n10, 51);
        ROLL_ROTATE_ANGLE_CONTROL = h.h(n23, n10, 52);
        YAW_ROTATE_ANGLE_CONTROL = h.h(n23, n10, 53);
        POINT_MOTION_TIME_LOW_BIT = h.h(n23, n10, 54);
        POINT_MOTION_TIME_HIGH_BIT = h.h(n23, n10, 55);
        JOYSTICK_SPEED_R = h.h(n11, n10, 162);
        JOYSTICK_SPEED_W = h.h(n23, n10, 162);
        SCENE_MODE_R = h.h(n11, n10, 163);
        SCENE_MODE_W = h.h(n23, n10, 163);
        TRACK_SENSITIVITY = h.h(n23, n10, 164);
        DEMO_MODE_W = h.h(n23, n10, 71);
        DEMO_MODE_R = h.h(n11, n10, 71);
        MAKE_INFO_A = h.h(0, n10, 124);
        MAKE_INFO_B = h.h(0, n10, 125);
        MAKE_INFO_C = h.h(0, n10, 126);
        MAKE_INFO_D = h.h(0, n10, 127);
        INTERACT_INVALID = h.h(0, 0, 0);
        MSC_PITCH_R = h.h(n11, n10, 112);
        MSC_PITCH_W = h.h(n23, n10, 112);
        MSC_PITCH_C = h.h(n17, n10, 6);
        MSC_ROLL_R = h.h(n11, n10, 113);
        MSC_ROLL_W = h.h(n23, n10, 113);
        MSC_ROLL_C = h.h(n17, n10, 7);
        MSC_YAW_R = h.h(n11, n10, 114);
        MSC_YAW_W = h.h(n23, n10, 114);
        MSC_YAW_C = h.h(n17, n10, 8);
        TRACKING_PITCH = h.h(n17, 0, 9);
        TRACKING_YAW = h.h(n17, 0, 10);
        CAMERA_ZOOM = h.h(n17, 0, 11);
        CALIBRATION_QUICK = h.h(n23, n10, 160);
        SWITCH_ORIENTATION = h.h(n23, n10, 161);
        MOTOR_PITCH_R = h.h(n11, n10, 144);
        MOTOR_PITCH_W = h.h(n23, n10, 144);
        MOTOR_ROLL_R = h.h(n11, n10, 145);
        MOTOR_ROLL_W = h.h(n23, n10, 145);
        MOTOR_YAW_R = h.h(n11, n10, 146);
        MOTOR_YAW_W = h.h(n23, n10, 146);
    }
}

