/*
 * Decompiled with CFR 0.151.
 */
package com.zhiyun.protocol.core.entities;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.zhiyun.protocol.constants.Active;
import com.zhiyun.protocol.constants.CameraManufacturer;
import com.zhiyun.protocol.constants.ConnectionMethod;
import com.zhiyun.protocol.constants.JoystickSpeed;
import com.zhiyun.protocol.constants.SceneMode;
import com.zhiyun.protocol.constants.Strength;
import com.zhiyun.protocol.constants.WorkingMode;
import com.zhiyun.protocol.core.entities.MoveLimit;
import com.zhiyun.protocol.core.entities.MoveLine;
import com.zhiyun.protocol.core.entities.Preset;
import com.zhiyun.protocol.core.entities.Preset$Row;
import com.zhiyun.protocol.core.entities.PresetLimit;
import com.zhiyun.protocol.core.entities.PresetLimit$Row;
import com.zhiyun.protocol.core.entities.StoryAttribute;
import com.zhiyun.protocol.core.entities.StoryAttribute$Precision;
import com.zhiyun.protocol.core.entities.StrengthLimit;
import d.v.y.d.i;
import java.util.Arrays;
import java.util.List;

public class Functions {
    public int accessory;
    public Active activate;
    public byte[] activateKey;
    public int autoTune;
    public int battery;
    public int bhTest;
    public int bleHid;
    public int bleMtu;
    public int calibration;
    public List cameraList;
    public int carry;
    public int ccs;
    public int digitalZoom;
    public int forceVersion;
    public int hvSwitch;
    public int identifier;
    public List joystickSpeed;
    public int jsonData;
    public List keyRedefine;
    public ConnectionMethod links;
    public int motionControl;
    public List motorStrength;
    public int motorStrengthAdjustNotify;
    public MoveLimit moveLimit;
    public MoveLine moveline;
    public int oem;
    public int photo;
    public List preset;
    public PresetLimit presetLimit;
    public int resetMethod;
    public List sceneModes;
    public int showmode;
    public StoryAttribute storyAttribute;
    public int storyMode;
    public StrengthLimit strengthLimit;
    public int tracking;
    public int update;
    public int video;
    public int wifiChannel;
    public int wifiModel;
    public List workingModes;

    public Functions() {
        int n10;
        this.battery = n10 = 1;
        Object object = 0;
        this.ccs = 0;
        this.update = 0;
        this.motionControl = 0;
        this.photo = 0;
        this.video = 0;
        this.digitalZoom = 0;
        Object object2 = new MoveLine();
        this.moveline = object2;
        this.jsonData = 0;
        object2 = ConnectionMethod.BLE;
        this.links = object2;
        this.carry = 0;
        this.accessory = 0;
        this.bleMtu = 20;
        this.bleHid = 0;
        this.tracking = 0;
        this.oem = 0;
        this.autoTune = 0;
        this.wifiChannel = 0;
        this.wifiModel = 0;
        this.bhTest = 0;
        this.calibration = 0;
        this.resetMethod = 0;
        object2 = Active.NONE;
        this.activate = object2;
        this.activateKey = null;
        this.storyMode = 0;
        float f10 = 0.01f;
        int n11 = 30000;
        Object object3 = new StoryAttribute$Precision(f10, n11);
        Object object4 = new StoryAttribute$Precision(f10, n11);
        Object object5 = new StoryAttribute$Precision(f10, n11);
        Object object6 = object2;
        super(false, false, (StoryAttribute$Precision)object3, (StoryAttribute$Precision)object4, (StoryAttribute$Precision)object5);
        this.storyAttribute = object2;
        super();
        this.keyRedefine = object2;
        this.hvSwitch = 0;
        int n12 = 3;
        object6 = new WorkingMode[n12];
        Object object7 = WorkingMode.PF;
        object6[0] = object7;
        object7 = WorkingMode.L;
        object6[n10] = object7;
        object7 = WorkingMode.F;
        int n13 = 2;
        object6[n13] = object7;
        this.workingModes = object6 = Arrays.asList(object6);
        object6 = new Strength[n12];
        object7 = Strength.LOW;
        object6[0] = object7;
        object7 = Strength.MEDIUM;
        object6[n10] = object7;
        object7 = Strength.HIGH;
        object6[n13] = object7;
        this.motorStrength = object6 = Arrays.asList(object6);
        object6 = new CameraManufacturer[4];
        object7 = CameraManufacturer.CLOSE;
        object6[0] = object7;
        object7 = CameraManufacturer.CANON;
        object6[n10] = object7;
        object7 = CameraManufacturer.SONY;
        object6[n13] = object7;
        object7 = CameraManufacturer.PANASONIC;
        object6[n12] = object7;
        object2 = Arrays.asList(object6);
        this.cameraList = object2;
        object6 = -90;
        object7 = 90;
        object6 = i.d((Comparable)object6, (Comparable)object7);
        object7 = -45;
        int n14 = 45;
        object4 = n14;
        object7 = i.d((Comparable)object7, (Comparable)object4);
        object4 = -180;
        object5 = 180;
        object4 = i.d((Comparable)object4, (Comparable)object5);
        super((i)object6, (i)object7, (i)object4);
        this.moveLimit = object2;
        super();
        this.strengthLimit = object2;
        this.motorStrengthAdjustNotify = 0;
        object2 = new JoystickSpeed[n10];
        object2[0] = object6 = JoystickSpeed.VALUE;
        this.joystickSpeed = object2 = Arrays.asList(object2);
        object2 = new SceneMode[n10];
        object2[0] = object6 = SceneMode.RUN;
        this.sceneModes = object2 = Arrays.asList(object2);
        object2 = new Preset[n13];
        n13 = 80;
        int n15 = 25;
        int n16 = 100;
        Integer n17 = n16;
        float f11 = 2.0f;
        object7 = new Preset$Row(n13, n15, n16, f11);
        float f12 = 5.0f;
        Preset$Row preset$Row = new Preset$Row(n13, n15, n16, f12);
        object4 = new Preset$Row(n13, n14, n16, f12);
        super((Preset$Row)object7, preset$Row, (Preset$Row)object4);
        object2[0] = object6;
        n11 = 120;
        Object object8 = n11;
        n14 = 200;
        object4 = n14;
        super(n11, n16, n14, f11);
        Object object9 = new Preset$Row(n11, n16, n14, f12);
        preset$Row = new Preset$Row(n11, n16, n14, f12);
        Object object10 = new Preset((Preset$Row)object6, (Preset$Row)object9, preset$Row);
        object2[n10] = object10;
        Object object11 = Arrays.asList(object2);
        this.preset = object11;
        object2 = i.d((Comparable)object, (Comparable)object8);
        object6 = i.d((Comparable)object, n17);
        object7 = i.d((Comparable)object, (Comparable)object4);
        object3 = 30;
        object5 = i.d((Comparable)object, (Comparable)object3);
        object10 = new PresetLimit$Row((i)object2, (i)object6, (i)object7, (i)object5);
        object6 = i.d((Comparable)object, (Comparable)object8);
        object7 = i.d((Comparable)object, n17);
        object5 = i.d((Comparable)object, (Comparable)object4);
        object9 = i.d((Comparable)object, (Comparable)object3);
        super((i)object6, (i)object7, (i)object5, (i)object9);
        object7 = i.d((Comparable)object, (Comparable)object8);
        object8 = i.d((Comparable)object, n17);
        object4 = i.d((Comparable)object, (Comparable)object4);
        object = i.d((Comparable)object, (Comparable)object3);
        super((i)object7, (i)object8, (i)object4, (i)object);
        this.presetLimit = object11 = new PresetLimit((PresetLimit$Row)object10, (PresetLimit$Row)object2, (PresetLimit$Row)object6);
    }

    public static Functions fromJson(Gson gson, String string2) {
        return (Functions)gson.fromJson(string2, Functions.class);
    }

    public static Functions fromJson(String string2) {
        GsonBuilder gsonBuilder = new GsonBuilder();
        return Functions.fromJson(gsonBuilder.create(), string2);
    }

    public void set(Functions object) {
        Object object2;
        int n10;
        this.battery = n10 = ((Functions)object).battery;
        this.ccs = n10 = ((Functions)object).ccs;
        this.update = n10 = ((Functions)object).update;
        this.motionControl = n10 = ((Functions)object).motionControl;
        this.photo = n10 = ((Functions)object).photo;
        this.video = n10 = ((Functions)object).video;
        this.digitalZoom = n10 = ((Functions)object).digitalZoom;
        this.moveline = object2 = ((Functions)object).moveline;
        this.jsonData = n10 = ((Functions)object).jsonData;
        object2 = ((Functions)object).links;
        this.links = object2;
        this.carry = n10 = ((Functions)object).carry;
        this.bleMtu = n10 = ((Functions)object).bleMtu;
        this.bleHid = n10 = ((Functions)object).bleHid;
        this.tracking = n10 = ((Functions)object).tracking;
        this.oem = n10 = ((Functions)object).oem;
        this.autoTune = n10 = ((Functions)object).autoTune;
        this.wifiChannel = n10 = ((Functions)object).wifiChannel;
        this.wifiModel = n10 = ((Functions)object).wifiModel;
        this.bhTest = n10 = ((Functions)object).bhTest;
        this.calibration = n10 = ((Functions)object).calibration;
        this.resetMethod = n10 = ((Functions)object).resetMethod;
        object2 = ((Functions)object).activate;
        this.activate = object2;
        object2 = ((Functions)object).activateKey;
        this.activateKey = (byte[])object2;
        this.identifier = n10 = ((Functions)object).identifier;
        this.storyMode = n10 = ((Functions)object).storyMode;
        object2 = ((Functions)object).storyAttribute;
        this.storyAttribute = object2;
        object2 = ((Functions)object).keyRedefine;
        this.keyRedefine = object2;
        this.motorStrengthAdjustNotify = n10 = ((Functions)object).motorStrengthAdjustNotify;
        this.hvSwitch = n10 = ((Functions)object).hvSwitch;
        this.forceVersion = n10 = ((Functions)object).forceVersion;
        object2 = ((Functions)object).workingModes;
        this.workingModes = object2;
        object2 = ((Functions)object).motorStrength;
        this.motorStrength = object2;
        object2 = ((Functions)object).cameraList;
        this.cameraList = object2;
        object2 = ((Functions)object).moveLimit;
        this.moveLimit = object2;
        object2 = ((Functions)object).strengthLimit;
        this.strengthLimit = object2;
        object2 = ((Functions)object).joystickSpeed;
        this.joystickSpeed = object2;
        object2 = ((Functions)object).sceneModes;
        this.sceneModes = object2;
        object2 = ((Functions)object).preset;
        this.preset = object2;
        this.presetLimit = object = ((Functions)object).presetLimit;
    }

    public String toString() {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("Functions{battery=");
        int n10 = this.battery;
        stringBuilder.append(n10);
        stringBuilder.append(", ccs=");
        n10 = this.ccs;
        stringBuilder.append(n10);
        stringBuilder.append(", update=");
        n10 = this.update;
        stringBuilder.append(n10);
        stringBuilder.append(", motionControl=");
        n10 = this.motionControl;
        stringBuilder.append(n10);
        stringBuilder.append(", photo=");
        n10 = this.photo;
        stringBuilder.append(n10);
        stringBuilder.append(", video=");
        n10 = this.video;
        stringBuilder.append(n10);
        stringBuilder.append(", digitalZoom=");
        n10 = this.digitalZoom;
        stringBuilder.append(n10);
        stringBuilder.append(", moveline=");
        Object object = this.moveline;
        stringBuilder.append(object);
        stringBuilder.append(", jsonData=");
        n10 = this.jsonData;
        stringBuilder.append(n10);
        stringBuilder.append(", links=");
        object = this.links;
        stringBuilder.append(object);
        stringBuilder.append(", carry=");
        n10 = this.carry;
        stringBuilder.append(n10);
        stringBuilder.append(", accessory=");
        n10 = this.accessory;
        stringBuilder.append(n10);
        stringBuilder.append(", bleMtu=");
        n10 = this.bleMtu;
        stringBuilder.append(n10);
        stringBuilder.append(", bleHid=");
        n10 = this.bleHid;
        stringBuilder.append(n10);
        stringBuilder.append(", tracking=");
        n10 = this.tracking;
        stringBuilder.append(n10);
        stringBuilder.append(", oem=");
        n10 = this.oem;
        stringBuilder.append(n10);
        stringBuilder.append(", autoTune=");
        n10 = this.autoTune;
        stringBuilder.append(n10);
        stringBuilder.append(", wifiChannel=");
        n10 = this.wifiChannel;
        stringBuilder.append(n10);
        stringBuilder.append(", wifiModel=");
        n10 = this.wifiModel;
        stringBuilder.append(n10);
        stringBuilder.append(", bhTest=");
        n10 = this.bhTest;
        stringBuilder.append(n10);
        stringBuilder.append(", calibration=");
        n10 = this.calibration;
        stringBuilder.append(n10);
        stringBuilder.append(", resetMethod=");
        n10 = this.resetMethod;
        stringBuilder.append(n10);
        stringBuilder.append(", activate=");
        object = this.activate;
        stringBuilder.append(object);
        stringBuilder.append(", activateKey len='");
        n10 = this.activateKey.length;
        stringBuilder.append(n10);
        stringBuilder.append('\'');
        stringBuilder.append(", identifier=");
        n10 = this.identifier;
        stringBuilder.append(n10);
        stringBuilder.append(", storyMode=");
        n10 = this.storyMode;
        stringBuilder.append(n10);
        stringBuilder.append(", storyAttribute=");
        object = this.storyAttribute;
        stringBuilder.append(object);
        stringBuilder.append(", keyRedefine=");
        object = this.keyRedefine;
        stringBuilder.append(object);
        stringBuilder.append(", hvSwitch=");
        n10 = this.hvSwitch;
        stringBuilder.append(n10);
        stringBuilder.append(", forceVersion=");
        n10 = this.forceVersion;
        stringBuilder.append(n10);
        stringBuilder.append(", workingModes=");
        object = this.workingModes;
        stringBuilder.append(object);
        stringBuilder.append(", motorStrength=");
        object = this.motorStrength;
        stringBuilder.append(object);
        stringBuilder.append(", cameraList=");
        object = this.cameraList;
        stringBuilder.append(object);
        stringBuilder.append(", moveLimit=");
        object = this.moveLimit;
        stringBuilder.append(object);
        stringBuilder.append(", strengthLimit=");
        object = this.strengthLimit;
        stringBuilder.append(object);
        stringBuilder.append(", motorStrengthAdjustNotify=");
        n10 = this.motorStrengthAdjustNotify;
        stringBuilder.append(n10);
        stringBuilder.append(", joystickSpeed=");
        object = this.joystickSpeed;
        stringBuilder.append(object);
        stringBuilder.append(", sceneModes=");
        object = this.sceneModes;
        stringBuilder.append(object);
        stringBuilder.append(", preset=");
        object = this.preset;
        stringBuilder.append(object);
        stringBuilder.append(", presetLimit=");
        object = this.presetLimit;
        stringBuilder.append(object);
        stringBuilder.append('}');
        return stringBuilder.toString();
    }
}

